apiVersion: margo.org/v1alpha1
kind: ApplicationDeployment
metadata:
  name: compose-sample
  annotations:
    id: 11111111-1111-1111-1111-111111111111
spec:
  appPackageRef:
    id: compose-sample
  deploymentProfile:
    type: compose
    components:
      - name: compose-sample
        properties:
          packageLocation: /home/margo/nitin/sandbox/docker-compose/docker-compose-sample.yaml
          wait: true