apiVersion: margo.org/v1alpha1
kind: ApplicationDeployment
metadata:
  name: compose-sample
  annotations:
    id: a7f3c9d2-4b8e-1a6f-9c3d-5e7b2f8a1c4e
spec:
  appPackageRef:
    id: compose-sample
  deploymentProfile:
    type: compose
    components:
      - name: compose-sample
        properties:
          packageLocation: https://raw.githubusercontent.com/nginx-proxy/nginx-proxy/refs/heads/main/docker-compose.yml
          wait: true