# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

project_name: margo-sandbox

before:
  hooks:
    - go mod tidy
    - go mod download

builds:
  - id: "linux-amd64"
    main: ./poc/device/agent
    # Binary name.
    # Can be a path (e.g. `bin/app`).
    binary: device-agent
    flags:
      - -trimpath
    ldflags:
      - -X main.build={{.Version}} -X main.commit={{.Commit}} -X
        main.date={{.CommitDate}}
    goos:
      - linux
    goarch:
      - amd64
      - arm64

dockers_v2:
  - images:
      - "ghcr.io/margo/workload-fleet-management-client"
    dockerfile: ./poc/device/agent/Dockerfile
    platforms:
      - linux/amd64
      - linux/arm64
    flags:
      - "--network=host"
    build_args:
      VERSION: "{{.Version}}"
      DATE: "{{.CommitDate}}"
      COMMIT: "{{.Commit}}"
    labels:
      org.opencontainers.image.title: "{{.ProjectName}}"
      org.opencontainers.image.description: "Margo sandbox workload fleet management
        client. A reference implementation."
      org.opencontainers.image.source: "{{.GitURL}}"
      org.opencontainers.image.version: "{{.Version}}"
      org.opencontainers.image.revision: "{{.FullCommit}}"
      org.opencontainers.image.created: "{{.CommitDate}}"
    extra_files:
      - go.mod
      - go.sum
      - poc/
      - standard/
      - non-standard/
      - shared-lib/

report_sizes: true

archives:
  - formats:
      - tar.gz
    name_template: "{{.ProjectName}}_{{.Version}}_{{.Os}}-{{.Arch}}"
    wrap_in_directory: device-agent   
    files:
      - LICENSE
      - src: docs/binary-getting-started.md
        dst: BINARY_GETTING_STARTED.md
      - src: poc/device/agent/config
+       dst: config

checksum:
  name_template: "{{.ProjectName}}_checksums.txt"

changelog:
  use: github-native

release:
  make_latest: true
  header: |
    ## This release targets the Margo spec version: {{.Env.MARGO_SPEC_VERSION}}, which can be tracked here, https://github.com/margo/specification .
  footer: |
    **Full Changelog**: https://github.com/margo/sandbox/compare/{{ .PreviousTag }}...{{ .Tag }}
  github:
    owner: margo
    name: sandbox
  disable: false

