apiVersion: margo.org/v1alpha1
kind: ApplicationDeployment
metadata:
  name: {{deploymentId}}
  annotations:
    id: {{deploymentId}}
spec:
  appPackageRef:
    id: compose-sample
  deploymentProfile:
    type: compose
    components:
      - name: compose-sample
        properties:
          packageLocation: https://raw.githubusercontent.com/nginx-proxy/nginx-proxy/refs/heads/main/docker-compose.yml
          wait: true
