// Code generated by ogen, DO NOT EDIT.

package api

import (
	"bytes"
	"io"
	"mime"
	"net/http"

	"github.com/go-faster/errors"
	"github.com/go-faster/jx"
	"github.com/ogen-go/ogen/conv"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/uri"
	"github.com/ogen-go/ogen/validate"
)

func decodeAPIV1ClientsClientIdBundlesDigestGetResponse(resp *http.Response) (res APIV1ClientsClientIdBundlesDigestGetRes, _ error) {
	switch resp.StatusCode {
	case 200:
		// Code 200.
		ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
		if err != nil {
			return res, errors.Wrap(err, "parse media type")
		}
		switch {
		case ct == "application/vnd.margo.bundle.v1+tar+gzip":
			reader := resp.Body
			b, err := io.ReadAll(reader)
			if err != nil {
				return res, err
			}

			response := APIV1ClientsClientIdBundlesDigestGetOK{Data: bytes.NewReader(b)}
			var wrapper APIV1ClientsClientIdBundlesDigestGetOKHeaders
			wrapper.Response = response
			h := uri.NewHeaderDecoder(resp.Header)
			// Parse "Cache-Control" header.
			{
				cfg := uri.HeaderParameterDecodingConfig{
					Name:    "Cache-Control",
					Explode: false,
				}
				if err := func() error {
					if err := h.HasParam(cfg); err == nil {
						if err := h.DecodeParam(cfg, func(d uri.Decoder) error {
							var wrapperDotCacheControlVal string
							if err := func() error {
								val, err := d.DecodeValue()
								if err != nil {
									return err
								}

								c, err := conv.ToString(val)
								if err != nil {
									return err
								}

								wrapperDotCacheControlVal = c
								return nil
							}(); err != nil {
								return err
							}
							wrapper.CacheControl.SetTo(wrapperDotCacheControlVal)
							return nil
						}); err != nil {
							return err
						}
					}
					return nil
				}(); err != nil {
					return res, errors.Wrap(err, "parse Cache-Control header")
				}
			}
			// Parse "ETag" header.
			{
				cfg := uri.HeaderParameterDecodingConfig{
					Name:    "ETag",
					Explode: false,
				}
				if err := func() error {
					if err := h.HasParam(cfg); err == nil {
						if err := h.DecodeParam(cfg, func(d uri.Decoder) error {
							var wrapperDotETagVal string
							if err := func() error {
								val, err := d.DecodeValue()
								if err != nil {
									return err
								}

								c, err := conv.ToString(val)
								if err != nil {
									return err
								}

								wrapperDotETagVal = c
								return nil
							}(); err != nil {
								return err
							}
							wrapper.ETag.SetTo(wrapperDotETagVal)
							return nil
						}); err != nil {
							return err
						}
					}
					return nil
				}(); err != nil {
					return res, errors.Wrap(err, "parse ETag header")
				}
			}
			return &wrapper, nil
		default:
			return res, validate.InvalidContentType(ct)
		}
	case 304:
		// Code 304.
		return &APIV1ClientsClientIdBundlesDigestGetNotModified{}, nil
	case 400:
		// Code 400.
		return &APIV1ClientsClientIdBundlesDigestGetBadRequest{}, nil
	case 404:
		// Code 404.
		return &APIV1ClientsClientIdBundlesDigestGetNotFound{}, nil
	}
	return res, validate.UnexpectedStatusCodeWithResponse(resp)
}

func decodeAPIV1ClientsClientIdCapabilitiesPostResponse(resp *http.Response) (res APIV1ClientsClientIdCapabilitiesPostRes, _ error) {
	switch resp.StatusCode {
	case 201:
		// Code 201.
		return &APIV1ClientsClientIdCapabilitiesPostCreated{}, nil
	case 400:
		// Code 400.
		return &APIV1ClientsClientIdCapabilitiesPostBadRequest{}, nil
	case 401:
		// Code 401.
		return &APIV1ClientsClientIdCapabilitiesPostUnauthorized{}, nil
	case 403:
		// Code 403.
		return &APIV1ClientsClientIdCapabilitiesPostForbidden{}, nil
	case 422:
		// Code 422.
		return &APIV1ClientsClientIdCapabilitiesPostUnprocessableEntity{}, nil
	}
	return res, validate.UnexpectedStatusCodeWithResponse(resp)
}

func decodeAPIV1ClientsClientIdCapabilitiesPutResponse(resp *http.Response) (res APIV1ClientsClientIdCapabilitiesPutRes, _ error) {
	switch resp.StatusCode {
	case 201:
		// Code 201.
		return &APIV1ClientsClientIdCapabilitiesPutCreated{}, nil
	case 400:
		// Code 400.
		return &APIV1ClientsClientIdCapabilitiesPutBadRequest{}, nil
	case 401:
		// Code 401.
		return &APIV1ClientsClientIdCapabilitiesPutUnauthorized{}, nil
	case 403:
		// Code 403.
		return &APIV1ClientsClientIdCapabilitiesPutForbidden{}, nil
	case 422:
		// Code 422.
		return &APIV1ClientsClientIdCapabilitiesPutUnprocessableEntity{}, nil
	}
	return res, validate.UnexpectedStatusCodeWithResponse(resp)
}

func decodeAPIV1ClientsClientIdDeploymentsDeploymentIdDigestGetResponse(resp *http.Response) (res APIV1ClientsClientIdDeploymentsDeploymentIdDigestGetRes, _ error) {
	switch resp.StatusCode {
	case 200:
		// Code 200.
		ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
		if err != nil {
			return res, errors.Wrap(err, "parse media type")
		}
		switch {
		case ct == "application/yaml":
			reader := resp.Body
			b, err := io.ReadAll(reader)
			if err != nil {
				return res, err
			}

			response := APIV1ClientsClientIdDeploymentsDeploymentIdDigestGetOK{Data: bytes.NewReader(b)}
			var wrapper APIV1ClientsClientIdDeploymentsDeploymentIdDigestGetOKHeaders
			wrapper.Response = response
			h := uri.NewHeaderDecoder(resp.Header)
			// Parse "Cache-Control" header.
			{
				cfg := uri.HeaderParameterDecodingConfig{
					Name:    "Cache-Control",
					Explode: false,
				}
				if err := func() error {
					if err := h.HasParam(cfg); err == nil {
						if err := h.DecodeParam(cfg, func(d uri.Decoder) error {
							var wrapperDotCacheControlVal string
							if err := func() error {
								val, err := d.DecodeValue()
								if err != nil {
									return err
								}

								c, err := conv.ToString(val)
								if err != nil {
									return err
								}

								wrapperDotCacheControlVal = c
								return nil
							}(); err != nil {
								return err
							}
							wrapper.CacheControl.SetTo(wrapperDotCacheControlVal)
							return nil
						}); err != nil {
							return err
						}
					}
					return nil
				}(); err != nil {
					return res, errors.Wrap(err, "parse Cache-Control header")
				}
			}
			// Parse "ETag" header.
			{
				cfg := uri.HeaderParameterDecodingConfig{
					Name:    "ETag",
					Explode: false,
				}
				if err := func() error {
					if err := h.HasParam(cfg); err == nil {
						if err := h.DecodeParam(cfg, func(d uri.Decoder) error {
							var wrapperDotETagVal string
							if err := func() error {
								val, err := d.DecodeValue()
								if err != nil {
									return err
								}

								c, err := conv.ToString(val)
								if err != nil {
									return err
								}

								wrapperDotETagVal = c
								return nil
							}(); err != nil {
								return err
							}
							wrapper.ETag.SetTo(wrapperDotETagVal)
							return nil
						}); err != nil {
							return err
						}
					}
					return nil
				}(); err != nil {
					return res, errors.Wrap(err, "parse ETag header")
				}
			}
			// Parse "Vary" header.
			{
				cfg := uri.HeaderParameterDecodingConfig{
					Name:    "Vary",
					Explode: false,
				}
				if err := func() error {
					if err := h.HasParam(cfg); err == nil {
						if err := h.DecodeParam(cfg, func(d uri.Decoder) error {
							var wrapperDotVaryVal string
							if err := func() error {
								val, err := d.DecodeValue()
								if err != nil {
									return err
								}

								c, err := conv.ToString(val)
								if err != nil {
									return err
								}

								wrapperDotVaryVal = c
								return nil
							}(); err != nil {
								return err
							}
							wrapper.Vary.SetTo(wrapperDotVaryVal)
							return nil
						}); err != nil {
							return err
						}
					}
					return nil
				}(); err != nil {
					return res, errors.Wrap(err, "parse Vary header")
				}
			}
			return &wrapper, nil
		default:
			return res, validate.InvalidContentType(ct)
		}
	case 404:
		// Code 404.
		return &APIV1ClientsClientIdDeploymentsDeploymentIdDigestGetNotFound{}, nil
	}
	return res, validate.UnexpectedStatusCodeWithResponse(resp)
}

func decodeAPIV1ClientsClientIdDeploymentsDeploymentIdStatusPostResponse(resp *http.Response) (res APIV1ClientsClientIdDeploymentsDeploymentIdStatusPostRes, _ error) {
	switch resp.StatusCode {
	case 200:
		// Code 200.
		return &APIV1ClientsClientIdDeploymentsDeploymentIdStatusPostOK{}, nil
	case 400:
		// Code 400.
		return &APIV1ClientsClientIdDeploymentsDeploymentIdStatusPostBadRequest{}, nil
	case 401:
		// Code 401.
		return &APIV1ClientsClientIdDeploymentsDeploymentIdStatusPostUnauthorized{}, nil
	case 403:
		// Code 403.
		return &APIV1ClientsClientIdDeploymentsDeploymentIdStatusPostForbidden{}, nil
	case 422:
		// Code 422.
		return &APIV1ClientsClientIdDeploymentsDeploymentIdStatusPostUnprocessableEntity{}, nil
	}
	return res, validate.UnexpectedStatusCodeWithResponse(resp)
}

func decodeAPIV1ClientsClientIdDeploymentsGetResponse(resp *http.Response) (res APIV1ClientsClientIdDeploymentsGetRes, _ error) {
	switch resp.StatusCode {
	case 200:
		// Code 200.
		ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
		if err != nil {
			return res, errors.Wrap(err, "parse media type")
		}
		switch {
		case ct == "application/vnd.margo.manifest.v1+json":
			buf, err := io.ReadAll(resp.Body)
			if err != nil {
				return res, err
			}
			d := jx.DecodeBytes(buf)

			var response UnsignedAppStateManifest
			if err := func() error {
				if err := response.Decode(d); err != nil {
					return err
				}
				if err := d.Skip(); err != io.EOF {
					return errors.New("unexpected trailing data")
				}
				return nil
			}(); err != nil {
				err = &ogenerrors.DecodeBodyError{
					ContentType: ct,
					Body:        buf,
					Err:         err,
				}
				return res, err
			}
			// Validate response.
			if err := func() error {
				if err := response.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return res, errors.Wrap(err, "validate")
			}
			var wrapper UnsignedAppStateManifestHeaders
			wrapper.Response = response
			h := uri.NewHeaderDecoder(resp.Header)
			// Parse "ETag" header.
			{
				cfg := uri.HeaderParameterDecodingConfig{
					Name:    "ETag",
					Explode: false,
				}
				if err := func() error {
					if err := h.HasParam(cfg); err == nil {
						if err := h.DecodeParam(cfg, func(d uri.Decoder) error {
							var wrapperDotETagVal string
							if err := func() error {
								val, err := d.DecodeValue()
								if err != nil {
									return err
								}

								c, err := conv.ToString(val)
								if err != nil {
									return err
								}

								wrapperDotETagVal = c
								return nil
							}(); err != nil {
								return err
							}
							wrapper.ETag.SetTo(wrapperDotETagVal)
							return nil
						}); err != nil {
							return err
						}
					}
					return nil
				}(); err != nil {
					return res, errors.Wrap(err, "parse ETag header")
				}
			}
			return &wrapper, nil
		default:
			return res, validate.InvalidContentType(ct)
		}
	case 304:
		// Code 304.
		return &APIV1ClientsClientIdDeploymentsGetNotModified{}, nil
	case 406:
		// Code 406.
		return &APIV1ClientsClientIdDeploymentsGetNotAcceptable{}, nil
	}
	return res, validate.UnexpectedStatusCodeWithResponse(resp)
}

func decodeAPIV1OnboardingCertificateGetResponse(resp *http.Response) (res *APIV1OnboardingCertificateGetOK, _ error) {
	switch resp.StatusCode {
	case 200:
		// Code 200.
		ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
		if err != nil {
			return res, errors.Wrap(err, "parse media type")
		}
		switch {
		case ct == "application/json":
			buf, err := io.ReadAll(resp.Body)
			if err != nil {
				return res, err
			}
			d := jx.DecodeBytes(buf)

			var response APIV1OnboardingCertificateGetOK
			if err := func() error {
				if err := response.Decode(d); err != nil {
					return err
				}
				if err := d.Skip(); err != io.EOF {
					return errors.New("unexpected trailing data")
				}
				return nil
			}(); err != nil {
				err = &ogenerrors.DecodeBodyError{
					ContentType: ct,
					Body:        buf,
					Err:         err,
				}
				return res, err
			}
			return &response, nil
		default:
			return res, validate.InvalidContentType(ct)
		}
	}
	return res, validate.UnexpectedStatusCodeWithResponse(resp)
}

func decodeAPIV1OnboardingPostResponse(resp *http.Response) (res APIV1OnboardingPostRes, _ error) {
	switch resp.StatusCode {
	case 201:
		// Code 201.
		ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
		if err != nil {
			return res, errors.Wrap(err, "parse media type")
		}
		switch {
		case ct == "application/json":
			buf, err := io.ReadAll(resp.Body)
			if err != nil {
				return res, err
			}
			d := jx.DecodeBytes(buf)

			var response APIV1OnboardingPostCreated
			if err := func() error {
				if err := response.Decode(d); err != nil {
					return err
				}
				if err := d.Skip(); err != io.EOF {
					return errors.New("unexpected trailing data")
				}
				return nil
			}(); err != nil {
				err = &ogenerrors.DecodeBodyError{
					ContentType: ct,
					Body:        buf,
					Err:         err,
				}
				return res, err
			}
			return &response, nil
		default:
			return res, validate.InvalidContentType(ct)
		}
	case 400:
		// Code 400.
		ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
		if err != nil {
			return res, errors.Wrap(err, "parse media type")
		}
		switch {
		case ct == "application/json":
			buf, err := io.ReadAll(resp.Body)
			if err != nil {
				return res, err
			}
			d := jx.DecodeBytes(buf)

			var response APIV1OnboardingPostBadRequest
			if err := func() error {
				if err := response.Decode(d); err != nil {
					return err
				}
				if err := d.Skip(); err != io.EOF {
					return errors.New("unexpected trailing data")
				}
				return nil
			}(); err != nil {
				err = &ogenerrors.DecodeBodyError{
					ContentType: ct,
					Body:        buf,
					Err:         err,
				}
				return res, err
			}
			return &response, nil
		default:
			return res, validate.InvalidContentType(ct)
		}
	case 403:
		// Code 403.
		ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
		if err != nil {
			return res, errors.Wrap(err, "parse media type")
		}
		switch {
		case ct == "application/json":
			buf, err := io.ReadAll(resp.Body)
			if err != nil {
				return res, err
			}
			d := jx.DecodeBytes(buf)

			var response APIV1OnboardingPostForbidden
			if err := func() error {
				if err := response.Decode(d); err != nil {
					return err
				}
				if err := d.Skip(); err != io.EOF {
					return errors.New("unexpected trailing data")
				}
				return nil
			}(); err != nil {
				err = &ogenerrors.DecodeBodyError{
					ContentType: ct,
					Body:        buf,
					Err:         err,
				}
				return res, err
			}
			return &response, nil
		default:
			return res, validate.InvalidContentType(ct)
		}
	}
	return res, validate.UnexpectedStatusCodeWithResponse(resp)
}
