// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// APIV1ClientsClientIdBundlesDigestGet implements GET /api/v1/clients/{clientId}/bundles/{digest} operation.
//
// Retrieve bundle information for a specific device and digest.
//
// GET /api/v1/clients/{clientId}/bundles/{digest}
func (UnimplementedHandler) APIV1ClientsClientIdBundlesDigestGet(ctx context.Context, params APIV1ClientsClientIdBundlesDigestGetParams) (r APIV1ClientsClientIdBundlesDigestGetRes, _ error) {
	return r, ht.ErrNotImplemented
}

// APIV1ClientsClientIdCapabilitiesPost implements POST /api/v1/clients/{clientId}/capabilities operation.
//
// Report device capabilities.
//
// POST /api/v1/clients/{clientId}/capabilities
func (UnimplementedHandler) APIV1ClientsClientIdCapabilitiesPost(ctx context.Context, req *DeviceCapabilitiesManifest, params APIV1ClientsClientIdCapabilitiesPostParams) (r APIV1ClientsClientIdCapabilitiesPostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// APIV1ClientsClientIdCapabilitiesPut implements PUT /api/v1/clients/{clientId}/capabilities operation.
//
// Update device capabilities (Update).
//
// PUT /api/v1/clients/{clientId}/capabilities
func (UnimplementedHandler) APIV1ClientsClientIdCapabilitiesPut(ctx context.Context, req *DeviceCapabilitiesManifest, params APIV1ClientsClientIdCapabilitiesPutParams) (r APIV1ClientsClientIdCapabilitiesPutRes, _ error) {
	return r, ht.ErrNotImplemented
}

// APIV1ClientsClientIdDeploymentsDeploymentIdDigestGet implements GET /api/v1/clients/{clientId}/deployments/{deploymentId}/{digest} operation.
//
// This endpoint is used by the client to fetch the YAML for a single ApplicationDeployment after it
// has processed a new State Manifest and identified a small number of new or updated deployments.
// This allows for highly efficient, incremental updates without needing to download the full bundle.
// To make individual workload retrievals race-free and cache-friendly, this endpoint is
// content-addressable: the digest of the expected YAML is part of the URL. This guarantees
// immutability of the fetched resource and prevents a time-of-check / time-of-use race where a
// deployment changes between manifest retrieval and content fetch.
//
// GET /api/v1/clients/{clientId}/deployments/{deploymentId}/{digest}
func (UnimplementedHandler) APIV1ClientsClientIdDeploymentsDeploymentIdDigestGet(ctx context.Context, params APIV1ClientsClientIdDeploymentsDeploymentIdDigestGetParams) (r APIV1ClientsClientIdDeploymentsDeploymentIdDigestGetRes, _ error) {
	return r, ht.ErrNotImplemented
}

// APIV1ClientsClientIdDeploymentsDeploymentIdStatusPost implements POST /api/v1/clients/{clientId}/deployments/{deploymentId}/status operation.
//
// Report deployment status.
//
// POST /api/v1/clients/{clientId}/deployments/{deploymentId}/status
func (UnimplementedHandler) APIV1ClientsClientIdDeploymentsDeploymentIdStatusPost(ctx context.Context, req *DeploymentStatusManifest, params APIV1ClientsClientIdDeploymentsDeploymentIdStatusPostParams) (r APIV1ClientsClientIdDeploymentsDeploymentIdStatusPostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// APIV1ClientsClientIdDeploymentsGet implements GET /api/v1/clients/{clientId}/deployments operation.
//
// Retrieve the complete desired state for all workloads assigned to a device.
//
// GET /api/v1/clients/{clientId}/deployments
func (UnimplementedHandler) APIV1ClientsClientIdDeploymentsGet(ctx context.Context, params APIV1ClientsClientIdDeploymentsGetParams) (r APIV1ClientsClientIdDeploymentsGetRes, _ error) {
	return r, ht.ErrNotImplemented
}

// APIV1OnboardingCertificateGet implements GET /api/v1/onboarding/certificate operation.
//
// Download Root CA certificate.
//
// GET /api/v1/onboarding/certificate
func (UnimplementedHandler) APIV1OnboardingCertificateGet(ctx context.Context) (r *APIV1OnboardingCertificateGetOK, _ error) {
	return r, ht.ErrNotImplemented
}

// APIV1OnboardingPost implements POST /api/v1/onboarding operation.
//
// Complete onboarding with client certificate.
//
// POST /api/v1/onboarding
func (UnimplementedHandler) APIV1OnboardingPost(ctx context.Context, req *APIV1OnboardingPostReq) (r APIV1OnboardingPostRes, _ error) {
	return r, ht.ErrNotImplemented
}
