// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// APIV1ClientsClientIdBundlesDigestGet implements GET /api/v1/clients/{clientId}/bundles/{digest} operation.
	//
	// Retrieve bundle information for a specific device and digest.
	//
	// GET /api/v1/clients/{clientId}/bundles/{digest}
	APIV1ClientsClientIdBundlesDigestGet(ctx context.Context, params APIV1ClientsClientIdBundlesDigestGetParams) (APIV1ClientsClientIdBundlesDigestGetRes, error)
	// APIV1ClientsClientIdCapabilitiesPost implements POST /api/v1/clients/{clientId}/capabilities operation.
	//
	// Report device capabilities.
	//
	// POST /api/v1/clients/{clientId}/capabilities
	APIV1ClientsClientIdCapabilitiesPost(ctx context.Context, req *DeviceCapabilitiesManifest, params APIV1ClientsClientIdCapabilitiesPostParams) (APIV1ClientsClientIdCapabilitiesPostRes, error)
	// APIV1ClientsClientIdCapabilitiesPut implements PUT /api/v1/clients/{clientId}/capabilities operation.
	//
	// Update device capabilities (Update).
	//
	// PUT /api/v1/clients/{clientId}/capabilities
	APIV1ClientsClientIdCapabilitiesPut(ctx context.Context, req *DeviceCapabilitiesManifest, params APIV1ClientsClientIdCapabilitiesPutParams) (APIV1ClientsClientIdCapabilitiesPutRes, error)
	// APIV1ClientsClientIdDeploymentsDeploymentIdDigestGet implements GET /api/v1/clients/{clientId}/deployments/{deploymentId}/{digest} operation.
	//
	// This endpoint is used by the client to fetch the YAML for a single ApplicationDeployment after it
	// has processed a new State Manifest and identified a small number of new or updated deployments.
	// This allows for highly efficient, incremental updates without needing to download the full bundle.
	// To make individual workload retrievals race-free and cache-friendly, this endpoint is
	// content-addressable: the digest of the expected YAML is part of the URL. This guarantees
	// immutability of the fetched resource and prevents a time-of-check / time-of-use race where a
	// deployment changes between manifest retrieval and content fetch.
	//
	// GET /api/v1/clients/{clientId}/deployments/{deploymentId}/{digest}
	APIV1ClientsClientIdDeploymentsDeploymentIdDigestGet(ctx context.Context, params APIV1ClientsClientIdDeploymentsDeploymentIdDigestGetParams) (APIV1ClientsClientIdDeploymentsDeploymentIdDigestGetRes, error)
	// APIV1ClientsClientIdDeploymentsDeploymentIdStatusPost implements POST /api/v1/clients/{clientId}/deployments/{deploymentId}/status operation.
	//
	// Report deployment status.
	//
	// POST /api/v1/clients/{clientId}/deployments/{deploymentId}/status
	APIV1ClientsClientIdDeploymentsDeploymentIdStatusPost(ctx context.Context, req *DeploymentStatusManifest, params APIV1ClientsClientIdDeploymentsDeploymentIdStatusPostParams) (APIV1ClientsClientIdDeploymentsDeploymentIdStatusPostRes, error)
	// APIV1ClientsClientIdDeploymentsGet implements GET /api/v1/clients/{clientId}/deployments operation.
	//
	// Retrieve the complete desired state for all workloads assigned to a device.
	//
	// GET /api/v1/clients/{clientId}/deployments
	APIV1ClientsClientIdDeploymentsGet(ctx context.Context, params APIV1ClientsClientIdDeploymentsGetParams) (APIV1ClientsClientIdDeploymentsGetRes, error)
	// APIV1OnboardingCertificateGet implements GET /api/v1/onboarding/certificate operation.
	//
	// Download Root CA certificate.
	//
	// GET /api/v1/onboarding/certificate
	APIV1OnboardingCertificateGet(ctx context.Context) (*APIV1OnboardingCertificateGetOK, error)
	// APIV1OnboardingPost implements POST /api/v1/onboarding operation.
	//
	// Complete onboarding with client certificate.
	//
	// POST /api/v1/onboarding
	APIV1OnboardingPost(ctx context.Context, req *APIV1OnboardingPostReq) (APIV1OnboardingPostRes, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
