// Code generated by ogen, DO NOT EDIT.
package api

type APIV1ClientsClientIdBundlesDigestGetRes interface {
	aPIV1ClientsClientIdBundlesDigestGetRes()
}

type APIV1ClientsClientIdCapabilitiesPostRes interface {
	aPIV1ClientsClientIdCapabilitiesPostRes()
}

type APIV1ClientsClientIdCapabilitiesPutRes interface {
	aPIV1ClientsClientIdCapabilitiesPutRes()
}

type APIV1ClientsClientIdDeploymentsDeploymentIdDigestGetRes interface {
	aPIV1ClientsClientIdDeploymentsDeploymentIdDigestGetRes()
}

type APIV1ClientsClientIdDeploymentsDeploymentIdStatusPostRes interface {
	aPIV1ClientsClientIdDeploymentsDeploymentIdStatusPostRes()
}

type APIV1ClientsClientIdDeploymentsGetRes interface {
	aPIV1ClientsClientIdDeploymentsGetRes()
}

type APIV1OnboardingPostRes interface {
	aPIV1OnboardingPostRes()
}
