// Code generated by ogen, DO NOT EDIT.

package api

import (
	"net/http"
	"net/url"

	"github.com/go-faster/errors"
	"github.com/ogen-go/ogen/conv"
	"github.com/ogen-go/ogen/middleware"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/uri"
	"github.com/ogen-go/ogen/validate"
)

// APIV1ClientsClientIdBundlesDigestGetParams is parameters of GET /api/v1/clients/{clientId}/bundles/{digest} operation.
type APIV1ClientsClientIdBundlesDigestGetParams struct {
	// Unique identifier of the device-client.
	ClientId string
	// Content-addressable digest of the bundle archive. MUST conform to the 'digest' attribute in the
	// Digest Specification and MUST equal the digest computed over the exact sequence of bytes (per
	// Exact Bytes Rule) in the HTTP 200 OK response body. If the server cannot produce content whose
	// digest matches this value it MUST return 404 Not Found.
	Digest string
	// Quoted ETag (same as digest) previously returned for this bundle.
	IfNoneMatch OptString `json:",omitempty,omitzero"`
}

func unpackAPIV1ClientsClientIdBundlesDigestGetParams(packed middleware.Parameters) (params APIV1ClientsClientIdBundlesDigestGetParams) {
	{
		key := middleware.ParameterKey{
			Name: "clientId",
			In:   "path",
		}
		params.ClientId = packed[key].(string)
	}
	{
		key := middleware.ParameterKey{
			Name: "digest",
			In:   "path",
		}
		params.Digest = packed[key].(string)
	}
	{
		key := middleware.ParameterKey{
			Name: "If-None-Match",
			In:   "header",
		}
		if v, ok := packed[key]; ok {
			params.IfNoneMatch = v.(OptString)
		}
	}
	return params
}

func decodeAPIV1ClientsClientIdBundlesDigestGetParams(args [2]string, argsEscaped bool, r *http.Request) (params APIV1ClientsClientIdBundlesDigestGetParams, _ error) {
	h := uri.NewHeaderDecoder(r.Header)
	// Decode path: clientId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "clientId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.ClientId = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "clientId",
			In:   "path",
			Err:  err,
		}
	}
	// Decode path: digest.
	if err := func() error {
		param := args[1]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[1])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "digest",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.Digest = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "digest",
			In:   "path",
			Err:  err,
		}
	}
	// Decode header: If-None-Match.
	if err := func() error {
		cfg := uri.HeaderParameterDecodingConfig{
			Name:    "If-None-Match",
			Explode: false,
		}
		if err := h.HasParam(cfg); err == nil {
			if err := h.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotIfNoneMatchVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotIfNoneMatchVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.IfNoneMatch.SetTo(paramsDotIfNoneMatchVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "If-None-Match",
			In:   "header",
			Err:  err,
		}
	}
	return params, nil
}

// APIV1ClientsClientIdCapabilitiesPostParams is parameters of POST /api/v1/clients/{clientId}/capabilities operation.
type APIV1ClientsClientIdCapabilitiesPostParams struct {
	ClientId string
}

func unpackAPIV1ClientsClientIdCapabilitiesPostParams(packed middleware.Parameters) (params APIV1ClientsClientIdCapabilitiesPostParams) {
	{
		key := middleware.ParameterKey{
			Name: "clientId",
			In:   "path",
		}
		params.ClientId = packed[key].(string)
	}
	return params
}

func decodeAPIV1ClientsClientIdCapabilitiesPostParams(args [1]string, argsEscaped bool, r *http.Request) (params APIV1ClientsClientIdCapabilitiesPostParams, _ error) {
	// Decode path: clientId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "clientId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.ClientId = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "clientId",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// APIV1ClientsClientIdCapabilitiesPutParams is parameters of PUT /api/v1/clients/{clientId}/capabilities operation.
type APIV1ClientsClientIdCapabilitiesPutParams struct {
	ClientId string
}

func unpackAPIV1ClientsClientIdCapabilitiesPutParams(packed middleware.Parameters) (params APIV1ClientsClientIdCapabilitiesPutParams) {
	{
		key := middleware.ParameterKey{
			Name: "clientId",
			In:   "path",
		}
		params.ClientId = packed[key].(string)
	}
	return params
}

func decodeAPIV1ClientsClientIdCapabilitiesPutParams(args [1]string, argsEscaped bool, r *http.Request) (params APIV1ClientsClientIdCapabilitiesPutParams, _ error) {
	// Decode path: clientId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "clientId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.ClientId = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "clientId",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// APIV1ClientsClientIdDeploymentsDeploymentIdDigestGetParams is parameters of GET /api/v1/clients/{clientId}/deployments/{deploymentId}/{digest} operation.
type APIV1ClientsClientIdDeploymentsDeploymentIdDigestGetParams struct {
	// Unique identifier of the Edge Compute Device.
	ClientId string
	// UUID of the ApplicationDeployment (metadata.annotations.id).
	DeploymentId string
	// Content-addressable digest of the ApplicationDeployment YAML file. MUST conform to the Digest
	// Specification and MUST equal the digest computed over the exact sequence of bytes (per Exact Bytes
	// Rule) in the HTTP 200 OK response body. If the server cannot produce content whose digest matches
	// this value it MUST return 404 Not Found.
	Digest string
	// Optional ETag for caching. The ETag is returned to the client from the /deployments endpoint, it
	// is the digest of the state manifest.
	IfNoneMatch OptString `json:",omitempty,omitzero"`
	// Indicates supported compression formats (e.g., gzip, br).
	AcceptEncoding OptString `json:",omitempty,omitzero"`
}

func unpackAPIV1ClientsClientIdDeploymentsDeploymentIdDigestGetParams(packed middleware.Parameters) (params APIV1ClientsClientIdDeploymentsDeploymentIdDigestGetParams) {
	{
		key := middleware.ParameterKey{
			Name: "clientId",
			In:   "path",
		}
		params.ClientId = packed[key].(string)
	}
	{
		key := middleware.ParameterKey{
			Name: "deploymentId",
			In:   "path",
		}
		params.DeploymentId = packed[key].(string)
	}
	{
		key := middleware.ParameterKey{
			Name: "digest",
			In:   "path",
		}
		params.Digest = packed[key].(string)
	}
	{
		key := middleware.ParameterKey{
			Name: "If-None-Match",
			In:   "header",
		}
		if v, ok := packed[key]; ok {
			params.IfNoneMatch = v.(OptString)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "Accept-Encoding",
			In:   "header",
		}
		if v, ok := packed[key]; ok {
			params.AcceptEncoding = v.(OptString)
		}
	}
	return params
}

func decodeAPIV1ClientsClientIdDeploymentsDeploymentIdDigestGetParams(args [3]string, argsEscaped bool, r *http.Request) (params APIV1ClientsClientIdDeploymentsDeploymentIdDigestGetParams, _ error) {
	h := uri.NewHeaderDecoder(r.Header)
	// Decode path: clientId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "clientId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.ClientId = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "clientId",
			In:   "path",
			Err:  err,
		}
	}
	// Decode path: deploymentId.
	if err := func() error {
		param := args[1]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[1])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "deploymentId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.DeploymentId = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "deploymentId",
			In:   "path",
			Err:  err,
		}
	}
	// Decode path: digest.
	if err := func() error {
		param := args[2]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[2])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "digest",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.Digest = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "digest",
			In:   "path",
			Err:  err,
		}
	}
	// Decode header: If-None-Match.
	if err := func() error {
		cfg := uri.HeaderParameterDecodingConfig{
			Name:    "If-None-Match",
			Explode: false,
		}
		if err := h.HasParam(cfg); err == nil {
			if err := h.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotIfNoneMatchVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotIfNoneMatchVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.IfNoneMatch.SetTo(paramsDotIfNoneMatchVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "If-None-Match",
			In:   "header",
			Err:  err,
		}
	}
	// Decode header: Accept-Encoding.
	if err := func() error {
		cfg := uri.HeaderParameterDecodingConfig{
			Name:    "Accept-Encoding",
			Explode: false,
		}
		if err := h.HasParam(cfg); err == nil {
			if err := h.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotAcceptEncodingVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotAcceptEncodingVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.AcceptEncoding.SetTo(paramsDotAcceptEncodingVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "Accept-Encoding",
			In:   "header",
			Err:  err,
		}
	}
	return params, nil
}

// APIV1ClientsClientIdDeploymentsDeploymentIdStatusPostParams is parameters of POST /api/v1/clients/{clientId}/deployments/{deploymentId}/status operation.
type APIV1ClientsClientIdDeploymentsDeploymentIdStatusPostParams struct {
	ClientId     string
	DeploymentId string
}

func unpackAPIV1ClientsClientIdDeploymentsDeploymentIdStatusPostParams(packed middleware.Parameters) (params APIV1ClientsClientIdDeploymentsDeploymentIdStatusPostParams) {
	{
		key := middleware.ParameterKey{
			Name: "clientId",
			In:   "path",
		}
		params.ClientId = packed[key].(string)
	}
	{
		key := middleware.ParameterKey{
			Name: "deploymentId",
			In:   "path",
		}
		params.DeploymentId = packed[key].(string)
	}
	return params
}

func decodeAPIV1ClientsClientIdDeploymentsDeploymentIdStatusPostParams(args [2]string, argsEscaped bool, r *http.Request) (params APIV1ClientsClientIdDeploymentsDeploymentIdStatusPostParams, _ error) {
	// Decode path: clientId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "clientId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.ClientId = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "clientId",
			In:   "path",
			Err:  err,
		}
	}
	// Decode path: deploymentId.
	if err := func() error {
		param := args[1]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[1])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "deploymentId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.DeploymentId = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "deploymentId",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// APIV1ClientsClientIdDeploymentsGetParams is parameters of GET /api/v1/clients/{clientId}/deployments operation.
type APIV1ClientsClientIdDeploymentsGetParams struct {
	// The unique identifier of the Edge Compute Device making the request.
	ClientId string
	// ETag value of the last successfully synced manifest. The ETag is returned to the client from the
	// /deployments endpoint, it is the digest of the state manifest.
	IfNoneMatch OptString `json:",omitempty,omitzero"`
	// Indicates which manifest formats the client supports. Supported values: application/vnd.margo.
	// manifest.v1+json.
	Accept OptString `json:",omitempty,omitzero"`
}

func unpackAPIV1ClientsClientIdDeploymentsGetParams(packed middleware.Parameters) (params APIV1ClientsClientIdDeploymentsGetParams) {
	{
		key := middleware.ParameterKey{
			Name: "clientId",
			In:   "path",
		}
		params.ClientId = packed[key].(string)
	}
	{
		key := middleware.ParameterKey{
			Name: "If-None-Match",
			In:   "header",
		}
		if v, ok := packed[key]; ok {
			params.IfNoneMatch = v.(OptString)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "Accept",
			In:   "header",
		}
		if v, ok := packed[key]; ok {
			params.Accept = v.(OptString)
		}
	}
	return params
}

func decodeAPIV1ClientsClientIdDeploymentsGetParams(args [1]string, argsEscaped bool, r *http.Request) (params APIV1ClientsClientIdDeploymentsGetParams, _ error) {
	h := uri.NewHeaderDecoder(r.Header)
	// Decode path: clientId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "clientId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.ClientId = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "clientId",
			In:   "path",
			Err:  err,
		}
	}
	// Decode header: If-None-Match.
	if err := func() error {
		cfg := uri.HeaderParameterDecodingConfig{
			Name:    "If-None-Match",
			Explode: false,
		}
		if err := h.HasParam(cfg); err == nil {
			if err := h.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotIfNoneMatchVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotIfNoneMatchVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.IfNoneMatch.SetTo(paramsDotIfNoneMatchVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "If-None-Match",
			In:   "header",
			Err:  err,
		}
	}
	// Decode header: Accept.
	if err := func() error {
		cfg := uri.HeaderParameterDecodingConfig{
			Name:    "Accept",
			Explode: false,
		}
		if err := h.HasParam(cfg); err == nil {
			if err := h.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotAcceptVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotAcceptVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.Accept.SetTo(paramsDotAcceptVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "Accept",
			In:   "header",
			Err:  err,
		}
	}
	return params, nil
}
