// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
	"net/http"
	"strings"
)

// SecurityHandler is handler for security parameters.
type SecurityHandler interface {
	// HandlePayloadSignature handles PayloadSignature security.
	// Base64-encoded payload signature using SHA-256 and device certificate. Format: public_key;
	// digital_signature.
	HandlePayloadSignature(ctx context.Context, operationName OperationName, t PayloadSignature) (context.Context, error)
}

func findAuthorization(h http.Header, prefix string) (string, bool) {
	v, ok := h["Authorization"]
	if !ok {
		return "", false
	}
	for _, vv := range v {
		scheme, value, ok := strings.Cut(vv, " ")
		if !ok || !strings.EqualFold(scheme, prefix) {
			continue
		}
		return value, true
	}
	return "", false
}

// operationRolesPayloadSignature is a private map storing roles per operation.
var operationRolesPayloadSignature = map[string][]string{
	APIV1ClientsClientIdBundlesDigestGetOperation:                  []string{},
	APIV1ClientsClientIdCapabilitiesPostOperation:                  []string{},
	APIV1ClientsClientIdCapabilitiesPutOperation:                   []string{},
	APIV1ClientsClientIdDeploymentsDeploymentIdDigestGetOperation:  []string{},
	APIV1ClientsClientIdDeploymentsDeploymentIdStatusPostOperation: []string{},
	APIV1ClientsClientIdDeploymentsGetOperation:                    []string{},
	APIV1OnboardingPostOperation:                                   []string{},
}

// GetRolesForPayloadSignature returns the required roles for the given operation.
//
// This is useful for authorization scenarios where you need to know which roles
// are required for an operation.
//
// Example:
//
//	requiredRoles := GetRolesForPayloadSignature(AddPetOperation)
//
// Returns nil if the operation has no role requirements or if the operation is unknown.
func GetRolesForPayloadSignature(operation string) []string {
	roles, ok := operationRolesPayloadSignature[operation]
	if !ok {
		return nil
	}
	// Return a copy to prevent external modification
	result := make([]string, len(roles))
	copy(result, roles)
	return result
}

func (s *Server) securityPayloadSignature(ctx context.Context, operationName OperationName, req *http.Request) (context.Context, bool, error) {
	var t PayloadSignature
	const parameterName = "X-Payload-Signature"
	value := req.Header.Get(parameterName)
	if value == "" {
		return ctx, false, nil
	}
	t.APIKey = value
	t.Roles = operationRolesPayloadSignature[operationName]
	return ctx, true, nil
}

// SecuritySource is provider of security values (tokens, passwords, etc.).
type SecuritySource interface {
	// PayloadSignature provides PayloadSignature security value.
	// Base64-encoded payload signature using SHA-256 and device certificate. Format: public_key;
	// digital_signature.
	PayloadSignature(ctx context.Context, operationName OperationName) (PayloadSignature, error)
}

func (s *Client) securityPayloadSignature(ctx context.Context, operationName OperationName, req *http.Request) error {
	return nil
}
