// Code generated by ogen, DO NOT EDIT.

package api

import (
	"io"
	"net/http"

	"github.com/go-faster/errors"
	"github.com/go-faster/jx"
	"github.com/ogen-go/ogen/conv"
	"github.com/ogen-go/ogen/uri"
	"go.opentelemetry.io/otel/codes"
	"go.opentelemetry.io/otel/trace"
)

func encodeAPIV1ClientsClientIdBundlesDigestGetResponse(response APIV1ClientsClientIdBundlesDigestGetRes, w http.ResponseWriter, span trace.Span) error {
	switch response := response.(type) {
	case *APIV1ClientsClientIdBundlesDigestGetOKHeaders:
		w.Header().Set("Content-Type", "application/vnd.margo.bundle.v1+tar+gzip")
		w.Header().Set("Access-Control-Expose-Headers", "Etag")
		// Encoding response headers.
		{
			h := uri.NewHeaderEncoder(w.Header())
			// Encode "Cache-Control" header.
			{
				cfg := uri.HeaderParameterEncodingConfig{
					Name:    "Cache-Control",
					Explode: false,
				}
				if err := h.EncodeParam(cfg, func(e uri.Encoder) error {
					if val, ok := response.CacheControl.Get(); ok {
						return e.EncodeValue(conv.StringToString(val))
					}
					return nil
				}); err != nil {
					return errors.Wrap(err, "encode Cache-Control header")
				}
			}
			// Encode "ETag" header.
			{
				cfg := uri.HeaderParameterEncodingConfig{
					Name:    "ETag",
					Explode: false,
				}
				if err := h.EncodeParam(cfg, func(e uri.Encoder) error {
					if val, ok := response.ETag.Get(); ok {
						return e.EncodeValue(conv.StringToString(val))
					}
					return nil
				}); err != nil {
					return errors.Wrap(err, "encode ETag header")
				}
			}
		}
		w.WriteHeader(200)
		span.SetStatus(codes.Ok, http.StatusText(200))

		writer := w
		if closer, ok := response.Response.Data.(io.Closer); ok {
			defer closer.Close()
		}
		if _, err := io.Copy(writer, response.Response); err != nil {
			return errors.Wrap(err, "write")
		}

		return nil

	case *APIV1ClientsClientIdBundlesDigestGetNotModified:
		w.WriteHeader(304)
		span.SetStatus(codes.Ok, http.StatusText(304))

		return nil

	case *APIV1ClientsClientIdBundlesDigestGetBadRequest:
		w.WriteHeader(400)
		span.SetStatus(codes.Error, http.StatusText(400))

		return nil

	case *APIV1ClientsClientIdBundlesDigestGetNotFound:
		w.WriteHeader(404)
		span.SetStatus(codes.Error, http.StatusText(404))

		return nil

	default:
		return errors.Errorf("unexpected response type: %T", response)
	}
}

func encodeAPIV1ClientsClientIdCapabilitiesPostResponse(response APIV1ClientsClientIdCapabilitiesPostRes, w http.ResponseWriter, span trace.Span) error {
	switch response := response.(type) {
	case *APIV1ClientsClientIdCapabilitiesPostCreated:
		w.WriteHeader(201)
		span.SetStatus(codes.Ok, http.StatusText(201))

		return nil

	case *APIV1ClientsClientIdCapabilitiesPostBadRequest:
		w.WriteHeader(400)
		span.SetStatus(codes.Error, http.StatusText(400))

		return nil

	case *APIV1ClientsClientIdCapabilitiesPostUnauthorized:
		w.WriteHeader(401)
		span.SetStatus(codes.Error, http.StatusText(401))

		return nil

	case *APIV1ClientsClientIdCapabilitiesPostForbidden:
		w.WriteHeader(403)
		span.SetStatus(codes.Error, http.StatusText(403))

		return nil

	case *APIV1ClientsClientIdCapabilitiesPostUnprocessableEntity:
		w.WriteHeader(422)
		span.SetStatus(codes.Error, http.StatusText(422))

		return nil

	default:
		return errors.Errorf("unexpected response type: %T", response)
	}
}

func encodeAPIV1ClientsClientIdCapabilitiesPutResponse(response APIV1ClientsClientIdCapabilitiesPutRes, w http.ResponseWriter, span trace.Span) error {
	switch response := response.(type) {
	case *APIV1ClientsClientIdCapabilitiesPutCreated:
		w.WriteHeader(201)
		span.SetStatus(codes.Ok, http.StatusText(201))

		return nil

	case *APIV1ClientsClientIdCapabilitiesPutBadRequest:
		w.WriteHeader(400)
		span.SetStatus(codes.Error, http.StatusText(400))

		return nil

	case *APIV1ClientsClientIdCapabilitiesPutUnauthorized:
		w.WriteHeader(401)
		span.SetStatus(codes.Error, http.StatusText(401))

		return nil

	case *APIV1ClientsClientIdCapabilitiesPutForbidden:
		w.WriteHeader(403)
		span.SetStatus(codes.Error, http.StatusText(403))

		return nil

	case *APIV1ClientsClientIdCapabilitiesPutUnprocessableEntity:
		w.WriteHeader(422)
		span.SetStatus(codes.Error, http.StatusText(422))

		return nil

	default:
		return errors.Errorf("unexpected response type: %T", response)
	}
}

func encodeAPIV1ClientsClientIdDeploymentsDeploymentIdDigestGetResponse(response APIV1ClientsClientIdDeploymentsDeploymentIdDigestGetRes, w http.ResponseWriter, span trace.Span) error {
	switch response := response.(type) {
	case *APIV1ClientsClientIdDeploymentsDeploymentIdDigestGetOKHeaders:
		w.Header().Set("Content-Type", "application/yaml")
		w.Header().Set("Access-Control-Expose-Headers", "Etag,Vary")
		// Encoding response headers.
		{
			h := uri.NewHeaderEncoder(w.Header())
			// Encode "Cache-Control" header.
			{
				cfg := uri.HeaderParameterEncodingConfig{
					Name:    "Cache-Control",
					Explode: false,
				}
				if err := h.EncodeParam(cfg, func(e uri.Encoder) error {
					if val, ok := response.CacheControl.Get(); ok {
						return e.EncodeValue(conv.StringToString(val))
					}
					return nil
				}); err != nil {
					return errors.Wrap(err, "encode Cache-Control header")
				}
			}
			// Encode "ETag" header.
			{
				cfg := uri.HeaderParameterEncodingConfig{
					Name:    "ETag",
					Explode: false,
				}
				if err := h.EncodeParam(cfg, func(e uri.Encoder) error {
					if val, ok := response.ETag.Get(); ok {
						return e.EncodeValue(conv.StringToString(val))
					}
					return nil
				}); err != nil {
					return errors.Wrap(err, "encode ETag header")
				}
			}
			// Encode "Vary" header.
			{
				cfg := uri.HeaderParameterEncodingConfig{
					Name:    "Vary",
					Explode: false,
				}
				if err := h.EncodeParam(cfg, func(e uri.Encoder) error {
					if val, ok := response.Vary.Get(); ok {
						return e.EncodeValue(conv.StringToString(val))
					}
					return nil
				}); err != nil {
					return errors.Wrap(err, "encode Vary header")
				}
			}
		}
		w.WriteHeader(200)
		span.SetStatus(codes.Ok, http.StatusText(200))

		writer := w
		if closer, ok := response.Response.Data.(io.Closer); ok {
			defer closer.Close()
		}
		if _, err := io.Copy(writer, response.Response); err != nil {
			return errors.Wrap(err, "write")
		}

		return nil

	case *APIV1ClientsClientIdDeploymentsDeploymentIdDigestGetNotFound:
		w.WriteHeader(404)
		span.SetStatus(codes.Error, http.StatusText(404))

		return nil

	default:
		return errors.Errorf("unexpected response type: %T", response)
	}
}

func encodeAPIV1ClientsClientIdDeploymentsDeploymentIdStatusPostResponse(response APIV1ClientsClientIdDeploymentsDeploymentIdStatusPostRes, w http.ResponseWriter, span trace.Span) error {
	switch response := response.(type) {
	case *APIV1ClientsClientIdDeploymentsDeploymentIdStatusPostOK:
		w.WriteHeader(200)
		span.SetStatus(codes.Ok, http.StatusText(200))

		return nil

	case *APIV1ClientsClientIdDeploymentsDeploymentIdStatusPostBadRequest:
		w.WriteHeader(400)
		span.SetStatus(codes.Error, http.StatusText(400))

		return nil

	case *APIV1ClientsClientIdDeploymentsDeploymentIdStatusPostUnauthorized:
		w.WriteHeader(401)
		span.SetStatus(codes.Error, http.StatusText(401))

		return nil

	case *APIV1ClientsClientIdDeploymentsDeploymentIdStatusPostForbidden:
		w.WriteHeader(403)
		span.SetStatus(codes.Error, http.StatusText(403))

		return nil

	case *APIV1ClientsClientIdDeploymentsDeploymentIdStatusPostUnprocessableEntity:
		w.WriteHeader(422)
		span.SetStatus(codes.Error, http.StatusText(422))

		return nil

	default:
		return errors.Errorf("unexpected response type: %T", response)
	}
}

func encodeAPIV1ClientsClientIdDeploymentsGetResponse(response APIV1ClientsClientIdDeploymentsGetRes, w http.ResponseWriter, span trace.Span) error {
	switch response := response.(type) {
	case *UnsignedAppStateManifestHeaders:
		w.Header().Set("Content-Type", "application/vnd.margo.manifest.v1+json")
		w.Header().Set("Access-Control-Expose-Headers", "Etag")
		// Encoding response headers.
		{
			h := uri.NewHeaderEncoder(w.Header())
			// Encode "ETag" header.
			{
				cfg := uri.HeaderParameterEncodingConfig{
					Name:    "ETag",
					Explode: false,
				}
				if err := h.EncodeParam(cfg, func(e uri.Encoder) error {
					if val, ok := response.ETag.Get(); ok {
						return e.EncodeValue(conv.StringToString(val))
					}
					return nil
				}); err != nil {
					return errors.Wrap(err, "encode ETag header")
				}
			}
		}
		w.WriteHeader(200)
		span.SetStatus(codes.Ok, http.StatusText(200))

		e := new(jx.Encoder)
		response.Response.Encode(e)
		if _, err := e.WriteTo(w); err != nil {
			return errors.Wrap(err, "write")
		}

		return nil

	case *APIV1ClientsClientIdDeploymentsGetNotModified:
		w.WriteHeader(304)
		span.SetStatus(codes.Ok, http.StatusText(304))

		return nil

	case *APIV1ClientsClientIdDeploymentsGetNotAcceptable:
		w.WriteHeader(406)
		span.SetStatus(codes.Error, http.StatusText(406))

		return nil

	default:
		return errors.Errorf("unexpected response type: %T", response)
	}
}

func encodeAPIV1OnboardingCertificateGetResponse(response *APIV1OnboardingCertificateGetOK, w http.ResponseWriter, span trace.Span) error {
	w.Header().Set("Content-Type", "application/json; charset=utf-8")
	w.WriteHeader(200)
	span.SetStatus(codes.Ok, http.StatusText(200))

	e := new(jx.Encoder)
	response.Encode(e)
	if _, err := e.WriteTo(w); err != nil {
		return errors.Wrap(err, "write")
	}

	return nil
}

func encodeAPIV1OnboardingPostResponse(response APIV1OnboardingPostRes, w http.ResponseWriter, span trace.Span) error {
	switch response := response.(type) {
	case *APIV1OnboardingPostCreated:
		w.Header().Set("Content-Type", "application/json; charset=utf-8")
		w.WriteHeader(201)
		span.SetStatus(codes.Ok, http.StatusText(201))

		e := new(jx.Encoder)
		response.Encode(e)
		if _, err := e.WriteTo(w); err != nil {
			return errors.Wrap(err, "write")
		}

		return nil

	case *APIV1OnboardingPostBadRequest:
		w.Header().Set("Content-Type", "application/json; charset=utf-8")
		w.WriteHeader(400)
		span.SetStatus(codes.Error, http.StatusText(400))

		e := new(jx.Encoder)
		response.Encode(e)
		if _, err := e.WriteTo(w); err != nil {
			return errors.Wrap(err, "write")
		}

		return nil

	case *APIV1OnboardingPostForbidden:
		w.Header().Set("Content-Type", "application/json; charset=utf-8")
		w.WriteHeader(403)
		span.SetStatus(codes.Error, http.StatusText(403))

		e := new(jx.Encoder)
		response.Encode(e)
		if _, err := e.WriteTo(w); err != nil {
			return errors.Wrap(err, "write")
		}

		return nil

	default:
		return errors.Errorf("unexpected response type: %T", response)
	}
}
