// Package generatedCode provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package generatedCode

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/oapi-codegen/runtime"
)

// RequestEditorFn is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {

	// GetDiscoveryDocument Retrieve MIAF discovery document
	//
	// Optional entry point for a Trust Domain.
	//
	// The discovery document identifies the Trust Domain and provides
	// the Trust Bundle URI from which the authoritative SPIFFE Bundle
	// Map can be retrieved.
	//
	// Corresponds with GET /.well-known/margo (the `GetDiscoveryDocument` operationId).
	GetDiscoveryDocument(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetTrustBundle Retrieve SPIFFE Bundle Map
	//
	// Returns a SPIFFE Bundle Map resource.
	//
	// The entry keyed by the local trustDomain contains the
	// authoritative Trust Bundle for that domain.
	//
	// The actual URL is provided by the discovery document's
	// trustBundleUri field.
	//
	// Corresponds with GET /{bundlePath} (the `GetTrustBundle` operationId).
	GetTrustBundle(ctx context.Context, bundlePath string, reqEditors ...RequestEditorFn) (*http.Response, error)
}

// GetDiscoveryDocument Retrieve MIAF discovery document
//
// Optional entry point for a Trust Domain.
//
// The discovery document identifies the Trust Domain and provides
// the Trust Bundle URI from which the authoritative SPIFFE Bundle
// Map can be retrieved.
//
// Corresponds with GET /.well-known/margo (the `GetDiscoveryDocument` operationId).
func (c *Client) GetDiscoveryDocument(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetDiscoveryDocumentRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetTrustBundle Retrieve SPIFFE Bundle Map
//
// Returns a SPIFFE Bundle Map resource.
//
// The entry keyed by the local trustDomain contains the
// authoritative Trust Bundle for that domain.
//
// The actual URL is provided by the discovery document's
// trustBundleUri field.
//
// Corresponds with GET /{bundlePath} (the `GetTrustBundle` operationId).
func (c *Client) GetTrustBundle(ctx context.Context, bundlePath string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetTrustBundleRequest(c.Server, bundlePath)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetDiscoveryDocumentRequest constructs an http.Request for the GetDiscoveryDocument method
func NewGetDiscoveryDocumentRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/.well-known/margo")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetTrustBundleRequest constructs an http.Request for the GetTrustBundle method
func NewGetTrustBundleRequest(server string, bundlePath string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "bundlePath", bundlePath, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {

	// GetDiscoveryDocumentWithResponse Retrieve MIAF discovery document
	//
	// Optional entry point for a Trust Domain.
	//
	// The discovery document identifies the Trust Domain and provides
	// the Trust Bundle URI from which the authoritative SPIFFE Bundle
	// Map can be retrieved.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /.well-known/margo (the `GetDiscoveryDocument` operationId).
	GetDiscoveryDocumentWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetDiscoveryDocumentResponse, error)

	// GetTrustBundleWithResponse Retrieve SPIFFE Bundle Map
	//
	// Returns a SPIFFE Bundle Map resource.
	//
	// The entry keyed by the local trustDomain contains the
	// authoritative Trust Bundle for that domain.
	//
	// The actual URL is provided by the discovery document's
	// trustBundleUri field.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /{bundlePath} (the `GetTrustBundle` operationId).
	GetTrustBundleWithResponse(ctx context.Context, bundlePath string, reqEditors ...RequestEditorFn) (*GetTrustBundleResponse, error)
}

// GetDiscoveryDocumentResponse200Headers the declared response headers of an HTTP 200 response for GetDiscoveryDocument
type GetDiscoveryDocumentResponse200Headers struct {
	ETag         *string
	LastModified *time.Time
}

type GetDiscoveryDocumentResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *DiscoveryDocument
	// Headers200 the parsed response headers for an HTTP 200 response
	Headers200 *GetDiscoveryDocumentResponse200Headers
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r GetDiscoveryDocumentResponse) GetJSON200() *DiscoveryDocument {
	return r.JSON200
}

// GetBody returns the raw response body bytes
func (r GetDiscoveryDocumentResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetDiscoveryDocumentResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetDiscoveryDocumentResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetDiscoveryDocumentResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// GetTrustBundleResponse200Headers the declared response headers of an HTTP 200 response for GetTrustBundle
type GetTrustBundleResponse200Headers struct {
	ETag         *string
	LastModified *time.Time
}

type GetTrustBundleResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *BundleMap
	// Headers200 the parsed response headers for an HTTP 200 response
	Headers200 *GetTrustBundleResponse200Headers
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r GetTrustBundleResponse) GetJSON200() *BundleMap {
	return r.JSON200
}

// GetBody returns the raw response body bytes
func (r GetTrustBundleResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetTrustBundleResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetTrustBundleResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetTrustBundleResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// GetDiscoveryDocumentWithResponse Retrieve MIAF discovery document
//
// Optional entry point for a Trust Domain.
//
// The discovery document identifies the Trust Domain and provides
// the Trust Bundle URI from which the authoritative SPIFFE Bundle
// Map can be retrieved.
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /.well-known/margo (the `GetDiscoveryDocument` operationId).
func (c *ClientWithResponses) GetDiscoveryDocumentWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetDiscoveryDocumentResponse, error) {
	rsp, err := c.GetDiscoveryDocument(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetDiscoveryDocumentResponse(rsp)
}

// GetTrustBundleWithResponse Retrieve SPIFFE Bundle Map
//
// Returns a SPIFFE Bundle Map resource.
//
// The entry keyed by the local trustDomain contains the
// authoritative Trust Bundle for that domain.
//
// The actual URL is provided by the discovery document's
// trustBundleUri field.
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /{bundlePath} (the `GetTrustBundle` operationId).
func (c *ClientWithResponses) GetTrustBundleWithResponse(ctx context.Context, bundlePath string, reqEditors ...RequestEditorFn) (*GetTrustBundleResponse, error) {
	rsp, err := c.GetTrustBundle(ctx, bundlePath, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetTrustBundleResponse(rsp)
}

// ParseGetDiscoveryDocumentResponse parses an HTTP response from a GetDiscoveryDocumentWithResponse call
func ParseGetDiscoveryDocumentResponse(rsp *http.Response) (*GetDiscoveryDocumentResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetDiscoveryDocumentResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest DiscoveryDocument
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case rsp.StatusCode == 304:
		break // No content-type

	case rsp.StatusCode == 404:
		break // No content-type

	}

	switch {
	case rsp.StatusCode == 200:
		var headers GetDiscoveryDocumentResponse200Headers
		if values := rsp.Header.Values("ETag"); len(values) > 0 {
			var value string
			if err := runtime.BindStyledParameterWithOptions("simple", "ETag", values[0], &value, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""}); err != nil {
				return nil, err
			}
			headers.ETag = &value
		}
		if values := rsp.Header.Values("Last-Modified"); len(values) > 0 {
			var value time.Time
			if err := runtime.BindStyledParameterWithOptions("simple", "Last-Modified", values[0], &value, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: "date-time"}); err != nil {
				return nil, err
			}
			headers.LastModified = &value
		}
		response.Headers200 = &headers
	}

	return response, nil
}

// ParseGetTrustBundleResponse parses an HTTP response from a GetTrustBundleWithResponse call
func ParseGetTrustBundleResponse(rsp *http.Response) (*GetTrustBundleResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetTrustBundleResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest BundleMap
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case rsp.StatusCode == 304:
		break // No content-type

	case rsp.StatusCode == 404:
		break // No content-type

	}

	switch {
	case rsp.StatusCode == 200:
		var headers GetTrustBundleResponse200Headers
		if values := rsp.Header.Values("ETag"); len(values) > 0 {
			var value string
			if err := runtime.BindStyledParameterWithOptions("simple", "ETag", values[0], &value, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""}); err != nil {
				return nil, err
			}
			headers.ETag = &value
		}
		if values := rsp.Header.Values("Last-Modified"); len(values) > 0 {
			var value time.Time
			if err := runtime.BindStyledParameterWithOptions("simple", "Last-Modified", values[0], &value, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: "date-time"}); err != nil {
				return nil, err
			}
			headers.LastModified = &value
		}
		response.Headers200 = &headers
	}

	return response, nil
}
