// Package generatedCode provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package generatedCode

import (
	"encoding/json"
	"fmt"
)

// Defines values for ProblemDetailBackoffStrategy.
const (
	Exponential ProblemDetailBackoffStrategy = "exponential"
	Fixed       ProblemDetailBackoffStrategy = "fixed"
	None        ProblemDetailBackoffStrategy = "none"
)

// Valid indicates whether the value is a known member of the ProblemDetailBackoffStrategy enum.
func (e ProblemDetailBackoffStrategy) Valid() bool {
	switch e {
	case Exponential:
		return true
	case Fixed:
		return true
	case None:
		return true
	default:
		return false
	}
}

// DiscoveryDocument Describes exactly one Trust Domain. Clients MUST ignore unknown fields.
type DiscoveryDocument struct {
	// TrustBundleUri Absolute HTTPS URL to the SPIFFE bundle for this Trust Domain. A client MUST reject a value whose scheme is not https. The bundle holds the authoritative trust anchors for the Trust Domain.
	//
	//
	// Examples: https://mis.factory.example/.well-known/spiffe/bundle.json
	TrustBundleUri string `json:"trustBundleUri"`

	// TrustDomain Identifier of the Trust Domain (for example, factory.example). Every SPIFFE ID issued by the MIS MUST belong to this Trust Domain.
	//
	//
	// Examples: factory.example
	TrustDomain          string                 `json:"trustDomain"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// ProblemDetail RFC 9457 Problem Details for HTTP APIs. Returned with Content-Type: application/problem+json. See https://www.rfc-editor.org/rfc/rfc9457. Extension members (RFC 9457 §3.2) are permitted via additionalProperties. Vendors MAY add custom fields alongside standard margo fields. Vendor-specific problem types MUST use their own URI namespace. The https://docs.margo.org/specification/problem-types namespace is reserved for Margo.
type ProblemDetail struct {
	// BackoffStrategy Recommended backoff strategy for retrying. none: do not retry. fixed: retry after retryAfterSeconds. exponential: use exponential backoff starting at retryAfterSeconds.
	BackoffStrategy *ProblemDetailBackoffStrategy `json:"backoffStrategy,omitempty"`

	// Detail Human-readable explanation specific to this occurrence of the problem.
	Detail *string `json:"detail,omitempty"`

	// Errors Optional list of field-level validation errors. SHOULD be present on 422 Unprocessable Entity responses.
	Errors *[]struct {
		// Field Field path that caused the validation error.
		Field *string `json:"field,omitempty"`

		// Message Human-readable validation error message.
		Message *string `json:"message,omitempty"`
	} `json:"errors,omitempty"`

	// Instance URI reference identifying the specific occurrence of the problem.
	Instance *string `json:"instance,omitempty"`

	// RetryAfterSeconds Advisory retry delay in seconds. The authoritative value is the Retry-After response header when present. This field is advisory only.
	RetryAfterSeconds *int `json:"retryAfterSeconds,omitempty"`

	// Retryable Whether the client MAY retry the request. If true, client SHOULD respect the Retry-After response header when present.
	Retryable *bool `json:"retryable,omitempty"`

	// Status HTTP status code.
	Status int `json:"status"`

	// Title Short human-readable summary of the problem type.
	Title string `json:"title"`

	// Type URI reference identifying the problem type. Implementations MUST use the registered Margo type URI for any error condition defined in the Margo specification. For error conditions not defined in this specification, implementations MAY define their own type URIs under their own namespace. Clients MUST use this field for programmatic error handling, NOT the status code or title. Clients encountering an unknown type URI SHOULD fall back to title, detail, and status for display and handling.
	Type                 string                 `json:"type"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// ProblemDetailBackoffStrategy Recommended backoff strategy for retrying. none: do not retry. fixed: retry after retryAfterSeconds. exponential: use exponential backoff starting at retryAfterSeconds.
type ProblemDetailBackoffStrategy string

// SpiffeBundle SPIFFE bundle for one Trust Domain. The concrete schema is defined by the SPIFFE Trust Domain and Bundle specification (a JWK Set). A client MUST reject the bundle, and MUST NOT validate SVIDs against it, if it carries no X.509 trust anchors (fail closed). The JWK Set MAY also carry jwt-svid signing keys; MIAF uses only x509-svid entries and MUST ignore any other key material on retrieval.
//
// Examples: {"keys":[{"crv":"P-256","kty":"EC","use":"x509-svid","x":"\u003cbase64url-encoded EC public key x coordinate\u003e","x5c":["\u003cbase64 DER of the Trust Domain's X.509 authority certificate\u003e"],"y":"\u003cbase64url-encoded EC public key y coordinate\u003e"}],"spiffe_refresh_hint":86400,"spiffe_sequence":12}
type SpiffeBundle map[string]interface{}

// GetWellKnownMargoParams defines parameters for GetWellKnownMargo.
type GetWellKnownMargoParams struct {
	// IfNoneMatch Previously returned ETag; used to revalidate a cached copy.
	IfNoneMatch *string `json:"If-None-Match,omitempty"`
}

// GetWellKnownSpiffeBundleJsonParams defines parameters for GetWellKnownSpiffeBundleJson.
type GetWellKnownSpiffeBundleJsonParams struct {
	// IfNoneMatch Previously returned ETag; used to revalidate a cached copy.
	IfNoneMatch *string `json:"If-None-Match,omitempty"`
}

// Getter for additional properties for DiscoveryDocument. Returns the specified
// element and whether it was found
func (a DiscoveryDocument) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for DiscoveryDocument
func (a *DiscoveryDocument) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for DiscoveryDocument to handle AdditionalProperties
func (a *DiscoveryDocument) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["trustBundleUri"]; found {
		err = json.Unmarshal(raw, &a.TrustBundleUri)
		if err != nil {
			return fmt.Errorf("error reading 'trustBundleUri': %w", err)
		}
		delete(object, "trustBundleUri")
	}

	if raw, found := object["trustDomain"]; found {
		err = json.Unmarshal(raw, &a.TrustDomain)
		if err != nil {
			return fmt.Errorf("error reading 'trustDomain': %w", err)
		}
		delete(object, "trustDomain")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for DiscoveryDocument to handle AdditionalProperties
func (a DiscoveryDocument) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["trustBundleUri"], err = json.Marshal(a.TrustBundleUri)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'trustBundleUri': %w", err)
	}

	object["trustDomain"], err = json.Marshal(a.TrustDomain)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'trustDomain': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for ProblemDetail. Returns the specified
// element and whether it was found
func (a ProblemDetail) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for ProblemDetail
func (a *ProblemDetail) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for ProblemDetail to handle AdditionalProperties
func (a *ProblemDetail) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["backoffStrategy"]; found {
		err = json.Unmarshal(raw, &a.BackoffStrategy)
		if err != nil {
			return fmt.Errorf("error reading 'backoffStrategy': %w", err)
		}
		delete(object, "backoffStrategy")
	}

	if raw, found := object["detail"]; found {
		err = json.Unmarshal(raw, &a.Detail)
		if err != nil {
			return fmt.Errorf("error reading 'detail': %w", err)
		}
		delete(object, "detail")
	}

	if raw, found := object["errors"]; found {
		err = json.Unmarshal(raw, &a.Errors)
		if err != nil {
			return fmt.Errorf("error reading 'errors': %w", err)
		}
		delete(object, "errors")
	}

	if raw, found := object["instance"]; found {
		err = json.Unmarshal(raw, &a.Instance)
		if err != nil {
			return fmt.Errorf("error reading 'instance': %w", err)
		}
		delete(object, "instance")
	}

	if raw, found := object["retryAfterSeconds"]; found {
		err = json.Unmarshal(raw, &a.RetryAfterSeconds)
		if err != nil {
			return fmt.Errorf("error reading 'retryAfterSeconds': %w", err)
		}
		delete(object, "retryAfterSeconds")
	}

	if raw, found := object["retryable"]; found {
		err = json.Unmarshal(raw, &a.Retryable)
		if err != nil {
			return fmt.Errorf("error reading 'retryable': %w", err)
		}
		delete(object, "retryable")
	}

	if raw, found := object["status"]; found {
		err = json.Unmarshal(raw, &a.Status)
		if err != nil {
			return fmt.Errorf("error reading 'status': %w", err)
		}
		delete(object, "status")
	}

	if raw, found := object["title"]; found {
		err = json.Unmarshal(raw, &a.Title)
		if err != nil {
			return fmt.Errorf("error reading 'title': %w", err)
		}
		delete(object, "title")
	}

	if raw, found := object["type"]; found {
		err = json.Unmarshal(raw, &a.Type)
		if err != nil {
			return fmt.Errorf("error reading 'type': %w", err)
		}
		delete(object, "type")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for ProblemDetail to handle AdditionalProperties
func (a ProblemDetail) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.BackoffStrategy != nil {
		object["backoffStrategy"], err = json.Marshal(a.BackoffStrategy)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'backoffStrategy': %w", err)
		}
	}

	if a.Detail != nil {
		object["detail"], err = json.Marshal(a.Detail)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'detail': %w", err)
		}
	}

	if a.Errors != nil {
		object["errors"], err = json.Marshal(a.Errors)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'errors': %w", err)
		}
	}

	if a.Instance != nil {
		object["instance"], err = json.Marshal(a.Instance)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'instance': %w", err)
		}
	}

	if a.RetryAfterSeconds != nil {
		object["retryAfterSeconds"], err = json.Marshal(a.RetryAfterSeconds)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'retryAfterSeconds': %w", err)
		}
	}

	if a.Retryable != nil {
		object["retryable"], err = json.Marshal(a.Retryable)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'retryable': %w", err)
		}
	}

	object["status"], err = json.Marshal(a.Status)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'status': %w", err)
	}

	object["title"], err = json.Marshal(a.Title)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'title': %w", err)
	}

	object["type"], err = json.Marshal(a.Type)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'type': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}
