// Package generatedCode provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package generatedCode

import (
	"encoding/json"
	"fmt"
)

// BundleMap SPIFFE Bundle Map.
//
// MIAF adopts the SPIFFE Bundle Map specification by reference.
// The structure is intentionally modeled as an open object because
// this specification does not redefine the SPIFFE schema.
type BundleMap map[string]interface{}

// DiscoveryDocument The discovery document is intentionally extensible.
// Clients MUST ignore unknown fields.
type DiscoveryDocument struct {
	// TrustBundleUri Absolute HTTPS URL pointing to the SPIFFE Bundle Map resource.
	//
	// The referenced Bundle Map MUST contain an entry for
	// trustDomain that represents the authoritative Trust Bundle
	// for that domain.
	TrustBundleUri string `json:"trustBundleUri"`

	// TrustDomain Identifier of the Trust Domain.
	//
	// All SPIFFE IDs issued by the MIS belong to this Trust Domain.
	//
	//
	// Examples: factory.example, northstar-ida.com
	TrustDomain          string                 `json:"trustDomain"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// Getter for additional properties for DiscoveryDocument. Returns the specified
// element and whether it was found
func (a DiscoveryDocument) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for DiscoveryDocument
func (a *DiscoveryDocument) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for DiscoveryDocument to handle AdditionalProperties
func (a *DiscoveryDocument) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["trustBundleUri"]; found {
		err = json.Unmarshal(raw, &a.TrustBundleUri)
		if err != nil {
			return fmt.Errorf("error reading 'trustBundleUri': %w", err)
		}
		delete(object, "trustBundleUri")
	}

	if raw, found := object["trustDomain"]; found {
		err = json.Unmarshal(raw, &a.TrustDomain)
		if err != nil {
			return fmt.Errorf("error reading 'trustDomain': %w", err)
		}
		delete(object, "trustDomain")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for DiscoveryDocument to handle AdditionalProperties
func (a DiscoveryDocument) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["trustBundleUri"], err = json.Marshal(a.TrustBundleUri)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'trustBundleUri': %w", err)
	}

	object["trustDomain"], err = json.Marshal(a.TrustDomain)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'trustDomain': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}
