version: '3.8'

services:
  device-agent:
    container_name: workload-fleet-management-client
    image: ${workload_Fleet_Management_Client_IMAGE_REF:-ghcr.io/margo/margo.org/workload-fleet-management-client:latest}
    pull_policy: never  # Options: always, never, missing, build
    # Add log rotation configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"      # Maximum size of each log file
        max-file: "3"        # Keep 3 rotated files (30MB total)
        compress: "true"     # Compress rotated logs (optional)
    volumes:
      # - /root/.kube/config:/root/.kube/config:ro # to manage kubernetes runtimes
      - /var/run/docker.sock:/var/run/docker.sock # to manage docker runtimes
      - ./config/config.yaml:/config/config.yaml
      - ./config/capabilities.json:/config/capabilities.json
      - ./config/device-private.key:/config/device-private.key
      - ./config/device-public.crt:/config/device-public.crt
      - ./config/device-ecdsa.key:/config/device-ecdsa.key
      - ./config/device-ecdsa.crt:/config/device-ecdsa.crt
      - ./config/ca-cert.pem:/config/ca-cert.pem
      - ./data:/var/lib/margo/device-agent/data #should be changed to whatever is set as dataDir in config.yaml for device agent
    restart: unless-stopped
    entrypoint: ["./device-agent"]
    command: ["-config", "config/config.yaml"]
