// Package sbi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package sbi

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"go.yaml.in/yaml/v3"

	"github.com/oapi-codegen/runtime"
)

// RequestEditorFn is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {

	// GetApiV1ClientsClientIdBundlesDigest Retrieve bundle information for a specific device and digest
	//
	// Corresponds with GET /api/v1/clients/{clientId}/bundles/{digest} (the `GetApiV1ClientsClientIdBundlesDigest` operationId).
	GetApiV1ClientsClientIdBundlesDigest(ctx context.Context, clientId string, digest string, params *GetApiV1ClientsClientIdBundlesDigestParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteApiV1ClientsClientIdCapabilitiesDeviceId Remove device (Unregister)
	//
	// Corresponds with DELETE /api/v1/clients/{clientId}/capabilities/{deviceId} (the `DeleteApiV1ClientsClientIdCapabilitiesDeviceId` operationId).
	DeleteApiV1ClientsClientIdCapabilitiesDeviceId(ctx context.Context, clientId string, deviceId DeviceId, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostApiV1ClientsClientIdCapabilitiesDeviceIdWithBody Report device capabilities
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with POST /api/v1/clients/{clientId}/capabilities/{deviceId} (the `PostApiV1ClientsClientIdCapabilitiesDeviceId` operationId).
	PostApiV1ClientsClientIdCapabilitiesDeviceIdWithBody(ctx context.Context, clientId string, deviceId DeviceId, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostApiV1ClientsClientIdCapabilitiesDeviceId Report device capabilities
	//
	// Takes a body of the `application/json` content type.
	//
	// Corresponds with POST /api/v1/clients/{clientId}/capabilities/{deviceId} (the `PostApiV1ClientsClientIdCapabilitiesDeviceId` operationId).
	PostApiV1ClientsClientIdCapabilitiesDeviceId(ctx context.Context, clientId string, deviceId DeviceId, body PostApiV1ClientsClientIdCapabilitiesDeviceIdJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PutApiV1ClientsClientIdCapabilitiesDeviceIdWithBody Update device capabilities (Update)
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with PUT /api/v1/clients/{clientId}/capabilities/{deviceId} (the `PutApiV1ClientsClientIdCapabilitiesDeviceId` operationId).
	PutApiV1ClientsClientIdCapabilitiesDeviceIdWithBody(ctx context.Context, clientId string, deviceId DeviceId, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PutApiV1ClientsClientIdCapabilitiesDeviceId Update device capabilities (Update)
	//
	// Takes a body of the `application/json` content type.
	//
	// Corresponds with PUT /api/v1/clients/{clientId}/capabilities/{deviceId} (the `PutApiV1ClientsClientIdCapabilitiesDeviceId` operationId).
	PutApiV1ClientsClientIdCapabilitiesDeviceId(ctx context.Context, clientId string, deviceId DeviceId, body PutApiV1ClientsClientIdCapabilitiesDeviceIdJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetApiV1ClientsClientIdDeployments Retrieve the complete desired state for all workloads assigned to a device
	//
	// Corresponds with GET /api/v1/clients/{clientId}/deployments (the `GetApiV1ClientsClientIdDeployments` operationId).
	GetApiV1ClientsClientIdDeployments(ctx context.Context, clientId string, params *GetApiV1ClientsClientIdDeploymentsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostApiV1ClientsClientIdDeploymentsDeploymentIdStatusWithBody Report deployment status
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with POST /api/v1/clients/{clientId}/deployments/{deploymentId}/status (the `PostApiV1ClientsClientIdDeploymentsDeploymentIdStatus` operationId).
	PostApiV1ClientsClientIdDeploymentsDeploymentIdStatusWithBody(ctx context.Context, clientId string, deploymentId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostApiV1ClientsClientIdDeploymentsDeploymentIdStatus Report deployment status
	//
	// Takes a body of the `application/json` content type.
	//
	// Corresponds with POST /api/v1/clients/{clientId}/deployments/{deploymentId}/status (the `PostApiV1ClientsClientIdDeploymentsDeploymentIdStatus` operationId).
	PostApiV1ClientsClientIdDeploymentsDeploymentIdStatus(ctx context.Context, clientId string, deploymentId string, body PostApiV1ClientsClientIdDeploymentsDeploymentIdStatusJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetApiV1ClientsClientIdDeploymentsDeploymentIdDigest Retrieve an individual ApplicationDeployment YAML file
	//
	// This endpoint is used by the client to fetch the YAML for a single ApplicationDeployment after it has processed a new State Manifest and identified a small number of new or updated deployments. This allows for highly efficient, incremental updates without needing to download the full bundle. To make individual workload retrievals race-free and cache-friendly, this endpoint is content-addressable: the digest of the expected YAML is part of the URL. This guarantees immutability of the fetched resource and prevents a time-of-check / time-of-use race where a deployment changes between manifest retrieval and content fetch.
	//
	// Corresponds with GET /api/v1/clients/{clientId}/deployments/{deploymentId}/{digest} (the `GetApiV1ClientsClientIdDeploymentsDeploymentIdDigest` operationId).
	GetApiV1ClientsClientIdDeploymentsDeploymentIdDigest(ctx context.Context, clientId string, deploymentId string, digest string, params *GetApiV1ClientsClientIdDeploymentsDeploymentIdDigestParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostApiV1OnboardingWithBody Complete onboarding with client certificate
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with POST /api/v1/onboarding (the `PostApiV1Onboarding` operationId).
	PostApiV1OnboardingWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostApiV1Onboarding Complete onboarding with client certificate
	//
	// Takes a body of the `application/json` content type.
	//
	// Corresponds with POST /api/v1/onboarding (the `PostApiV1Onboarding` operationId).
	PostApiV1Onboarding(ctx context.Context, body PostApiV1OnboardingJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetApiV1OnboardingCertificate Download Root CA certificate
	//
	// Corresponds with GET /api/v1/onboarding/certificate (the `GetApiV1OnboardingCertificate` operationId).
	GetApiV1OnboardingCertificate(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)
}

// GetApiV1ClientsClientIdBundlesDigest Retrieve bundle information for a specific device and digest
//
// Corresponds with GET /api/v1/clients/{clientId}/bundles/{digest} (the `GetApiV1ClientsClientIdBundlesDigest` operationId).
func (c *Client) GetApiV1ClientsClientIdBundlesDigest(ctx context.Context, clientId string, digest string, params *GetApiV1ClientsClientIdBundlesDigestParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetApiV1ClientsClientIdBundlesDigestRequest(c.Server, clientId, digest, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// DeleteApiV1ClientsClientIdCapabilitiesDeviceId Remove device (Unregister)
//
// Corresponds with DELETE /api/v1/clients/{clientId}/capabilities/{deviceId} (the `DeleteApiV1ClientsClientIdCapabilitiesDeviceId` operationId).
func (c *Client) DeleteApiV1ClientsClientIdCapabilitiesDeviceId(ctx context.Context, clientId string, deviceId DeviceId, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteApiV1ClientsClientIdCapabilitiesDeviceIdRequest(c.Server, clientId, deviceId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// PostApiV1ClientsClientIdCapabilitiesDeviceIdWithBody Report device capabilities
//
// Takes any type of body and a specified content type.
//
// Corresponds with POST /api/v1/clients/{clientId}/capabilities/{deviceId} (the `PostApiV1ClientsClientIdCapabilitiesDeviceId` operationId).
func (c *Client) PostApiV1ClientsClientIdCapabilitiesDeviceIdWithBody(ctx context.Context, clientId string, deviceId DeviceId, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostApiV1ClientsClientIdCapabilitiesDeviceIdRequestWithBody(c.Server, clientId, deviceId, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// PostApiV1ClientsClientIdCapabilitiesDeviceId Report device capabilities
//
// Takes a body of the `application/json` content type.
//
// Corresponds with POST /api/v1/clients/{clientId}/capabilities/{deviceId} (the `PostApiV1ClientsClientIdCapabilitiesDeviceId` operationId).
func (c *Client) PostApiV1ClientsClientIdCapabilitiesDeviceId(ctx context.Context, clientId string, deviceId DeviceId, body PostApiV1ClientsClientIdCapabilitiesDeviceIdJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostApiV1ClientsClientIdCapabilitiesDeviceIdRequest(c.Server, clientId, deviceId, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// PutApiV1ClientsClientIdCapabilitiesDeviceIdWithBody Update device capabilities (Update)
//
// Takes any type of body and a specified content type.
//
// Corresponds with PUT /api/v1/clients/{clientId}/capabilities/{deviceId} (the `PutApiV1ClientsClientIdCapabilitiesDeviceId` operationId).
func (c *Client) PutApiV1ClientsClientIdCapabilitiesDeviceIdWithBody(ctx context.Context, clientId string, deviceId DeviceId, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPutApiV1ClientsClientIdCapabilitiesDeviceIdRequestWithBody(c.Server, clientId, deviceId, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// PutApiV1ClientsClientIdCapabilitiesDeviceId Update device capabilities (Update)
//
// Takes a body of the `application/json` content type.
//
// Corresponds with PUT /api/v1/clients/{clientId}/capabilities/{deviceId} (the `PutApiV1ClientsClientIdCapabilitiesDeviceId` operationId).
func (c *Client) PutApiV1ClientsClientIdCapabilitiesDeviceId(ctx context.Context, clientId string, deviceId DeviceId, body PutApiV1ClientsClientIdCapabilitiesDeviceIdJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPutApiV1ClientsClientIdCapabilitiesDeviceIdRequest(c.Server, clientId, deviceId, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetApiV1ClientsClientIdDeployments Retrieve the complete desired state for all workloads assigned to a device
//
// Corresponds with GET /api/v1/clients/{clientId}/deployments (the `GetApiV1ClientsClientIdDeployments` operationId).
func (c *Client) GetApiV1ClientsClientIdDeployments(ctx context.Context, clientId string, params *GetApiV1ClientsClientIdDeploymentsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetApiV1ClientsClientIdDeploymentsRequest(c.Server, clientId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// PostApiV1ClientsClientIdDeploymentsDeploymentIdStatusWithBody Report deployment status
//
// Takes any type of body and a specified content type.
//
// Corresponds with POST /api/v1/clients/{clientId}/deployments/{deploymentId}/status (the `PostApiV1ClientsClientIdDeploymentsDeploymentIdStatus` operationId).
func (c *Client) PostApiV1ClientsClientIdDeploymentsDeploymentIdStatusWithBody(ctx context.Context, clientId string, deploymentId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostApiV1ClientsClientIdDeploymentsDeploymentIdStatusRequestWithBody(c.Server, clientId, deploymentId, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// PostApiV1ClientsClientIdDeploymentsDeploymentIdStatus Report deployment status
//
// Takes a body of the `application/json` content type.
//
// Corresponds with POST /api/v1/clients/{clientId}/deployments/{deploymentId}/status (the `PostApiV1ClientsClientIdDeploymentsDeploymentIdStatus` operationId).
func (c *Client) PostApiV1ClientsClientIdDeploymentsDeploymentIdStatus(ctx context.Context, clientId string, deploymentId string, body PostApiV1ClientsClientIdDeploymentsDeploymentIdStatusJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostApiV1ClientsClientIdDeploymentsDeploymentIdStatusRequest(c.Server, clientId, deploymentId, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetApiV1ClientsClientIdDeploymentsDeploymentIdDigest Retrieve an individual ApplicationDeployment YAML file
//
// This endpoint is used by the client to fetch the YAML for a single ApplicationDeployment after it has processed a new State Manifest and identified a small number of new or updated deployments. This allows for highly efficient, incremental updates without needing to download the full bundle. To make individual workload retrievals race-free and cache-friendly, this endpoint is content-addressable: the digest of the expected YAML is part of the URL. This guarantees immutability of the fetched resource and prevents a time-of-check / time-of-use race where a deployment changes between manifest retrieval and content fetch.
//
// Corresponds with GET /api/v1/clients/{clientId}/deployments/{deploymentId}/{digest} (the `GetApiV1ClientsClientIdDeploymentsDeploymentIdDigest` operationId).
func (c *Client) GetApiV1ClientsClientIdDeploymentsDeploymentIdDigest(ctx context.Context, clientId string, deploymentId string, digest string, params *GetApiV1ClientsClientIdDeploymentsDeploymentIdDigestParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetApiV1ClientsClientIdDeploymentsDeploymentIdDigestRequest(c.Server, clientId, deploymentId, digest, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// PostApiV1OnboardingWithBody Complete onboarding with client certificate
//
// Takes any type of body and a specified content type.
//
// Corresponds with POST /api/v1/onboarding (the `PostApiV1Onboarding` operationId).
func (c *Client) PostApiV1OnboardingWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostApiV1OnboardingRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// PostApiV1Onboarding Complete onboarding with client certificate
//
// Takes a body of the `application/json` content type.
//
// Corresponds with POST /api/v1/onboarding (the `PostApiV1Onboarding` operationId).
func (c *Client) PostApiV1Onboarding(ctx context.Context, body PostApiV1OnboardingJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostApiV1OnboardingRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetApiV1OnboardingCertificate Download Root CA certificate
//
// Corresponds with GET /api/v1/onboarding/certificate (the `GetApiV1OnboardingCertificate` operationId).
func (c *Client) GetApiV1OnboardingCertificate(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetApiV1OnboardingCertificateRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetApiV1ClientsClientIdBundlesDigestRequest constructs an http.Request for the GetApiV1ClientsClientIdBundlesDigest method
func NewGetApiV1ClientsClientIdBundlesDigestRequest(server string, clientId string, digest string, params *GetApiV1ClientsClientIdBundlesDigestParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "clientId", clientId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithOptions("simple", false, "digest", digest, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/clients/%s/bundles/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	if params != nil {

		if params.IfNoneMatch != nil {
			var headerParam0 string

			headerParam0, err = runtime.StyleParamWithOptions("simple", false, "If-None-Match", *params.IfNoneMatch, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("If-None-Match", headerParam0)
		}

	}

	return req, nil
}

// NewDeleteApiV1ClientsClientIdCapabilitiesDeviceIdRequest constructs an http.Request for the DeleteApiV1ClientsClientIdCapabilitiesDeviceId method
func NewDeleteApiV1ClientsClientIdCapabilitiesDeviceIdRequest(server string, clientId string, deviceId DeviceId) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "clientId", clientId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithOptions("simple", false, "deviceId", deviceId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/clients/%s/capabilities/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodDelete, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostApiV1ClientsClientIdCapabilitiesDeviceIdRequest calls the generic PostApiV1ClientsClientIdCapabilitiesDeviceId builder with application/json body
func NewPostApiV1ClientsClientIdCapabilitiesDeviceIdRequest(server string, clientId string, deviceId DeviceId, body PostApiV1ClientsClientIdCapabilitiesDeviceIdJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostApiV1ClientsClientIdCapabilitiesDeviceIdRequestWithBody(server, clientId, deviceId, "application/json", bodyReader)
}

// NewPostApiV1ClientsClientIdCapabilitiesDeviceIdRequestWithBody constructs an http.Request for the PostApiV1ClientsClientIdCapabilitiesDeviceId method, with any body, and a specified content type
func NewPostApiV1ClientsClientIdCapabilitiesDeviceIdRequestWithBody(server string, clientId string, deviceId DeviceId, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "clientId", clientId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithOptions("simple", false, "deviceId", deviceId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/clients/%s/capabilities/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewPutApiV1ClientsClientIdCapabilitiesDeviceIdRequest calls the generic PutApiV1ClientsClientIdCapabilitiesDeviceId builder with application/json body
func NewPutApiV1ClientsClientIdCapabilitiesDeviceIdRequest(server string, clientId string, deviceId DeviceId, body PutApiV1ClientsClientIdCapabilitiesDeviceIdJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPutApiV1ClientsClientIdCapabilitiesDeviceIdRequestWithBody(server, clientId, deviceId, "application/json", bodyReader)
}

// NewPutApiV1ClientsClientIdCapabilitiesDeviceIdRequestWithBody constructs an http.Request for the PutApiV1ClientsClientIdCapabilitiesDeviceId method, with any body, and a specified content type
func NewPutApiV1ClientsClientIdCapabilitiesDeviceIdRequestWithBody(server string, clientId string, deviceId DeviceId, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "clientId", clientId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithOptions("simple", false, "deviceId", deviceId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/clients/%s/capabilities/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPut, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetApiV1ClientsClientIdDeploymentsRequest constructs an http.Request for the GetApiV1ClientsClientIdDeployments method
func NewGetApiV1ClientsClientIdDeploymentsRequest(server string, clientId string, params *GetApiV1ClientsClientIdDeploymentsParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "clientId", clientId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/clients/%s/deployments", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	if params != nil {

		if params.IfNoneMatch != nil {
			var headerParam0 string

			headerParam0, err = runtime.StyleParamWithOptions("simple", false, "If-None-Match", *params.IfNoneMatch, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("If-None-Match", headerParam0)
		}

		if params.Accept != nil {
			var headerParam1 string

			headerParam1, err = runtime.StyleParamWithOptions("simple", false, "Accept", *params.Accept, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("Accept", headerParam1)
		}

	}

	return req, nil
}

// NewPostApiV1ClientsClientIdDeploymentsDeploymentIdStatusRequest calls the generic PostApiV1ClientsClientIdDeploymentsDeploymentIdStatus builder with application/json body
func NewPostApiV1ClientsClientIdDeploymentsDeploymentIdStatusRequest(server string, clientId string, deploymentId string, body PostApiV1ClientsClientIdDeploymentsDeploymentIdStatusJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostApiV1ClientsClientIdDeploymentsDeploymentIdStatusRequestWithBody(server, clientId, deploymentId, "application/json", bodyReader)
}

// NewPostApiV1ClientsClientIdDeploymentsDeploymentIdStatusRequestWithBody constructs an http.Request for the PostApiV1ClientsClientIdDeploymentsDeploymentIdStatus method, with any body, and a specified content type
func NewPostApiV1ClientsClientIdDeploymentsDeploymentIdStatusRequestWithBody(server string, clientId string, deploymentId string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "clientId", clientId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithOptions("simple", false, "deploymentId", deploymentId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/clients/%s/deployments/%s/status", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetApiV1ClientsClientIdDeploymentsDeploymentIdDigestRequest constructs an http.Request for the GetApiV1ClientsClientIdDeploymentsDeploymentIdDigest method
func NewGetApiV1ClientsClientIdDeploymentsDeploymentIdDigestRequest(server string, clientId string, deploymentId string, digest string, params *GetApiV1ClientsClientIdDeploymentsDeploymentIdDigestParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "clientId", clientId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithOptions("simple", false, "deploymentId", deploymentId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	var pathParam2 string

	pathParam2, err = runtime.StyleParamWithOptions("simple", false, "digest", digest, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/clients/%s/deployments/%s/%s", pathParam0, pathParam1, pathParam2)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	if params != nil {

		if params.IfNoneMatch != nil {
			var headerParam0 string

			headerParam0, err = runtime.StyleParamWithOptions("simple", false, "If-None-Match", *params.IfNoneMatch, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("If-None-Match", headerParam0)
		}

		if params.AcceptEncoding != nil {
			var headerParam1 string

			headerParam1, err = runtime.StyleParamWithOptions("simple", false, "Accept-Encoding", *params.AcceptEncoding, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("Accept-Encoding", headerParam1)
		}

	}

	return req, nil
}

// NewPostApiV1OnboardingRequest calls the generic PostApiV1Onboarding builder with application/json body
func NewPostApiV1OnboardingRequest(server string, body PostApiV1OnboardingJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostApiV1OnboardingRequestWithBody(server, "application/json", bodyReader)
}

// NewPostApiV1OnboardingRequestWithBody constructs an http.Request for the PostApiV1Onboarding method, with any body, and a specified content type
func NewPostApiV1OnboardingRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/onboarding")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetApiV1OnboardingCertificateRequest constructs an http.Request for the GetApiV1OnboardingCertificate method
func NewGetApiV1OnboardingCertificateRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/onboarding/certificate")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {

	// GetApiV1ClientsClientIdBundlesDigestWithResponse Retrieve bundle information for a specific device and digest
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /api/v1/clients/{clientId}/bundles/{digest} (the `GetApiV1ClientsClientIdBundlesDigest` operationId).
	GetApiV1ClientsClientIdBundlesDigestWithResponse(ctx context.Context, clientId string, digest string, params *GetApiV1ClientsClientIdBundlesDigestParams, reqEditors ...RequestEditorFn) (*GetApiV1ClientsClientIdBundlesDigestResponse, error)

	// DeleteApiV1ClientsClientIdCapabilitiesDeviceIdWithResponse Remove device (Unregister)
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with DELETE /api/v1/clients/{clientId}/capabilities/{deviceId} (the `DeleteApiV1ClientsClientIdCapabilitiesDeviceId` operationId).
	DeleteApiV1ClientsClientIdCapabilitiesDeviceIdWithResponse(ctx context.Context, clientId string, deviceId DeviceId, reqEditors ...RequestEditorFn) (*DeleteApiV1ClientsClientIdCapabilitiesDeviceIdResponse, error)

	// PostApiV1ClientsClientIdCapabilitiesDeviceIdWithBodyWithResponse Report device capabilities
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /api/v1/clients/{clientId}/capabilities/{deviceId} (the `PostApiV1ClientsClientIdCapabilitiesDeviceId` operationId).
	PostApiV1ClientsClientIdCapabilitiesDeviceIdWithBodyWithResponse(ctx context.Context, clientId string, deviceId DeviceId, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostApiV1ClientsClientIdCapabilitiesDeviceIdResponse, error)

	// PostApiV1ClientsClientIdCapabilitiesDeviceIdWithResponse Report device capabilities
	//
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /api/v1/clients/{clientId}/capabilities/{deviceId} (the `PostApiV1ClientsClientIdCapabilitiesDeviceId` operationId).
	PostApiV1ClientsClientIdCapabilitiesDeviceIdWithResponse(ctx context.Context, clientId string, deviceId DeviceId, body PostApiV1ClientsClientIdCapabilitiesDeviceIdJSONRequestBody, reqEditors ...RequestEditorFn) (*PostApiV1ClientsClientIdCapabilitiesDeviceIdResponse, error)

	// PutApiV1ClientsClientIdCapabilitiesDeviceIdWithBodyWithResponse Update device capabilities (Update)
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with PUT /api/v1/clients/{clientId}/capabilities/{deviceId} (the `PutApiV1ClientsClientIdCapabilitiesDeviceId` operationId).
	PutApiV1ClientsClientIdCapabilitiesDeviceIdWithBodyWithResponse(ctx context.Context, clientId string, deviceId DeviceId, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PutApiV1ClientsClientIdCapabilitiesDeviceIdResponse, error)

	// PutApiV1ClientsClientIdCapabilitiesDeviceIdWithResponse Update device capabilities (Update)
	//
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with PUT /api/v1/clients/{clientId}/capabilities/{deviceId} (the `PutApiV1ClientsClientIdCapabilitiesDeviceId` operationId).
	PutApiV1ClientsClientIdCapabilitiesDeviceIdWithResponse(ctx context.Context, clientId string, deviceId DeviceId, body PutApiV1ClientsClientIdCapabilitiesDeviceIdJSONRequestBody, reqEditors ...RequestEditorFn) (*PutApiV1ClientsClientIdCapabilitiesDeviceIdResponse, error)

	// GetApiV1ClientsClientIdDeploymentsWithResponse Retrieve the complete desired state for all workloads assigned to a device
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /api/v1/clients/{clientId}/deployments (the `GetApiV1ClientsClientIdDeployments` operationId).
	GetApiV1ClientsClientIdDeploymentsWithResponse(ctx context.Context, clientId string, params *GetApiV1ClientsClientIdDeploymentsParams, reqEditors ...RequestEditorFn) (*GetApiV1ClientsClientIdDeploymentsResponse, error)

	// PostApiV1ClientsClientIdDeploymentsDeploymentIdStatusWithBodyWithResponse Report deployment status
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /api/v1/clients/{clientId}/deployments/{deploymentId}/status (the `PostApiV1ClientsClientIdDeploymentsDeploymentIdStatus` operationId).
	PostApiV1ClientsClientIdDeploymentsDeploymentIdStatusWithBodyWithResponse(ctx context.Context, clientId string, deploymentId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostApiV1ClientsClientIdDeploymentsDeploymentIdStatusResponse, error)

	// PostApiV1ClientsClientIdDeploymentsDeploymentIdStatusWithResponse Report deployment status
	//
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /api/v1/clients/{clientId}/deployments/{deploymentId}/status (the `PostApiV1ClientsClientIdDeploymentsDeploymentIdStatus` operationId).
	PostApiV1ClientsClientIdDeploymentsDeploymentIdStatusWithResponse(ctx context.Context, clientId string, deploymentId string, body PostApiV1ClientsClientIdDeploymentsDeploymentIdStatusJSONRequestBody, reqEditors ...RequestEditorFn) (*PostApiV1ClientsClientIdDeploymentsDeploymentIdStatusResponse, error)

	// GetApiV1ClientsClientIdDeploymentsDeploymentIdDigestWithResponse Retrieve an individual ApplicationDeployment YAML file
	//
	// This endpoint is used by the client to fetch the YAML for a single ApplicationDeployment after it has processed a new State Manifest and identified a small number of new or updated deployments. This allows for highly efficient, incremental updates without needing to download the full bundle. To make individual workload retrievals race-free and cache-friendly, this endpoint is content-addressable: the digest of the expected YAML is part of the URL. This guarantees immutability of the fetched resource and prevents a time-of-check / time-of-use race where a deployment changes between manifest retrieval and content fetch.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /api/v1/clients/{clientId}/deployments/{deploymentId}/{digest} (the `GetApiV1ClientsClientIdDeploymentsDeploymentIdDigest` operationId).
	GetApiV1ClientsClientIdDeploymentsDeploymentIdDigestWithResponse(ctx context.Context, clientId string, deploymentId string, digest string, params *GetApiV1ClientsClientIdDeploymentsDeploymentIdDigestParams, reqEditors ...RequestEditorFn) (*GetApiV1ClientsClientIdDeploymentsDeploymentIdDigestResponse, error)

	// PostApiV1OnboardingWithBodyWithResponse Complete onboarding with client certificate
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /api/v1/onboarding (the `PostApiV1Onboarding` operationId).
	PostApiV1OnboardingWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostApiV1OnboardingResponse, error)

	// PostApiV1OnboardingWithResponse Complete onboarding with client certificate
	//
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /api/v1/onboarding (the `PostApiV1Onboarding` operationId).
	PostApiV1OnboardingWithResponse(ctx context.Context, body PostApiV1OnboardingJSONRequestBody, reqEditors ...RequestEditorFn) (*PostApiV1OnboardingResponse, error)

	// GetApiV1OnboardingCertificateWithResponse Download Root CA certificate
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /api/v1/onboarding/certificate (the `GetApiV1OnboardingCertificate` operationId).
	GetApiV1OnboardingCertificateWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetApiV1OnboardingCertificateResponse, error)
}

// GetApiV1ClientsClientIdBundlesDigestResponse200Headers the declared response headers of an HTTP 200 response for GetApiV1ClientsClientIdBundlesDigest
type GetApiV1ClientsClientIdBundlesDigestResponse200Headers struct {
	CacheControl *string
	ETag         *string
}

type GetApiV1ClientsClientIdBundlesDigestResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// Headers200 the parsed response headers for an HTTP 200 response
	Headers200 *GetApiV1ClientsClientIdBundlesDigestResponse200Headers
}

// GetBody returns the raw response body bytes
func (r GetApiV1ClientsClientIdBundlesDigestResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetApiV1ClientsClientIdBundlesDigestResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetApiV1ClientsClientIdBundlesDigestResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetApiV1ClientsClientIdBundlesDigestResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type DeleteApiV1ClientsClientIdCapabilitiesDeviceIdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// GetBody returns the raw response body bytes
func (r DeleteApiV1ClientsClientIdCapabilitiesDeviceIdResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r DeleteApiV1ClientsClientIdCapabilitiesDeviceIdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteApiV1ClientsClientIdCapabilitiesDeviceIdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r DeleteApiV1ClientsClientIdCapabilitiesDeviceIdResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type PostApiV1ClientsClientIdCapabilitiesDeviceIdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// GetBody returns the raw response body bytes
func (r PostApiV1ClientsClientIdCapabilitiesDeviceIdResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r PostApiV1ClientsClientIdCapabilitiesDeviceIdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostApiV1ClientsClientIdCapabilitiesDeviceIdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r PostApiV1ClientsClientIdCapabilitiesDeviceIdResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type PutApiV1ClientsClientIdCapabilitiesDeviceIdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// GetBody returns the raw response body bytes
func (r PutApiV1ClientsClientIdCapabilitiesDeviceIdResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r PutApiV1ClientsClientIdCapabilitiesDeviceIdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PutApiV1ClientsClientIdCapabilitiesDeviceIdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r PutApiV1ClientsClientIdCapabilitiesDeviceIdResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// GetApiV1ClientsClientIdDeploymentsResponse200Headers the declared response headers of an HTTP 200 response for GetApiV1ClientsClientIdDeployments
type GetApiV1ClientsClientIdDeploymentsResponse200Headers struct {
	ContentType *string
	ETag        *string
}

type GetApiV1ClientsClientIdDeploymentsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// ApplicationvndMargoManifestV1JSON200 the response for an HTTP 200 `application/vnd.margo.manifest.v1+json` response
	ApplicationvndMargoManifestV1JSON200 *UnsignedAppStateManifest
	// Headers200 the parsed response headers for an HTTP 200 response
	Headers200 *GetApiV1ClientsClientIdDeploymentsResponse200Headers
}

// GetApplicationvndMargoManifestV1JSON200 returns the response for an HTTP 200 `application/vnd.margo.manifest.v1+json` response
func (r GetApiV1ClientsClientIdDeploymentsResponse) GetApplicationvndMargoManifestV1JSON200() *UnsignedAppStateManifest {
	return r.ApplicationvndMargoManifestV1JSON200
}

// GetBody returns the raw response body bytes
func (r GetApiV1ClientsClientIdDeploymentsResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetApiV1ClientsClientIdDeploymentsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetApiV1ClientsClientIdDeploymentsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetApiV1ClientsClientIdDeploymentsResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type PostApiV1ClientsClientIdDeploymentsDeploymentIdStatusResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// GetBody returns the raw response body bytes
func (r PostApiV1ClientsClientIdDeploymentsDeploymentIdStatusResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r PostApiV1ClientsClientIdDeploymentsDeploymentIdStatusResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostApiV1ClientsClientIdDeploymentsDeploymentIdStatusResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r PostApiV1ClientsClientIdDeploymentsDeploymentIdStatusResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// GetApiV1ClientsClientIdDeploymentsDeploymentIdDigestResponse200Headers the declared response headers of an HTTP 200 response for GetApiV1ClientsClientIdDeploymentsDeploymentIdDigest
type GetApiV1ClientsClientIdDeploymentsDeploymentIdDigestResponse200Headers struct {
	CacheControl *string
	ContentType  *string
	ETag         *string
	Vary         *string
}

type GetApiV1ClientsClientIdDeploymentsDeploymentIdDigestResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// YAML200 the response for an HTTP 200 `application/yaml` response
	YAML200 *string
	// Headers200 the parsed response headers for an HTTP 200 response
	Headers200 *GetApiV1ClientsClientIdDeploymentsDeploymentIdDigestResponse200Headers
}

// GetYAML200 returns the response for an HTTP 200 `application/yaml` response
func (r GetApiV1ClientsClientIdDeploymentsDeploymentIdDigestResponse) GetYAML200() *string {
	return r.YAML200
}

// GetBody returns the raw response body bytes
func (r GetApiV1ClientsClientIdDeploymentsDeploymentIdDigestResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetApiV1ClientsClientIdDeploymentsDeploymentIdDigestResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetApiV1ClientsClientIdDeploymentsDeploymentIdDigestResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetApiV1ClientsClientIdDeploymentsDeploymentIdDigestResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type PostApiV1OnboardingResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON201 the response for an HTTP 201 `application/json` response
	JSON201 *struct {
		ClientId *string `json:"clientId,omitempty"`
	}
	// JSON400 the response for an HTTP 400 `application/json` response
	JSON400 *struct {
		Error *string `json:"error,omitempty"`
	}
	// JSON403 the response for an HTTP 403 `application/json` response
	JSON403 *struct {
		Error *string `json:"error,omitempty"`
	}
}

// GetJSON201 returns the response for an HTTP 201 `application/json` response
func (r PostApiV1OnboardingResponse) GetJSON201() *struct {
	ClientId *string `json:"clientId,omitempty"`
} {
	return r.JSON201
}

// GetJSON400 returns the response for an HTTP 400 `application/json` response
func (r PostApiV1OnboardingResponse) GetJSON400() *struct {
	Error *string `json:"error,omitempty"`
} {
	return r.JSON400
}

// GetJSON403 returns the response for an HTTP 403 `application/json` response
func (r PostApiV1OnboardingResponse) GetJSON403() *struct {
	Error *string `json:"error,omitempty"`
} {
	return r.JSON403
}

// GetBody returns the raw response body bytes
func (r PostApiV1OnboardingResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r PostApiV1OnboardingResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostApiV1OnboardingResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r PostApiV1OnboardingResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetApiV1OnboardingCertificateResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *struct {
		// Certificate Base64-encoded certificate text
		Certificate *string `json:"certificate,omitempty"`
	}
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r GetApiV1OnboardingCertificateResponse) GetJSON200() *struct {
	// Certificate Base64-encoded certificate text
	Certificate *string `json:"certificate,omitempty"`
} {
	return r.JSON200
}

// GetBody returns the raw response body bytes
func (r GetApiV1OnboardingCertificateResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetApiV1OnboardingCertificateResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetApiV1OnboardingCertificateResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetApiV1OnboardingCertificateResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// GetApiV1ClientsClientIdBundlesDigestWithResponse Retrieve bundle information for a specific device and digest
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /api/v1/clients/{clientId}/bundles/{digest} (the `GetApiV1ClientsClientIdBundlesDigest` operationId).
func (c *ClientWithResponses) GetApiV1ClientsClientIdBundlesDigestWithResponse(ctx context.Context, clientId string, digest string, params *GetApiV1ClientsClientIdBundlesDigestParams, reqEditors ...RequestEditorFn) (*GetApiV1ClientsClientIdBundlesDigestResponse, error) {
	rsp, err := c.GetApiV1ClientsClientIdBundlesDigest(ctx, clientId, digest, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetApiV1ClientsClientIdBundlesDigestResponse(rsp)
}

// DeleteApiV1ClientsClientIdCapabilitiesDeviceIdWithResponse Remove device (Unregister)
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with DELETE /api/v1/clients/{clientId}/capabilities/{deviceId} (the `DeleteApiV1ClientsClientIdCapabilitiesDeviceId` operationId).
func (c *ClientWithResponses) DeleteApiV1ClientsClientIdCapabilitiesDeviceIdWithResponse(ctx context.Context, clientId string, deviceId DeviceId, reqEditors ...RequestEditorFn) (*DeleteApiV1ClientsClientIdCapabilitiesDeviceIdResponse, error) {
	rsp, err := c.DeleteApiV1ClientsClientIdCapabilitiesDeviceId(ctx, clientId, deviceId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteApiV1ClientsClientIdCapabilitiesDeviceIdResponse(rsp)
}

// PostApiV1ClientsClientIdCapabilitiesDeviceIdWithBodyWithResponse Report device capabilities
//
// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /api/v1/clients/{clientId}/capabilities/{deviceId} (the `PostApiV1ClientsClientIdCapabilitiesDeviceId` operationId).
func (c *ClientWithResponses) PostApiV1ClientsClientIdCapabilitiesDeviceIdWithBodyWithResponse(ctx context.Context, clientId string, deviceId DeviceId, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostApiV1ClientsClientIdCapabilitiesDeviceIdResponse, error) {
	rsp, err := c.PostApiV1ClientsClientIdCapabilitiesDeviceIdWithBody(ctx, clientId, deviceId, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostApiV1ClientsClientIdCapabilitiesDeviceIdResponse(rsp)
}

// PostApiV1ClientsClientIdCapabilitiesDeviceIdWithResponse Report device capabilities
//
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /api/v1/clients/{clientId}/capabilities/{deviceId} (the `PostApiV1ClientsClientIdCapabilitiesDeviceId` operationId).
func (c *ClientWithResponses) PostApiV1ClientsClientIdCapabilitiesDeviceIdWithResponse(ctx context.Context, clientId string, deviceId DeviceId, body PostApiV1ClientsClientIdCapabilitiesDeviceIdJSONRequestBody, reqEditors ...RequestEditorFn) (*PostApiV1ClientsClientIdCapabilitiesDeviceIdResponse, error) {
	rsp, err := c.PostApiV1ClientsClientIdCapabilitiesDeviceId(ctx, clientId, deviceId, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostApiV1ClientsClientIdCapabilitiesDeviceIdResponse(rsp)
}

// PutApiV1ClientsClientIdCapabilitiesDeviceIdWithBodyWithResponse Update device capabilities (Update)
//
// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with PUT /api/v1/clients/{clientId}/capabilities/{deviceId} (the `PutApiV1ClientsClientIdCapabilitiesDeviceId` operationId).
func (c *ClientWithResponses) PutApiV1ClientsClientIdCapabilitiesDeviceIdWithBodyWithResponse(ctx context.Context, clientId string, deviceId DeviceId, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PutApiV1ClientsClientIdCapabilitiesDeviceIdResponse, error) {
	rsp, err := c.PutApiV1ClientsClientIdCapabilitiesDeviceIdWithBody(ctx, clientId, deviceId, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePutApiV1ClientsClientIdCapabilitiesDeviceIdResponse(rsp)
}

// PutApiV1ClientsClientIdCapabilitiesDeviceIdWithResponse Update device capabilities (Update)
//
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with PUT /api/v1/clients/{clientId}/capabilities/{deviceId} (the `PutApiV1ClientsClientIdCapabilitiesDeviceId` operationId).
func (c *ClientWithResponses) PutApiV1ClientsClientIdCapabilitiesDeviceIdWithResponse(ctx context.Context, clientId string, deviceId DeviceId, body PutApiV1ClientsClientIdCapabilitiesDeviceIdJSONRequestBody, reqEditors ...RequestEditorFn) (*PutApiV1ClientsClientIdCapabilitiesDeviceIdResponse, error) {
	rsp, err := c.PutApiV1ClientsClientIdCapabilitiesDeviceId(ctx, clientId, deviceId, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePutApiV1ClientsClientIdCapabilitiesDeviceIdResponse(rsp)
}

// GetApiV1ClientsClientIdDeploymentsWithResponse Retrieve the complete desired state for all workloads assigned to a device
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /api/v1/clients/{clientId}/deployments (the `GetApiV1ClientsClientIdDeployments` operationId).
func (c *ClientWithResponses) GetApiV1ClientsClientIdDeploymentsWithResponse(ctx context.Context, clientId string, params *GetApiV1ClientsClientIdDeploymentsParams, reqEditors ...RequestEditorFn) (*GetApiV1ClientsClientIdDeploymentsResponse, error) {
	rsp, err := c.GetApiV1ClientsClientIdDeployments(ctx, clientId, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetApiV1ClientsClientIdDeploymentsResponse(rsp)
}

// PostApiV1ClientsClientIdDeploymentsDeploymentIdStatusWithBodyWithResponse Report deployment status
//
// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /api/v1/clients/{clientId}/deployments/{deploymentId}/status (the `PostApiV1ClientsClientIdDeploymentsDeploymentIdStatus` operationId).
func (c *ClientWithResponses) PostApiV1ClientsClientIdDeploymentsDeploymentIdStatusWithBodyWithResponse(ctx context.Context, clientId string, deploymentId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostApiV1ClientsClientIdDeploymentsDeploymentIdStatusResponse, error) {
	rsp, err := c.PostApiV1ClientsClientIdDeploymentsDeploymentIdStatusWithBody(ctx, clientId, deploymentId, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostApiV1ClientsClientIdDeploymentsDeploymentIdStatusResponse(rsp)
}

// PostApiV1ClientsClientIdDeploymentsDeploymentIdStatusWithResponse Report deployment status
//
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /api/v1/clients/{clientId}/deployments/{deploymentId}/status (the `PostApiV1ClientsClientIdDeploymentsDeploymentIdStatus` operationId).
func (c *ClientWithResponses) PostApiV1ClientsClientIdDeploymentsDeploymentIdStatusWithResponse(ctx context.Context, clientId string, deploymentId string, body PostApiV1ClientsClientIdDeploymentsDeploymentIdStatusJSONRequestBody, reqEditors ...RequestEditorFn) (*PostApiV1ClientsClientIdDeploymentsDeploymentIdStatusResponse, error) {
	rsp, err := c.PostApiV1ClientsClientIdDeploymentsDeploymentIdStatus(ctx, clientId, deploymentId, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostApiV1ClientsClientIdDeploymentsDeploymentIdStatusResponse(rsp)
}

// GetApiV1ClientsClientIdDeploymentsDeploymentIdDigestWithResponse Retrieve an individual ApplicationDeployment YAML file
//
// This endpoint is used by the client to fetch the YAML for a single ApplicationDeployment after it has processed a new State Manifest and identified a small number of new or updated deployments. This allows for highly efficient, incremental updates without needing to download the full bundle. To make individual workload retrievals race-free and cache-friendly, this endpoint is content-addressable: the digest of the expected YAML is part of the URL. This guarantees immutability of the fetched resource and prevents a time-of-check / time-of-use race where a deployment changes between manifest retrieval and content fetch.
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /api/v1/clients/{clientId}/deployments/{deploymentId}/{digest} (the `GetApiV1ClientsClientIdDeploymentsDeploymentIdDigest` operationId).
func (c *ClientWithResponses) GetApiV1ClientsClientIdDeploymentsDeploymentIdDigestWithResponse(ctx context.Context, clientId string, deploymentId string, digest string, params *GetApiV1ClientsClientIdDeploymentsDeploymentIdDigestParams, reqEditors ...RequestEditorFn) (*GetApiV1ClientsClientIdDeploymentsDeploymentIdDigestResponse, error) {
	rsp, err := c.GetApiV1ClientsClientIdDeploymentsDeploymentIdDigest(ctx, clientId, deploymentId, digest, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetApiV1ClientsClientIdDeploymentsDeploymentIdDigestResponse(rsp)
}

// PostApiV1OnboardingWithBodyWithResponse Complete onboarding with client certificate
//
// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /api/v1/onboarding (the `PostApiV1Onboarding` operationId).
func (c *ClientWithResponses) PostApiV1OnboardingWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostApiV1OnboardingResponse, error) {
	rsp, err := c.PostApiV1OnboardingWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostApiV1OnboardingResponse(rsp)
}

// PostApiV1OnboardingWithResponse Complete onboarding with client certificate
//
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /api/v1/onboarding (the `PostApiV1Onboarding` operationId).
func (c *ClientWithResponses) PostApiV1OnboardingWithResponse(ctx context.Context, body PostApiV1OnboardingJSONRequestBody, reqEditors ...RequestEditorFn) (*PostApiV1OnboardingResponse, error) {
	rsp, err := c.PostApiV1Onboarding(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostApiV1OnboardingResponse(rsp)
}

// GetApiV1OnboardingCertificateWithResponse Download Root CA certificate
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /api/v1/onboarding/certificate (the `GetApiV1OnboardingCertificate` operationId).
func (c *ClientWithResponses) GetApiV1OnboardingCertificateWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetApiV1OnboardingCertificateResponse, error) {
	rsp, err := c.GetApiV1OnboardingCertificate(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetApiV1OnboardingCertificateResponse(rsp)
}

// ParseGetApiV1ClientsClientIdBundlesDigestResponse parses an HTTP response from a GetApiV1ClientsClientIdBundlesDigestWithResponse call
func ParseGetApiV1ClientsClientIdBundlesDigestResponse(rsp *http.Response) (*GetApiV1ClientsClientIdBundlesDigestResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetApiV1ClientsClientIdBundlesDigestResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case rsp.StatusCode == 200:
		var headers GetApiV1ClientsClientIdBundlesDigestResponse200Headers
		if values := rsp.Header.Values("Cache-Control"); len(values) > 0 {
			var value string
			if err := runtime.BindStyledParameterWithOptions("simple", "Cache-Control", values[0], &value, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""}); err != nil {
				return nil, err
			}
			headers.CacheControl = &value
		}
		if values := rsp.Header.Values("ETag"); len(values) > 0 {
			var value string
			if err := runtime.BindStyledParameterWithOptions("simple", "ETag", values[0], &value, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""}); err != nil {
				return nil, err
			}
			headers.ETag = &value
		}
		response.Headers200 = &headers
	}

	return response, nil
}

// ParseDeleteApiV1ClientsClientIdCapabilitiesDeviceIdResponse parses an HTTP response from a DeleteApiV1ClientsClientIdCapabilitiesDeviceIdWithResponse call
func ParseDeleteApiV1ClientsClientIdCapabilitiesDeviceIdResponse(rsp *http.Response) (*DeleteApiV1ClientsClientIdCapabilitiesDeviceIdResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteApiV1ClientsClientIdCapabilitiesDeviceIdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParsePostApiV1ClientsClientIdCapabilitiesDeviceIdResponse parses an HTTP response from a PostApiV1ClientsClientIdCapabilitiesDeviceIdWithResponse call
func ParsePostApiV1ClientsClientIdCapabilitiesDeviceIdResponse(rsp *http.Response) (*PostApiV1ClientsClientIdCapabilitiesDeviceIdResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostApiV1ClientsClientIdCapabilitiesDeviceIdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParsePutApiV1ClientsClientIdCapabilitiesDeviceIdResponse parses an HTTP response from a PutApiV1ClientsClientIdCapabilitiesDeviceIdWithResponse call
func ParsePutApiV1ClientsClientIdCapabilitiesDeviceIdResponse(rsp *http.Response) (*PutApiV1ClientsClientIdCapabilitiesDeviceIdResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PutApiV1ClientsClientIdCapabilitiesDeviceIdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseGetApiV1ClientsClientIdDeploymentsResponse parses an HTTP response from a GetApiV1ClientsClientIdDeploymentsWithResponse call
func ParseGetApiV1ClientsClientIdDeploymentsResponse(rsp *http.Response) (*GetApiV1ClientsClientIdDeploymentsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetApiV1ClientsClientIdDeploymentsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest UnsignedAppStateManifest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationvndMargoManifestV1JSON200 = &dest

	case rsp.StatusCode == 304:
		break // No content-type

	case rsp.StatusCode == 406:
		break // No content-type

	}

	switch {
	case rsp.StatusCode == 200:
		var headers GetApiV1ClientsClientIdDeploymentsResponse200Headers
		if values := rsp.Header.Values("Content-Type"); len(values) > 0 {
			var value string
			if err := runtime.BindStyledParameterWithOptions("simple", "Content-Type", values[0], &value, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""}); err != nil {
				return nil, err
			}
			headers.ContentType = &value
		}
		if values := rsp.Header.Values("ETag"); len(values) > 0 {
			var value string
			if err := runtime.BindStyledParameterWithOptions("simple", "ETag", values[0], &value, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""}); err != nil {
				return nil, err
			}
			headers.ETag = &value
		}
		response.Headers200 = &headers
	}

	return response, nil
}

// ParsePostApiV1ClientsClientIdDeploymentsDeploymentIdStatusResponse parses an HTTP response from a PostApiV1ClientsClientIdDeploymentsDeploymentIdStatusWithResponse call
func ParsePostApiV1ClientsClientIdDeploymentsDeploymentIdStatusResponse(rsp *http.Response) (*PostApiV1ClientsClientIdDeploymentsDeploymentIdStatusResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostApiV1ClientsClientIdDeploymentsDeploymentIdStatusResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseGetApiV1ClientsClientIdDeploymentsDeploymentIdDigestResponse parses an HTTP response from a GetApiV1ClientsClientIdDeploymentsDeploymentIdDigestWithResponse call
func ParseGetApiV1ClientsClientIdDeploymentsDeploymentIdDigestResponse(rsp *http.Response) (*GetApiV1ClientsClientIdDeploymentsDeploymentIdDigestResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetApiV1ClientsClientIdDeploymentsDeploymentIdDigestResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "yaml") && rsp.StatusCode == 200:
		var dest string
		if err := yaml.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.YAML200 = &dest

	case rsp.StatusCode == 404:
		break // No content-type

	}

	switch {
	case rsp.StatusCode == 200:
		var headers GetApiV1ClientsClientIdDeploymentsDeploymentIdDigestResponse200Headers
		if values := rsp.Header.Values("Cache-Control"); len(values) > 0 {
			var value string
			if err := runtime.BindStyledParameterWithOptions("simple", "Cache-Control", values[0], &value, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""}); err != nil {
				return nil, err
			}
			headers.CacheControl = &value
		}
		if values := rsp.Header.Values("Content-Type"); len(values) > 0 {
			var value string
			if err := runtime.BindStyledParameterWithOptions("simple", "Content-Type", values[0], &value, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""}); err != nil {
				return nil, err
			}
			headers.ContentType = &value
		}
		if values := rsp.Header.Values("ETag"); len(values) > 0 {
			var value string
			if err := runtime.BindStyledParameterWithOptions("simple", "ETag", values[0], &value, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""}); err != nil {
				return nil, err
			}
			headers.ETag = &value
		}
		if values := rsp.Header.Values("Vary"); len(values) > 0 {
			var value string
			if err := runtime.BindStyledParameterWithOptions("simple", "Vary", values[0], &value, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""}); err != nil {
				return nil, err
			}
			headers.Vary = &value
		}
		response.Headers200 = &headers
	}

	return response, nil
}

// ParsePostApiV1OnboardingResponse parses an HTTP response from a PostApiV1OnboardingWithResponse call
func ParsePostApiV1OnboardingResponse(rsp *http.Response) (*PostApiV1OnboardingResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostApiV1OnboardingResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest struct {
			ClientId *string `json:"clientId,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest struct {
			Error *string `json:"error,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest struct {
			Error *string `json:"error,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	}

	return response, nil
}

// ParseGetApiV1OnboardingCertificateResponse parses an HTTP response from a GetApiV1OnboardingCertificateWithResponse call
func ParseGetApiV1OnboardingCertificateResponse(rsp *http.Response) (*GetApiV1OnboardingCertificateResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetApiV1OnboardingCertificateResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			// Certificate Base64-encoded certificate text
			Certificate *string `json:"certificate,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}
