// Package sbi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.3 DO NOT EDIT.
package sbi

const (
	PayloadSignatureScopes = "PayloadSignature.Scopes"
)

// Defines values for ComponentStatusState.
const (
	ComponentStatusStateFailed     ComponentStatusState = "failed"
	ComponentStatusStateInstalled  ComponentStatusState = "installed"
	ComponentStatusStateInstalling ComponentStatusState = "installing"
	ComponentStatusStatePending    ComponentStatusState = "pending"
	ComponentStatusStateRemoved    ComponentStatusState = "removed"
	ComponentStatusStateRemoving   ComponentStatusState = "removing"
)

// Defines values for DeploymentStatusManifestKind.
const (
	DeploymentStatusManifestKindDeploymentStatusManifest DeploymentStatusManifestKind = "DeploymentStatusManifest"
)

// Defines values for DeploymentStatusManifestStatusState.
const (
	DeploymentStatusManifestStatusStateFailed     DeploymentStatusManifestStatusState = "failed"
	DeploymentStatusManifestStatusStateInstalled  DeploymentStatusManifestStatusState = "installed"
	DeploymentStatusManifestStatusStateInstalling DeploymentStatusManifestStatusState = "installing"
	DeploymentStatusManifestStatusStatePending    DeploymentStatusManifestStatusState = "pending"
	DeploymentStatusManifestStatusStateRemoved    DeploymentStatusManifestStatusState = "removed"
	DeploymentStatusManifestStatusStateRemoving   DeploymentStatusManifestStatusState = "removing"
)

// Defines values for DeviceCapabilitiesManifestKind.
const (
	DeviceCapabilitiesManifestKindDeviceCapabilitiesManifest DeviceCapabilitiesManifestKind = "DeviceCapabilitiesManifest"
)

// Defines values for DeviceCapabilitiesManifestPropertiesResourcesCpuArchitecture.
const (
	Amd64 DeviceCapabilitiesManifestPropertiesResourcesCpuArchitecture = "amd64"
	Arm   DeviceCapabilitiesManifestPropertiesResourcesCpuArchitecture = "arm"
	Arm64 DeviceCapabilitiesManifestPropertiesResourcesCpuArchitecture = "arm64"
	X8664 DeviceCapabilitiesManifestPropertiesResourcesCpuArchitecture = "x86_64"
)

// Defines values for DeviceCapabilitiesManifestPropertiesRoles.
const (
	ClusterLeader     DeviceCapabilitiesManifestPropertiesRoles = "Cluster Leader"
	StandaloneCluster DeviceCapabilitiesManifestPropertiesRoles = "Standalone Cluster"
	StandaloneDevice  DeviceCapabilitiesManifestPropertiesRoles = "Standalone Device"
)

// Defines values for DeviceCommunicationInterfaceType.
const (
	Bluetooth DeviceCommunicationInterfaceType = "bluetooth"
	Canbus    DeviceCommunicationInterfaceType = "canbus"
	Cellular  DeviceCommunicationInterfaceType = "cellular"
	Ethernet  DeviceCommunicationInterfaceType = "ethernet"
	Rs232     DeviceCommunicationInterfaceType = "rs232"
	Usb       DeviceCommunicationInterfaceType = "usb"
	Wifi      DeviceCommunicationInterfaceType = "wifi"
)

// Defines values for DevicePeripheralType.
const (
	Camera     DevicePeripheralType = "camera"
	Display    DevicePeripheralType = "display"
	Gpu        DevicePeripheralType = "gpu"
	Microphone DevicePeripheralType = "microphone"
	Speaker    DevicePeripheralType = "speaker"
)

// Defines values for PostApiV1OnboardingJSONBodyKind.
const (
	OnboardingRequest PostApiV1OnboardingJSONBodyKind = "OnboardingRequest"
)

// ComponentStatus defines model for ComponentStatus.
type ComponentStatus struct {
	Error *struct {
		Code    *string `json:"code,omitempty"`
		Message *string `json:"message,omitempty"`
	} `json:"error,omitempty"`
	Name  string               `json:"name"`
	State ComponentStatusState `json:"state"`
}

// ComponentStatusState defines model for ComponentStatus.State.
type ComponentStatusState string

// DeploymentBundleRef Describes a single archive containing all ApplicationDeployment documents. If there are zero deployments (deployments array is empty) the property MUST be present with the value null (it MUST NOT be omitted).
type DeploymentBundleRef struct {
	// Digest The digest of the bundle archive. MUST equal the digest computed over the exact sequence of bytes (per Exact Bytes Rule) in the bundle endpoint's HTTP 200 OK response body.
	Digest *string `json:"digest,omitempty"`

	// MediaType MUST be application/vnd.margo.bundle.v1+tar+gzip; a gzip-compressed tar whose root contains one or more ApplicationDeployment YAML files. If there are zero deployments then bundle MUST be null (an empty archive MUST NOT be served). The archive MUST contain exactly the set of YAML files referenced by deployments.
	MediaType *string `json:"mediaType,omitempty"`

	// SizeBytes Unsigned 64-bit advisory estimate of the decoded payload length in bytes for the bundle archive. Provided for bandwidth estimation and update planning. MUST NOT be used for integrity; digest verification remains mandatory.
	SizeBytes *float32 `json:"sizeBytes,omitempty"`

	// Url Content-addressable retrieval endpoint of the form /api/v1/clients/{clientId}/bundles/{digest} where {digest} equals bundle.digest.
	Url *string `json:"url,omitempty"`
}

// DeploymentManifestRef Reference to a deployment manifest with content addressing and integrity verification.
type DeploymentManifestRef struct {
	// DeploymentId The unique UUID from the ApplicationDeployment's metadata.annotations.id.
	DeploymentId string `json:"deploymentId"`

	// Digest The digest of the individual ApplicationDeployment YAML file. MUST equal the digest computed over the exact sequence of bytes (per Exact Bytes Rule) in that deployment endpoint's HTTP 200 OK response body.
	Digest string `json:"digest"`

	// SizeBytes Unsigned 64-bit advisory estimate of the decoded payload length in bytes for the deployment YAML. Provided for planning or progress display. MUST NOT be used for integrity; digest verification remains mandatory.
	SizeBytes *float32 `json:"sizeBytes,omitempty"`

	// Url Content-addressable endpoint of the form /api/v1/clients/{clientId}/deployments/{deploymentId}/{digest}. The {digest} MUST equal deployments[].digest; the referenced resource is immutable
	Url string `json:"url"`
}

// DeploymentStatusManifest defines model for DeploymentStatusManifest.
type DeploymentStatusManifest struct {
	ApiVersion   string                       `json:"apiVersion"`
	Components   []ComponentStatus            `json:"components"`
	DeploymentId string                       `json:"deploymentId"`
	Kind         DeploymentStatusManifestKind `json:"kind"`
	Status       struct {
		Error *struct {
			Code    *string `json:"code,omitempty"`
			Message *string `json:"message,omitempty"`
		} `json:"error,omitempty"`
		State DeploymentStatusManifestStatusState `json:"state"`
	} `json:"status"`
}

// DeploymentStatusManifestKind defines model for DeploymentStatusManifest.Kind.
type DeploymentStatusManifestKind string

// DeploymentStatusManifestStatusState defines model for DeploymentStatusManifest.Status.State.
type DeploymentStatusManifestStatusState string

// DeviceCapabilitiesManifest defines model for DeviceCapabilitiesManifest.
type DeviceCapabilitiesManifest struct {
	ApiVersion string                         `json:"apiVersion"`
	Kind       DeviceCapabilitiesManifestKind `json:"kind"`
	Properties struct {
		Id          string `json:"id"`
		ModelNumber string `json:"modelNumber"`
		Resources   struct {
			Cpu struct {
				Architecture *DeviceCapabilitiesManifestPropertiesResourcesCpuArchitecture `json:"architecture,omitempty"`
				Cores        float32                                                       `json:"cores"`
			} `json:"cpu"`
			Interfaces  []DeviceCommunicationInterface `json:"interfaces"`
			Memory      string                         `json:"memory"`
			Peripherals []DevicePeripheral             `json:"peripherals"`
			Storage     string                         `json:"storage"`
		} `json:"resources"`
		Roles        []DeviceCapabilitiesManifestPropertiesRoles `json:"roles"`
		SerialNumber string                                      `json:"serialNumber"`
		Vendor       string                                      `json:"vendor"`
	} `json:"properties"`
}

// DeviceCapabilitiesManifestKind defines model for DeviceCapabilitiesManifest.Kind.
type DeviceCapabilitiesManifestKind string

// DeviceCapabilitiesManifestPropertiesResourcesCpuArchitecture defines model for DeviceCapabilitiesManifest.Properties.Resources.Cpu.Architecture.
type DeviceCapabilitiesManifestPropertiesResourcesCpuArchitecture string

// DeviceCapabilitiesManifestPropertiesRoles defines model for DeviceCapabilitiesManifest.Properties.Roles.
type DeviceCapabilitiesManifestPropertiesRoles string

// DeviceCommunicationInterface defines model for DeviceCommunicationInterface.
type DeviceCommunicationInterface struct {
	Type DeviceCommunicationInterfaceType `json:"type"`
}

// DeviceCommunicationInterfaceType defines model for DeviceCommunicationInterface.Type.
type DeviceCommunicationInterfaceType string

// DevicePeripheral defines model for DevicePeripheral.
type DevicePeripheral struct {
	Manufacturer *string              `json:"manufacturer,omitempty"`
	Model        *string              `json:"model,omitempty"`
	Type         DevicePeripheralType `json:"type"`
}

// DevicePeripheralType defines model for DevicePeripheral.Type.
type DevicePeripheralType string

// ManifestVersion Monotonically increasing unsigned 64-bit integer in the inclusive range [1, 2^64-1]. Prevents rollback attacks. The first manifest MUST use 1.
type ManifestVersion = float32

// UnsignedAppStateManifest defines model for UnsignedAppStateManifest.
type UnsignedAppStateManifest struct {
	// Bundle Describes a single archive containing all ApplicationDeployment documents. If there are zero deployments (deployments array is empty) the property MUST be present with the value null (it MUST NOT be omitted).
	Bundle *DeploymentBundleRef `json:"bundle"`

	// Deployments A list of deployment object references for the device. The reference contains some meta info and reference to the url where the deployment is available.
	Deployments []DeploymentManifestRef `json:"deployments"`

	// ManifestVersion Monotonically increasing unsigned 64-bit integer in the inclusive range [1, 2^64-1]. Prevents rollback attacks. The first manifest MUST use 1.
	ManifestVersion ManifestVersion `json:"manifestVersion"`
}

// GetApiV1ClientsClientIdBundlesDigestParams defines parameters for GetApiV1ClientsClientIdBundlesDigest.
type GetApiV1ClientsClientIdBundlesDigestParams struct {
	// IfNoneMatch Quoted ETag (same as digest) previously returned for this bundle.
	IfNoneMatch *string `json:"If-None-Match,omitempty"`
}

// GetApiV1ClientsClientIdDeploymentsParams defines parameters for GetApiV1ClientsClientIdDeployments.
type GetApiV1ClientsClientIdDeploymentsParams struct {
	// IfNoneMatch ETag value of the last successfully synced manifest. The ETag is returned to the client from the /deployments endpoint, it is the digest of the state manifest.
	IfNoneMatch *string `json:"If-None-Match,omitempty"`

	// Accept Indicates which manifest formats the client supports. Supported values: application/vnd.margo.manifest.v1+json.
	Accept *string `json:"Accept,omitempty"`
}

// GetApiV1ClientsClientIdDeploymentsDeploymentIdDigestParams defines parameters for GetApiV1ClientsClientIdDeploymentsDeploymentIdDigest.
type GetApiV1ClientsClientIdDeploymentsDeploymentIdDigestParams struct {
	// IfNoneMatch Optional ETag for caching. The ETag is returned to the client from the /deployments endpoint, it is the digest of the state manifest.
	IfNoneMatch *string `json:"If-None-Match,omitempty"`

	// AcceptEncoding Indicates supported compression formats (e.g., gzip, br)
	AcceptEncoding *string `json:"Accept-Encoding,omitempty"`
}

// PostApiV1OnboardingJSONBody defines parameters for PostApiV1Onboarding.
type PostApiV1OnboardingJSONBody struct {
	// ApiVersion API version identifier
	ApiVersion string `json:"apiVersion"`

	// Certificate Base64-encoded client certificate
	Certificate string `json:"certificate"`

	// Kind Resource kind
	Kind PostApiV1OnboardingJSONBodyKind `json:"kind"`
}

// PostApiV1OnboardingJSONBodyKind defines parameters for PostApiV1Onboarding.
type PostApiV1OnboardingJSONBodyKind string

// PostApiV1ClientsClientIdCapabilitiesJSONRequestBody defines body for PostApiV1ClientsClientIdCapabilities for application/json ContentType.
type PostApiV1ClientsClientIdCapabilitiesJSONRequestBody = DeviceCapabilitiesManifest

// PutApiV1ClientsClientIdCapabilitiesJSONRequestBody defines body for PutApiV1ClientsClientIdCapabilities for application/json ContentType.
type PutApiV1ClientsClientIdCapabilitiesJSONRequestBody = DeviceCapabilitiesManifest

// PostApiV1ClientsClientIdDeploymentsDeploymentIdStatusJSONRequestBody defines body for PostApiV1ClientsClientIdDeploymentsDeploymentIdStatus for application/json ContentType.
type PostApiV1ClientsClientIdDeploymentsDeploymentIdStatusJSONRequestBody = DeploymentStatusManifest

// PostApiV1OnboardingJSONRequestBody defines body for PostApiV1Onboarding for application/json ContentType.
type PostApiV1OnboardingJSONRequestBody PostApiV1OnboardingJSONBody
