// Package sbi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package sbi

import (
	"encoding/json"
	"fmt"
)

// Defines values for ComponentStatusState.
const (
	ComponentStatusStateFailed     ComponentStatusState = "failed"
	ComponentStatusStateInstalled  ComponentStatusState = "installed"
	ComponentStatusStateInstalling ComponentStatusState = "installing"
	ComponentStatusStatePending    ComponentStatusState = "pending"
	ComponentStatusStateRemoved    ComponentStatusState = "removed"
	ComponentStatusStateRemoving   ComponentStatusState = "removing"
)

// Valid indicates whether the value is a known member of the ComponentStatusState enum.
func (e ComponentStatusState) Valid() bool {
	switch e {
	case ComponentStatusStateFailed:
		return true
	case ComponentStatusStateInstalled:
		return true
	case ComponentStatusStateInstalling:
		return true
	case ComponentStatusStatePending:
		return true
	case ComponentStatusStateRemoved:
		return true
	case ComponentStatusStateRemoving:
		return true
	default:
		return false
	}
}

// Defines values for DeploymentStatusManifestStatusState.
const (
	DeploymentStatusManifestStatusStateFailed     DeploymentStatusManifestStatusState = "failed"
	DeploymentStatusManifestStatusStateInstalled  DeploymentStatusManifestStatusState = "installed"
	DeploymentStatusManifestStatusStateInstalling DeploymentStatusManifestStatusState = "installing"
	DeploymentStatusManifestStatusStatePending    DeploymentStatusManifestStatusState = "pending"
	DeploymentStatusManifestStatusStateRemoved    DeploymentStatusManifestStatusState = "removed"
	DeploymentStatusManifestStatusStateRemoving   DeploymentStatusManifestStatusState = "removing"
)

// Valid indicates whether the value is a known member of the DeploymentStatusManifestStatusState enum.
func (e DeploymentStatusManifestStatusState) Valid() bool {
	switch e {
	case DeploymentStatusManifestStatusStateFailed:
		return true
	case DeploymentStatusManifestStatusStateInstalled:
		return true
	case DeploymentStatusManifestStatusStateInstalling:
		return true
	case DeploymentStatusManifestStatusStatePending:
		return true
	case DeploymentStatusManifestStatusStateRemoved:
		return true
	case DeploymentStatusManifestStatusStateRemoving:
		return true
	default:
		return false
	}
}

// Defines values for DeviceCapabilitiesManifestPropertiesCpusArchitecture.
const (
	Amd64 DeviceCapabilitiesManifestPropertiesCpusArchitecture = "amd64"
	Arm   DeviceCapabilitiesManifestPropertiesCpusArchitecture = "arm"
	Arm64 DeviceCapabilitiesManifestPropertiesCpusArchitecture = "arm64"
)

// Valid indicates whether the value is a known member of the DeviceCapabilitiesManifestPropertiesCpusArchitecture enum.
func (e DeviceCapabilitiesManifestPropertiesCpusArchitecture) Valid() bool {
	switch e {
	case Amd64:
		return true
	case Arm:
		return true
	case Arm64:
		return true
	default:
		return false
	}
}

// Defines values for DeviceCapabilitiesManifestPropertiesSupportedDeploymentTypes.
const (
	DeviceCapabilitiesManifestPropertiesSupportedDeploymentTypesCompose DeviceCapabilitiesManifestPropertiesSupportedDeploymentTypes = "compose"
	DeviceCapabilitiesManifestPropertiesSupportedDeploymentTypesHelm    DeviceCapabilitiesManifestPropertiesSupportedDeploymentTypes = "helm"
)

// Valid indicates whether the value is a known member of the DeviceCapabilitiesManifestPropertiesSupportedDeploymentTypes enum.
func (e DeviceCapabilitiesManifestPropertiesSupportedDeploymentTypes) Valid() bool {
	switch e {
	case DeviceCapabilitiesManifestPropertiesSupportedDeploymentTypesCompose:
		return true
	case DeviceCapabilitiesManifestPropertiesSupportedDeploymentTypesHelm:
		return true
	default:
		return false
	}
}

// Defines values for DeviceCapabilitiesManifestPropertiesSupportedRuntimes.
const (
	Oci DeviceCapabilitiesManifestPropertiesSupportedRuntimes = "oci"
)

// Valid indicates whether the value is a known member of the DeviceCapabilitiesManifestPropertiesSupportedRuntimes enum.
func (e DeviceCapabilitiesManifestPropertiesSupportedRuntimes) Valid() bool {
	switch e {
	case Oci:
		return true
	default:
		return false
	}
}

// Defines values for DeviceCommunicationInterfaceType.
const (
	Bluetooth DeviceCommunicationInterfaceType = "bluetooth"
	Canbus    DeviceCommunicationInterfaceType = "canbus"
	Cellular  DeviceCommunicationInterfaceType = "cellular"
	Ethernet  DeviceCommunicationInterfaceType = "ethernet"
	Rs232     DeviceCommunicationInterfaceType = "rs232"
	Usb       DeviceCommunicationInterfaceType = "usb"
	Wifi      DeviceCommunicationInterfaceType = "wifi"
)

// Valid indicates whether the value is a known member of the DeviceCommunicationInterfaceType enum.
func (e DeviceCommunicationInterfaceType) Valid() bool {
	switch e {
	case Bluetooth:
		return true
	case Canbus:
		return true
	case Cellular:
		return true
	case Ethernet:
		return true
	case Rs232:
		return true
	case Usb:
		return true
	case Wifi:
		return true
	default:
		return false
	}
}

// Defines values for DevicePeripheralType.
const (
	Camera     DevicePeripheralType = "camera"
	Display    DevicePeripheralType = "display"
	Gpu        DevicePeripheralType = "gpu"
	Microphone DevicePeripheralType = "microphone"
	Speaker    DevicePeripheralType = "speaker"
)

// Valid indicates whether the value is a known member of the DevicePeripheralType enum.
func (e DevicePeripheralType) Valid() bool {
	switch e {
	case Camera:
		return true
	case Display:
		return true
	case Gpu:
		return true
	case Microphone:
		return true
	case Speaker:
		return true
	default:
		return false
	}
}

// Defines values for ProblemDetailBackoffStrategy.
const (
	Exponential ProblemDetailBackoffStrategy = "exponential"
	Fixed       ProblemDetailBackoffStrategy = "fixed"
	None        ProblemDetailBackoffStrategy = "none"
)

// Valid indicates whether the value is a known member of the ProblemDetailBackoffStrategy enum.
func (e ProblemDetailBackoffStrategy) Valid() bool {
	switch e {
	case Exponential:
		return true
	case Fixed:
		return true
	case None:
		return true
	default:
		return false
	}
}

// Defines values for AppDeploymentProfileType.
const (
	AppDeploymentProfileTypeCompose AppDeploymentProfileType = "compose"
	AppDeploymentProfileTypeHelm    AppDeploymentProfileType = "helm"
)

// Valid indicates whether the value is a known member of the AppDeploymentProfileType enum.
func (e AppDeploymentProfileType) Valid() bool {
	switch e {
	case AppDeploymentProfileTypeCompose:
		return true
	case AppDeploymentProfileTypeHelm:
		return true
	default:
		return false
	}
}

// ComponentStatus defines model for ComponentStatus.
type ComponentStatus struct {
	Error *struct {
		Code    *string `json:"code,omitempty"`
		Message *string `json:"message,omitempty"`
		Source  *string `json:"source,omitempty"`
	} `json:"error,omitempty"`
	Name  string               `json:"name"`
	State ComponentStatusState `json:"state"`
}

// ComponentStatusState defines model for ComponentStatus.State.
type ComponentStatusState string

// DeploymentBundleRef Describes a single archive containing all ApplicationDeployment documents. If there are zero deployments (deployments array is empty) the property MUST be present with the value null (it MUST NOT be omitted).
type DeploymentBundleRef struct {
	// Digest The digest of the bundle archive. MUST equal the digest computed over the exact sequence of bytes (per Exact Bytes Rule) in the bundle endpoint's HTTP 200 OK response body.
	Digest *string `json:"digest,omitempty"`

	// MediaType MUST be application/vnd.margo.bundle.v1+tar+gzip; a gzip-compressed tar whose root contains one or more ApplicationDeployment YAML files. If there are zero deployments then bundle MUST be null (an empty archive MUST NOT be served). The archive MUST contain exactly the set of YAML files referenced by deployments.
	MediaType *string `json:"mediaType,omitempty"`

	// SizeBytes Unsigned 64-bit advisory estimate of the decoded payload length in bytes for the bundle archive. Provided for bandwidth estimation and update planning. MUST NOT be used for integrity; digest verification remains mandatory.
	SizeBytes *float32 `json:"sizeBytes,omitempty"`

	// Url Content-addressable retrieval endpoint of the form /api/v1/bundles/{digest} where {digest} equals bundle.digest.
	Url *string `json:"url,omitempty"`
}

// DeploymentManifestRef Reference to a deployment manifest with content addressing and integrity verification.
type DeploymentManifestRef struct {
	// DeploymentId Unique identifier for the application deployment.
	DeploymentId string `json:"deploymentId"`

	// Digest The digest of the individual ApplicationDeployment YAML file. MUST equal the digest computed over the exact sequence of bytes (per Exact Bytes Rule) in that deployment endpoint's HTTP 200 OK response body.
	Digest string `json:"digest"`

	// SizeBytes Unsigned 64-bit advisory estimate of the decoded payload length in bytes for the deployment YAML. Provided for planning or progress display. MUST NOT be used for integrity; digest verification remains mandatory.
	SizeBytes *float32 `json:"sizeBytes,omitempty"`

	// Url Content-addressable endpoint of the form /api/v1/deployments/{deploymentId}/{digest}. The {digest} MUST equal deployments[].digest; the referenced resource is immutable
	Url string `json:"url"`
}

// DeploymentStatusManifest defines model for DeploymentStatusManifest.
type DeploymentStatusManifest struct {
	Components   []ComponentStatus `json:"components"`
	DeploymentId string            `json:"deploymentId"`
	DeviceId     *DeviceId         `json:"deviceId,omitempty"`
	Status       struct {
		Error *struct {
			Code    *string `json:"code,omitempty"`
			Message *string `json:"message,omitempty"`
			Source  *string `json:"source,omitempty"`
		} `json:"error,omitempty"`
		State DeploymentStatusManifestStatusState `json:"state"`
	} `json:"status"`
}

// DeploymentStatusManifestStatusState defines model for DeploymentStatusManifest.Status.State.
type DeploymentStatusManifestStatusState string

// DeviceCapabilitiesManifest defines model for DeviceCapabilitiesManifest.
type DeviceCapabilitiesManifest struct {
	Properties struct {
		Cpus *[]struct {
			Architecture *DeviceCapabilitiesManifestPropertiesCpusArchitecture `json:"architecture,omitempty"`
			Cores        float32                                               `json:"cores"`
		} `json:"cpus,omitempty"`
		Id                       DeviceId                                                        `json:"id"`
		Interfaces               *[]DeviceCommunicationInterface                                 `json:"interfaces,omitempty"`
		Memory                   *string                                                         `json:"memory,omitempty"`
		ModelNumber              string                                                          `json:"modelNumber"`
		OtelCollector            *bool                                                           `json:"otelCollector,omitempty"`
		Peripherals              *[]DevicePeripheral                                             `json:"peripherals,omitempty"`
		SerialNumber             string                                                          `json:"serialNumber"`
		Storage                  *string                                                         `json:"storage,omitempty"`
		SupportedDeploymentTypes *[]DeviceCapabilitiesManifestPropertiesSupportedDeploymentTypes `json:"supportedDeploymentTypes,omitempty"`
		SupportedRuntimes        *[]DeviceCapabilitiesManifestPropertiesSupportedRuntimes        `json:"supportedRuntimes,omitempty"`
		Vendor                   string                                                          `json:"vendor"`
	} `json:"properties"`
}

// DeviceCapabilitiesManifestPropertiesCpusArchitecture defines model for DeviceCapabilitiesManifest.Properties.Cpus.Architecture.
type DeviceCapabilitiesManifestPropertiesCpusArchitecture string

// DeviceCapabilitiesManifestPropertiesSupportedDeploymentTypes defines model for DeviceCapabilitiesManifest.Properties.SupportedDeploymentTypes.
type DeviceCapabilitiesManifestPropertiesSupportedDeploymentTypes string

// DeviceCapabilitiesManifestPropertiesSupportedRuntimes defines model for DeviceCapabilitiesManifest.Properties.SupportedRuntimes.
type DeviceCapabilitiesManifestPropertiesSupportedRuntimes string

// DeviceCommunicationInterface defines model for DeviceCommunicationInterface.
type DeviceCommunicationInterface struct {
	Type DeviceCommunicationInterfaceType `json:"type"`
}

// DeviceCommunicationInterfaceType defines model for DeviceCommunicationInterface.Type.
type DeviceCommunicationInterfaceType string

// DeviceId defines model for DeviceId.
type DeviceId = string

// DeviceIdWithAsterisk defines model for DeviceId_with_asterisk.
type DeviceIdWithAsterisk = string

// DevicePeripheral defines model for DevicePeripheral.
type DevicePeripheral struct {
	Manufacturer *string              `json:"manufacturer,omitempty"`
	Model        *string              `json:"model,omitempty"`
	Type         DevicePeripheralType `json:"type"`
}

// DevicePeripheralType defines model for DevicePeripheral.Type.
type DevicePeripheralType string

// ManifestVersion Monotonically increasing unsigned 64-bit integer in the inclusive range [1, 2^64-1]. Prevents rollback attacks. The first manifest MUST use 1.
type ManifestVersion = float32

// ProblemDetail RFC 9457 Problem Details for HTTP APIs. Returned with Content-Type: application/problem+json. See https://www.rfc-editor.org/rfc/rfc9457. Extension members (RFC 9457 §3.2) are permitted via additionalProperties. Vendors MAY add custom fields alongside standard margo fields. Vendor-specific problem types MUST use their own URI namespace. The https://docs.margo.org/specification/problem-types namespace is reserved for Margo.
type ProblemDetail struct {
	// BackoffStrategy Recommended backoff strategy for retrying. none: do not retry. fixed: retry after retryAfterSeconds. exponential: use exponential backoff starting at retryAfterSeconds.
	BackoffStrategy *ProblemDetailBackoffStrategy `json:"backoffStrategy,omitempty"`

	// Detail Human-readable explanation specific to this occurrence of the problem.
	Detail *string `json:"detail,omitempty"`

	// Errors Optional list of field-level validation errors. SHOULD be present on 422 Unprocessable Entity responses.
	Errors *[]struct {
		// Field Field path that caused the validation error.
		Field *string `json:"field,omitempty"`

		// Message Human-readable validation error message.
		Message *string `json:"message,omitempty"`
	} `json:"errors,omitempty"`

	// Instance URI reference identifying the specific occurrence of the problem.
	Instance *string `json:"instance,omitempty"`

	// RetryAfterSeconds Advisory retry delay in seconds. The authoritative value is the Retry-After response header when present. This field is advisory only.
	RetryAfterSeconds *int `json:"retryAfterSeconds,omitempty"`

	// Retryable Whether the client MAY retry the request. If true, client SHOULD respect the Retry-After response header when present.
	Retryable *bool `json:"retryable,omitempty"`

	// Status HTTP status code.
	Status int `json:"status"`

	// Title Short human-readable summary of the problem type.
	Title string `json:"title"`

	// Type URI reference identifying the problem type. Implementations MUST use the registered Margo type URI for any error condition defined in the Margo specification. For error conditions not defined in this specification, implementations MAY define their own type URIs under their own namespace. Clients MUST use this field for programmatic error handling, NOT the status code or title. Clients encountering an unknown type URI SHOULD fall back to title, detail, and status for display and handling.
	Type                 string                 `json:"type"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// ProblemDetailBackoffStrategy Recommended backoff strategy for retrying. none: do not retry. fixed: retry after retryAfterSeconds. exponential: use exponential backoff starting at retryAfterSeconds.
type ProblemDetailBackoffStrategy string

// UnsignedAppStateManifest defines model for UnsignedAppStateManifest.
type UnsignedAppStateManifest struct {
	// Bundle Describes a single archive containing all ApplicationDeployment documents. If there are zero deployments (deployments array is empty) the property MUST be present with the value null (it MUST NOT be omitted).
	Bundle *DeploymentBundleRef `json:"bundle"`

	// Deployments A list of deployment object references for the device. The reference contains some meta info and reference to the url where the deployment is available.
	Deployments []DeploymentManifestRef `json:"deployments"`

	// ManifestVersion Monotonically increasing unsigned 64-bit integer in the inclusive range [1, 2^64-1]. Prevents rollback attacks. The first manifest MUST use 1.
	ManifestVersion ManifestVersion `json:"manifestVersion"`
}

// AppDeploymentManifest Application Deployment manifest
type AppDeploymentManifest struct {
	// Id Unique identifier for the application deployment
	Id       *string               `json:"id,omitempty"`
	Metadata AppDeploymentMetadata `json:"metadata"`

	// Spec Application Deployment specification
	Spec AppDeploymentSpec `json:"spec"`
}

// AppDeploymentMetadata defines model for appDeploymentMetadata.
type AppDeploymentMetadata struct {
	// DeviceId Device ID of the target device for the deployment
	DeviceId DeviceIdWithAsterisk `json:"deviceId"`

	// Labels Labels for the resource
	Labels *map[string]string `json:"labels,omitempty"`

	// Name Name of the resource
	Name string `json:"name"`

	// Namespace Namespace of the resource
	Namespace string `json:"namespace"`
}

// AppDeploymentParams Application Parameters
type AppDeploymentParams map[string]AppParameterValue

// AppDeploymentProfile Application Deployment Profile
type AppDeploymentProfile struct {
	// Components Components of the deployment profile
	Components []ApplicationDeploymentProfileComponent `json:"components"`

	// Type Type of deployment profile
	Type AppDeploymentProfileType `json:"type"`
}

// AppDeploymentProfileType Type of deployment profile
type AppDeploymentProfileType string

// AppDeploymentSpec Application Deployment specification
type AppDeploymentSpec struct {
	// ApplicationId An identifier for the application. The id is used to help create unique identifiers where required, such as namespaces. The id must be lower case letters and numbers and MAY contain dashes. Uppercase letters, underscores and periods MUST NOT be used. The id MUST NOT be more than 200 characters. The applicationId MUST match the associated application description's top-level "id" attribute.
	ApplicationId string `json:"applicationId"`

	// DeploymentProfile Deployment profile
	DeploymentProfile AppDeploymentProfile `json:"deploymentProfile"`

	// Parameters Parameters for the deployment
	Parameters *AppDeploymentParams `json:"parameters,omitempty"`
}

// AppParameterTarget Application Parameter Target
type AppParameterTarget struct {
	// Components Components of the parameter
	Components []string `json:"components"`

	// Pointer Pointer to the parameter
	Pointer string `json:"pointer"`
}

// AppParameterValue Application Parameter Value
type AppParameterValue struct {
	// Targets Targets of the parameter
	Targets []AppParameterTarget `json:"targets"`

	// Value Value of the parameter
	Value interface{} `json:"value"`
}

// ApplicationDeploymentProfileComponent A component within a deployment profile. Uses the unified ComponentProperties shape — both Helm and Compose components share the same OCI coordinate structure.
type ApplicationDeploymentProfileComponent struct {
	// Name Name of the component
	Name       string `json:"name"`
	Properties struct {
		// Repository OCI repository URI for the component package (e.g., oci://registry.example.com/org/component-name). MUST be a valid OCI reference using the oci:// scheme.
		Repository string `json:"repository"`

		// Revision OCI tag identifying the component version. MUST be a valid SemVer 2.0 string without leading v. Build metadata uses _ as separator instead of +.
		Revision string `json:"revision"`

		// Timeout Maximum time to wait for component installation to complete. Format is ##m##s (e.g., 5m0s, 8m30s).
		Timeout *string `json:"timeout,omitempty"`

		// Wait Whether to wait for component installation to complete before proceeding. Default is true. Only applies when multiple components are provided.
		Wait *bool `json:"wait,omitempty"`
	} `json:"properties"`
}

// GetApiV1BundlesDigestParams defines parameters for GetApiV1BundlesDigest.
type GetApiV1BundlesDigestParams struct {
	// IfNoneMatch Quoted ETag (same as digest) previously returned for this bundle.
	IfNoneMatch *string `json:"If-None-Match,omitempty"`
}

// GetApiV1DeploymentsParams defines parameters for GetApiV1Deployments.
type GetApiV1DeploymentsParams struct {
	// IfNoneMatch ETag value of the last successfully synced manifest. The ETag is returned to the client from the /deployments endpoint, it is the digest of the state manifest.
	IfNoneMatch *string `json:"If-None-Match,omitempty"`

	// Accept Indicates which manifest formats the client supports. Supported values: application/vnd.margo.manifest.v1+json.
	Accept *string `json:"Accept,omitempty"`
}

// GetApiV1DeploymentsDeploymentIdDigestParams defines parameters for GetApiV1DeploymentsDeploymentIdDigest.
type GetApiV1DeploymentsDeploymentIdDigestParams struct {
	// IfNoneMatch Optional ETag for caching. The ETag is returned to the client from the /deployments endpoint, it is the digest of the state manifest.
	IfNoneMatch *string `json:"If-None-Match,omitempty"`

	// AcceptEncoding Indicates supported compression formats (e.g., gzip, br)
	AcceptEncoding *string `json:"Accept-Encoding,omitempty"`
}

// PutApiV1CapabilitiesDeviceIdJSONRequestBody defines body for PutApiV1CapabilitiesDeviceId for application/json ContentType.
type PutApiV1CapabilitiesDeviceIdJSONRequestBody = DeviceCapabilitiesManifest

// PostApiV1DeploymentsDeploymentIdStatusJSONRequestBody defines body for PostApiV1DeploymentsDeploymentIdStatus for application/json ContentType.
type PostApiV1DeploymentsDeploymentIdStatusJSONRequestBody = DeploymentStatusManifest

// Getter for additional properties for ProblemDetail. Returns the specified
// element and whether it was found
func (a ProblemDetail) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for ProblemDetail
func (a *ProblemDetail) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for ProblemDetail to handle AdditionalProperties
func (a *ProblemDetail) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["backoffStrategy"]; found {
		err = json.Unmarshal(raw, &a.BackoffStrategy)
		if err != nil {
			return fmt.Errorf("error reading 'backoffStrategy': %w", err)
		}
		delete(object, "backoffStrategy")
	}

	if raw, found := object["detail"]; found {
		err = json.Unmarshal(raw, &a.Detail)
		if err != nil {
			return fmt.Errorf("error reading 'detail': %w", err)
		}
		delete(object, "detail")
	}

	if raw, found := object["errors"]; found {
		err = json.Unmarshal(raw, &a.Errors)
		if err != nil {
			return fmt.Errorf("error reading 'errors': %w", err)
		}
		delete(object, "errors")
	}

	if raw, found := object["instance"]; found {
		err = json.Unmarshal(raw, &a.Instance)
		if err != nil {
			return fmt.Errorf("error reading 'instance': %w", err)
		}
		delete(object, "instance")
	}

	if raw, found := object["retryAfterSeconds"]; found {
		err = json.Unmarshal(raw, &a.RetryAfterSeconds)
		if err != nil {
			return fmt.Errorf("error reading 'retryAfterSeconds': %w", err)
		}
		delete(object, "retryAfterSeconds")
	}

	if raw, found := object["retryable"]; found {
		err = json.Unmarshal(raw, &a.Retryable)
		if err != nil {
			return fmt.Errorf("error reading 'retryable': %w", err)
		}
		delete(object, "retryable")
	}

	if raw, found := object["status"]; found {
		err = json.Unmarshal(raw, &a.Status)
		if err != nil {
			return fmt.Errorf("error reading 'status': %w", err)
		}
		delete(object, "status")
	}

	if raw, found := object["title"]; found {
		err = json.Unmarshal(raw, &a.Title)
		if err != nil {
			return fmt.Errorf("error reading 'title': %w", err)
		}
		delete(object, "title")
	}

	if raw, found := object["type"]; found {
		err = json.Unmarshal(raw, &a.Type)
		if err != nil {
			return fmt.Errorf("error reading 'type': %w", err)
		}
		delete(object, "type")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for ProblemDetail to handle AdditionalProperties
func (a ProblemDetail) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.BackoffStrategy != nil {
		object["backoffStrategy"], err = json.Marshal(a.BackoffStrategy)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'backoffStrategy': %w", err)
		}
	}

	if a.Detail != nil {
		object["detail"], err = json.Marshal(a.Detail)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'detail': %w", err)
		}
	}

	if a.Errors != nil {
		object["errors"], err = json.Marshal(a.Errors)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'errors': %w", err)
		}
	}

	if a.Instance != nil {
		object["instance"], err = json.Marshal(a.Instance)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'instance': %w", err)
		}
	}

	if a.RetryAfterSeconds != nil {
		object["retryAfterSeconds"], err = json.Marshal(a.RetryAfterSeconds)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'retryAfterSeconds': %w", err)
		}
	}

	if a.Retryable != nil {
		object["retryable"], err = json.Marshal(a.Retryable)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'retryable': %w", err)
		}
	}

	object["status"], err = json.Marshal(a.Status)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'status': %w", err)
	}

	object["title"], err = json.Marshal(a.Title)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'title': %w", err)
	}

	object["type"], err = json.Marshal(a.Type)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'type': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}
