// Package sbi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package sbi

import (
	"encoding/json"

	"github.com/oapi-codegen/runtime"
)

// Defines values for ComponentStatusState.
const (
	ComponentStatusStateFailed     ComponentStatusState = "failed"
	ComponentStatusStateInstalled  ComponentStatusState = "installed"
	ComponentStatusStateInstalling ComponentStatusState = "installing"
	ComponentStatusStatePending    ComponentStatusState = "pending"
	ComponentStatusStateRemoved    ComponentStatusState = "removed"
	ComponentStatusStateRemoving   ComponentStatusState = "removing"
)

// Valid indicates whether the value is a known member of the ComponentStatusState enum.
func (e ComponentStatusState) Valid() bool {
	switch e {
	case ComponentStatusStateFailed:
		return true
	case ComponentStatusStateInstalled:
		return true
	case ComponentStatusStateInstalling:
		return true
	case ComponentStatusStatePending:
		return true
	case ComponentStatusStateRemoved:
		return true
	case ComponentStatusStateRemoving:
		return true
	default:
		return false
	}
}

// Defines values for DeploymentCpuRequirementArchitectures.
const (
	DeploymentCpuRequirementArchitecturesAmd64   DeploymentCpuRequirementArchitectures = "amd64"
	DeploymentCpuRequirementArchitecturesArm     DeploymentCpuRequirementArchitectures = "arm"
	DeploymentCpuRequirementArchitecturesArm64   DeploymentCpuRequirementArchitectures = "arm64"
	DeploymentCpuRequirementArchitecturesOther   DeploymentCpuRequirementArchitectures = "other"
	DeploymentCpuRequirementArchitecturesRiscv64 DeploymentCpuRequirementArchitectures = "riscv64"
)

// Valid indicates whether the value is a known member of the DeploymentCpuRequirementArchitectures enum.
func (e DeploymentCpuRequirementArchitectures) Valid() bool {
	switch e {
	case DeploymentCpuRequirementArchitecturesAmd64:
		return true
	case DeploymentCpuRequirementArchitecturesArm:
		return true
	case DeploymentCpuRequirementArchitecturesArm64:
		return true
	case DeploymentCpuRequirementArchitecturesOther:
		return true
	case DeploymentCpuRequirementArchitecturesRiscv64:
		return true
	default:
		return false
	}
}

// Defines values for DeploymentStatusManifestKind.
const (
	DeploymentStatusManifestKindDeploymentStatusManifest DeploymentStatusManifestKind = "DeploymentStatusManifest"
)

// Valid indicates whether the value is a known member of the DeploymentStatusManifestKind enum.
func (e DeploymentStatusManifestKind) Valid() bool {
	switch e {
	case DeploymentStatusManifestKindDeploymentStatusManifest:
		return true
	default:
		return false
	}
}

// Defines values for DeploymentStatusManifestStatusState.
const (
	DeploymentStatusManifestStatusStateFailed     DeploymentStatusManifestStatusState = "failed"
	DeploymentStatusManifestStatusStateInstalled  DeploymentStatusManifestStatusState = "installed"
	DeploymentStatusManifestStatusStateInstalling DeploymentStatusManifestStatusState = "installing"
	DeploymentStatusManifestStatusStatePending    DeploymentStatusManifestStatusState = "pending"
	DeploymentStatusManifestStatusStateRemoved    DeploymentStatusManifestStatusState = "removed"
	DeploymentStatusManifestStatusStateRemoving   DeploymentStatusManifestStatusState = "removing"
)

// Valid indicates whether the value is a known member of the DeploymentStatusManifestStatusState enum.
func (e DeploymentStatusManifestStatusState) Valid() bool {
	switch e {
	case DeploymentStatusManifestStatusStateFailed:
		return true
	case DeploymentStatusManifestStatusStateInstalled:
		return true
	case DeploymentStatusManifestStatusStateInstalling:
		return true
	case DeploymentStatusManifestStatusStatePending:
		return true
	case DeploymentStatusManifestStatusStateRemoved:
		return true
	case DeploymentStatusManifestStatusStateRemoving:
		return true
	default:
		return false
	}
}

// Defines values for DeviceCapabilitiesManifestKind.
const (
	DeviceCapabilitiesManifestKindDeviceCapabilitiesManifest DeviceCapabilitiesManifestKind = "DeviceCapabilitiesManifest"
)

// Valid indicates whether the value is a known member of the DeviceCapabilitiesManifestKind enum.
func (e DeviceCapabilitiesManifestKind) Valid() bool {
	switch e {
	case DeviceCapabilitiesManifestKindDeviceCapabilitiesManifest:
		return true
	default:
		return false
	}
}

// Defines values for DeviceCapabilitiesManifestPropertiesCpusArchitecture.
const (
	DeviceCapabilitiesManifestPropertiesCpusArchitectureAmd64 DeviceCapabilitiesManifestPropertiesCpusArchitecture = "amd64"
	DeviceCapabilitiesManifestPropertiesCpusArchitectureArm   DeviceCapabilitiesManifestPropertiesCpusArchitecture = "arm"
	DeviceCapabilitiesManifestPropertiesCpusArchitectureArm64 DeviceCapabilitiesManifestPropertiesCpusArchitecture = "arm64"
)

// Valid indicates whether the value is a known member of the DeviceCapabilitiesManifestPropertiesCpusArchitecture enum.
func (e DeviceCapabilitiesManifestPropertiesCpusArchitecture) Valid() bool {
	switch e {
	case DeviceCapabilitiesManifestPropertiesCpusArchitectureAmd64:
		return true
	case DeviceCapabilitiesManifestPropertiesCpusArchitectureArm:
		return true
	case DeviceCapabilitiesManifestPropertiesCpusArchitectureArm64:
		return true
	default:
		return false
	}
}

// Defines values for DeviceCapabilitiesManifestPropertiesSupportedDeploymentTypes.
const (
	DeviceCapabilitiesManifestPropertiesSupportedDeploymentTypesCompose DeviceCapabilitiesManifestPropertiesSupportedDeploymentTypes = "compose"
	DeviceCapabilitiesManifestPropertiesSupportedDeploymentTypesCustom  DeviceCapabilitiesManifestPropertiesSupportedDeploymentTypes = "custom"
	DeviceCapabilitiesManifestPropertiesSupportedDeploymentTypesHelm    DeviceCapabilitiesManifestPropertiesSupportedDeploymentTypes = "helm"
)

// Valid indicates whether the value is a known member of the DeviceCapabilitiesManifestPropertiesSupportedDeploymentTypes enum.
func (e DeviceCapabilitiesManifestPropertiesSupportedDeploymentTypes) Valid() bool {
	switch e {
	case DeviceCapabilitiesManifestPropertiesSupportedDeploymentTypesCompose:
		return true
	case DeviceCapabilitiesManifestPropertiesSupportedDeploymentTypesCustom:
		return true
	case DeviceCapabilitiesManifestPropertiesSupportedDeploymentTypesHelm:
		return true
	default:
		return false
	}
}

// Defines values for DeviceCapabilitiesManifestPropertiesSupportedRuntimes.
const (
	DeviceCapabilitiesManifestPropertiesSupportedRuntimesCustom DeviceCapabilitiesManifestPropertiesSupportedRuntimes = "custom"
	DeviceCapabilitiesManifestPropertiesSupportedRuntimesOci    DeviceCapabilitiesManifestPropertiesSupportedRuntimes = "oci"
)

// Valid indicates whether the value is a known member of the DeviceCapabilitiesManifestPropertiesSupportedRuntimes enum.
func (e DeviceCapabilitiesManifestPropertiesSupportedRuntimes) Valid() bool {
	switch e {
	case DeviceCapabilitiesManifestPropertiesSupportedRuntimesCustom:
		return true
	case DeviceCapabilitiesManifestPropertiesSupportedRuntimesOci:
		return true
	default:
		return false
	}
}

// Defines values for DeviceCommunicationInterfaceType.
const (
	Bluetooth DeviceCommunicationInterfaceType = "bluetooth"
	Canbus    DeviceCommunicationInterfaceType = "canbus"
	Cellular  DeviceCommunicationInterfaceType = "cellular"
	Ethernet  DeviceCommunicationInterfaceType = "ethernet"
	Rs232     DeviceCommunicationInterfaceType = "rs232"
	Usb       DeviceCommunicationInterfaceType = "usb"
	Wifi      DeviceCommunicationInterfaceType = "wifi"
)

// Valid indicates whether the value is a known member of the DeviceCommunicationInterfaceType enum.
func (e DeviceCommunicationInterfaceType) Valid() bool {
	switch e {
	case Bluetooth:
		return true
	case Canbus:
		return true
	case Cellular:
		return true
	case Ethernet:
		return true
	case Rs232:
		return true
	case Usb:
		return true
	case Wifi:
		return true
	default:
		return false
	}
}

// Defines values for DevicePeripheralType.
const (
	Camera     DevicePeripheralType = "camera"
	Display    DevicePeripheralType = "display"
	Gpu        DevicePeripheralType = "gpu"
	Microphone DevicePeripheralType = "microphone"
	Speaker    DevicePeripheralType = "speaker"
)

// Valid indicates whether the value is a known member of the DevicePeripheralType enum.
func (e DevicePeripheralType) Valid() bool {
	switch e {
	case Camera:
		return true
	case Display:
		return true
	case Gpu:
		return true
	case Microphone:
		return true
	case Speaker:
		return true
	default:
		return false
	}
}

// Defines values for MatchExpressionOperator.
const (
	ContainsAll  MatchExpressionOperator = "ContainsAll"
	ContainsAny  MatchExpressionOperator = "ContainsAny"
	DoesNotExist MatchExpressionOperator = "DoesNotExist"
	Exists       MatchExpressionOperator = "Exists"
	Gt           MatchExpressionOperator = "Gt"
	In           MatchExpressionOperator = "In"
	Lt           MatchExpressionOperator = "Lt"
	NotIn        MatchExpressionOperator = "NotIn"
)

// Valid indicates whether the value is a known member of the MatchExpressionOperator enum.
func (e MatchExpressionOperator) Valid() bool {
	switch e {
	case ContainsAll:
		return true
	case ContainsAny:
		return true
	case DoesNotExist:
		return true
	case Exists:
		return true
	case Gt:
		return true
	case In:
		return true
	case Lt:
		return true
	case NotIn:
		return true
	default:
		return false
	}
}

// Defines values for AppDeploymentProfileType.
const (
	AppDeploymentProfileTypeCompose AppDeploymentProfileType = "compose"
	AppDeploymentProfileTypeHelm    AppDeploymentProfileType = "helm"
)

// Valid indicates whether the value is a known member of the AppDeploymentProfileType enum.
func (e AppDeploymentProfileType) Valid() bool {
	switch e {
	case AppDeploymentProfileTypeCompose:
		return true
	case AppDeploymentProfileTypeHelm:
		return true
	default:
		return false
	}
}

// Defines values for PostApiV1OnboardingJSONBodyKind.
const (
	OnboardingRequest PostApiV1OnboardingJSONBodyKind = "OnboardingRequest"
)

// Valid indicates whether the value is a known member of the PostApiV1OnboardingJSONBodyKind enum.
func (e PostApiV1OnboardingJSONBodyKind) Valid() bool {
	switch e {
	case OnboardingRequest:
		return true
	default:
		return false
	}
}

// CapacityRequirements Minimum device capacity required by the deployment profile.
type CapacityRequirements struct {
	// Cpu CPU element specifying the CPU requirements for the deployment.
	Cpu *DeploymentCpuRequirement `json:"cpu,omitempty"`

	// Memory The minimum amount of memory required. The value is given in binary units (`Ki` = Kibibytes, `Mi` = Mebibytes, `Gi` = Gibibytes).
	Memory *string `json:"memory,omitempty"`

	// Storage The minimum amount of storage required. The value is given in binary units (`Ki` = Kibibytes, `Mi` = Mebibytes, `Gi` = Gibibytes, `Ti` = Tebibytes, `Pi` = Pebibytes, `Ei` = Exbibytes).
	Storage *string `json:"storage,omitempty"`
}

// ComponentStatus defines model for ComponentStatus.
type ComponentStatus struct {
	Error *struct {
		Code    *string `json:"code,omitempty"`
		Message *string `json:"message,omitempty"`
		Source  *string `json:"source,omitempty"`
	} `json:"error,omitempty"`
	Name  string               `json:"name"`
	State ComponentStatusState `json:"state"`
}

// ComponentStatusState defines model for ComponentStatus.State.
type ComponentStatusState string

// DeploymentBundleRef Describes a single archive containing all ApplicationDeployment documents. If there are zero deployments (deployments array is empty) the property MUST be present with the value null (it MUST NOT be omitted).
type DeploymentBundleRef struct {
	// Digest The digest of the bundle archive. MUST equal the digest computed over the exact sequence of bytes (per Exact Bytes Rule) in the bundle endpoint's HTTP 200 OK response body.
	Digest *string `json:"digest,omitempty"`

	// MediaType MUST be application/vnd.margo.bundle.v1+tar+gzip; a gzip-compressed tar whose root contains one or more ApplicationDeployment YAML files. If there are zero deployments then bundle MUST be null (an empty archive MUST NOT be served). The archive MUST contain exactly the set of YAML files referenced by deployments.
	MediaType *string `json:"mediaType,omitempty"`

	// SizeBytes Unsigned 64-bit advisory estimate of the decoded payload length in bytes for the bundle archive. Provided for bandwidth estimation and update planning. MUST NOT be used for integrity; digest verification remains mandatory.
	SizeBytes *float32 `json:"sizeBytes,omitempty"`

	// Url Content-addressable retrieval endpoint of the form /api/v1/clients/{clientId}/bundles/{digest} where {digest} equals bundle.digest.
	Url *string `json:"url,omitempty"`
}

// DeploymentCpuRequirement CPU element specifying the CPU requirements for the deployment.
type DeploymentCpuRequirement struct {
	// Architectures The CPU architectures supported by the deployment.
	Architectures *[]DeploymentCpuRequirementArchitectures `json:"architectures,omitempty"`

	// Cores The required amount of CPU cores. Specified as decimal units of CPU cores (e.g., `0.5` is half a core).
	Cores float32 `json:"cores"`
}

// DeploymentCpuRequirementArchitectures defines model for DeploymentCpuRequirement.Architectures.
type DeploymentCpuRequirementArchitectures string

// DeploymentManifestRef Reference to a deployment manifest with content addressing and integrity verification.
type DeploymentManifestRef struct {
	// DeploymentId Unique identifier for the application deployment.
	DeploymentId string `json:"deploymentId"`

	// Digest The digest of the individual ApplicationDeployment YAML file. MUST equal the digest computed over the exact sequence of bytes (per Exact Bytes Rule) in that deployment endpoint's HTTP 200 OK response body.
	Digest string `json:"digest"`

	// SizeBytes Unsigned 64-bit advisory estimate of the decoded payload length in bytes for the deployment YAML. Provided for planning or progress display. MUST NOT be used for integrity; digest verification remains mandatory.
	SizeBytes *float32 `json:"sizeBytes,omitempty"`

	// Url Content-addressable endpoint of the form /api/v1/clients/{clientId}/deployments/{deploymentId}/{digest}. The {digest} MUST equal deployments[].digest; the referenced resource is immutable
	Url string `json:"url"`
}

// DeploymentStatusManifest defines model for DeploymentStatusManifest.
type DeploymentStatusManifest struct {
	ApiVersion   string                       `json:"apiVersion"`
	Components   []ComponentStatus            `json:"components"`
	DeploymentId string                       `json:"deploymentId"`
	DeviceId     *DeviceId                    `json:"deviceId,omitempty"`
	Kind         DeploymentStatusManifestKind `json:"kind"`
	Status       struct {
		Error *struct {
			Code    *string `json:"code,omitempty"`
			Message *string `json:"message,omitempty"`
			Source  *string `json:"source,omitempty"`
		} `json:"error,omitempty"`
		State DeploymentStatusManifestStatusState `json:"state"`
	} `json:"status"`
}

// DeploymentStatusManifestKind defines model for DeploymentStatusManifest.Kind.
type DeploymentStatusManifestKind string

// DeploymentStatusManifestStatusState defines model for DeploymentStatusManifest.Status.State.
type DeploymentStatusManifestStatusState string

// DeviceCapabilitiesManifest defines model for DeviceCapabilitiesManifest.
type DeviceCapabilitiesManifest struct {
	ApiVersion string                         `json:"apiVersion"`
	Kind       DeviceCapabilitiesManifestKind `json:"kind"`

	// Labels Optional supplier-defined key/value pair metadata used for device matching via eligibilityRules label selectors. Values MUST be a string, number, boolean, or an array of strings or numbers. Margo does not assign semantics to any particular label key or value. Label keys are case-sensitive. Implementations SHOULD use stable, collision-resistant label names, prefixing with an organization domain is recommended.
	Labels     *map[string]DeviceCapabilitiesManifest_Labels_AdditionalProperties `json:"labels,omitempty"`
	Properties struct {
		Cpus *[]struct {
			Architecture *DeviceCapabilitiesManifestPropertiesCpusArchitecture `json:"architecture,omitempty"`
			Cores        float32                                               `json:"cores"`
		} `json:"cpus,omitempty"`
		Id                       DeviceId                                                        `json:"id"`
		Interfaces               *[]DeviceCommunicationInterface                                 `json:"interfaces,omitempty"`
		Memory                   *string                                                         `json:"memory,omitempty"`
		ModelNumber              string                                                          `json:"modelNumber"`
		OtelCollector            *bool                                                           `json:"otelCollector,omitempty"`
		Peripherals              *[]DevicePeripheral                                             `json:"peripherals,omitempty"`
		SerialNumber             string                                                          `json:"serialNumber"`
		Storage                  *string                                                         `json:"storage,omitempty"`
		SupportedDeploymentTypes *[]DeviceCapabilitiesManifestPropertiesSupportedDeploymentTypes `json:"supportedDeploymentTypes,omitempty"`
		SupportedRuntimes        *[]DeviceCapabilitiesManifestPropertiesSupportedRuntimes        `json:"supportedRuntimes,omitempty"`
		Vendor                   string                                                          `json:"vendor"`
	} `json:"properties"`
}

// DeviceCapabilitiesManifestKind defines model for DeviceCapabilitiesManifest.Kind.
type DeviceCapabilitiesManifestKind string

// DeviceCapabilitiesManifestLabels0 defines model for DeviceCapabilitiesManifest.Labels.0.
type DeviceCapabilitiesManifestLabels0 = string

// DeviceCapabilitiesManifestLabels1 defines model for DeviceCapabilitiesManifest.Labels.1.
type DeviceCapabilitiesManifestLabels1 = float32

// DeviceCapabilitiesManifestLabels2 defines model for DeviceCapabilitiesManifest.Labels.2.
type DeviceCapabilitiesManifestLabels2 = bool

// DeviceCapabilitiesManifestLabels3 defines model for DeviceCapabilitiesManifest.Labels.3.
type DeviceCapabilitiesManifestLabels3 = []string

// DeviceCapabilitiesManifestLabels4 defines model for DeviceCapabilitiesManifest.Labels.4.
type DeviceCapabilitiesManifestLabels4 = []float32

// DeviceCapabilitiesManifest_Labels_AdditionalProperties defines model for DeviceCapabilitiesManifest.labels.AdditionalProperties.
type DeviceCapabilitiesManifest_Labels_AdditionalProperties struct {
	union json.RawMessage
}

// DeviceCapabilitiesManifestPropertiesCpusArchitecture defines model for DeviceCapabilitiesManifest.Properties.Cpus.Architecture.
type DeviceCapabilitiesManifestPropertiesCpusArchitecture string

// DeviceCapabilitiesManifestPropertiesSupportedDeploymentTypes defines model for DeviceCapabilitiesManifest.Properties.SupportedDeploymentTypes.
type DeviceCapabilitiesManifestPropertiesSupportedDeploymentTypes string

// DeviceCapabilitiesManifestPropertiesSupportedRuntimes defines model for DeviceCapabilitiesManifest.Properties.SupportedRuntimes.
type DeviceCapabilitiesManifestPropertiesSupportedRuntimes string

// DeviceCommunicationInterface defines model for DeviceCommunicationInterface.
type DeviceCommunicationInterface struct {
	Type DeviceCommunicationInterfaceType `json:"type"`
}

// DeviceCommunicationInterfaceType defines model for DeviceCommunicationInterface.Type.
type DeviceCommunicationInterfaceType string

// DeviceConstraints Device constraints specifying the minimum device capabilities and eligibility rules required for the deployment.
type DeviceConstraints struct {
	// CapacityRequirements Minimum CPU, memory, and storage requirements for the deployment profile.
	CapacityRequirements *CapacityRequirements `json:"capacityRequirements,omitempty"`

	// EligibilityRules Optional rules used to match the deployment with device properties and supplier-defined labels reported in the device capabilities.
	EligibilityRules *[]EligibilityRule `json:"eligibilityRules,omitempty"`
}

// DeviceId defines model for DeviceId.
type DeviceId = string

// DeviceIdWithAsterisk defines model for DeviceId_with_asterisk.
type DeviceIdWithAsterisk = string

// DevicePeripheral defines model for DevicePeripheral.
type DevicePeripheral struct {
	Manufacturer *string              `json:"manufacturer,omitempty"`
	Model        *string              `json:"model,omitempty"`
	Type         DevicePeripheralType `json:"type"`
}

// DevicePeripheralType defines model for DevicePeripheral.Type.
type DevicePeripheralType string

// EligibilityRule A rule matching properties and supplier-defined labels reported through the device capabilities.
type EligibilityRule struct {
	// LabelSelector Selector evaluated against the labels reported in the device capabilities.
	LabelSelector *Selector `json:"labelSelector,omitempty"`

	// PropertySelector Selector evaluated against the properties reported in the device capabilities.
	PropertySelector *Selector `json:"propertySelector,omitempty"`
}

// ManifestVersion Monotonically increasing unsigned 64-bit integer in the inclusive range [1, 2^64-1]. Prevents rollback attacks. The first manifest MUST use 1.
type ManifestVersion = float32

// MatchExpression An expression used to match a device's reported capabilities properties or labels.
type MatchExpression struct {
	// ItemSelector A set of match expressions evaluated with AND semantics.
	ItemSelector *Selector `json:"itemSelector,omitempty"`

	// Key The key used to match the device's reported capabilities. For property selectors, this MUST be a JSON Pointer, as defined by RFC 6901, mapping to a specific property. For label selectors, this MUST be the exact label key.
	Key string `json:"key"`

	// Operator Operator used to evaluate the referenced value.
	Operator MatchExpressionOperator `json:"operator"`

	// Values Values used by the operator when required for matching expressions. Required for the `In`, `NotIn`, `Gt`, or `Lt` operator.
	Values *[]interface{} `json:"values,omitempty"`
}

// MatchExpressionOperator Operator used to evaluate the referenced value.
type MatchExpressionOperator string

// Selector A set of match expressions evaluated with AND semantics.
type Selector struct {
	// MatchExpressions Match expressions evaluated against the device's reported capabilities.
	MatchExpressions []MatchExpression `json:"matchExpressions"`
}

// UnsignedAppStateManifest defines model for UnsignedAppStateManifest.
type UnsignedAppStateManifest struct {
	// Bundle Describes a single archive containing all ApplicationDeployment documents. If there are zero deployments (deployments array is empty) the property MUST be present with the value null (it MUST NOT be omitted).
	Bundle *DeploymentBundleRef `json:"bundle"`

	// Deployments A list of deployment object references for the device. The reference contains some meta info and reference to the url where the deployment is available.
	Deployments []DeploymentManifestRef `json:"deployments"`

	// ManifestVersion Monotonically increasing unsigned 64-bit integer in the inclusive range [1, 2^64-1]. Prevents rollback attacks. The first manifest MUST use 1.
	ManifestVersion ManifestVersion `json:"manifestVersion"`
}

// AppDeploymentManifest Application Deployment manifest
type AppDeploymentManifest struct {
	// ApiVersion API version
	ApiVersion string `json:"apiVersion"`

	// Id Unique identifier for the application deployment
	Id *string `json:"id,omitempty"`

	// Kind Resource kind
	Kind     string                `json:"kind"`
	Metadata AppDeploymentMetadata `json:"metadata"`

	// Spec Application Deployment specification
	Spec AppDeploymentSpec `json:"spec"`
}

// AppDeploymentMetadata defines model for appDeploymentMetadata.
type AppDeploymentMetadata struct {
	// DeviceId Device ID of the target device for the deployment
	DeviceId DeviceIdWithAsterisk `json:"deviceId"`

	// Labels Labels for the resource
	Labels *map[string]string `json:"labels,omitempty"`

	// Name Name of the resource
	Name string `json:"name"`

	// Namespace Namespace of the resource
	Namespace string `json:"namespace"`
}

// AppDeploymentParams Application Parameters
type AppDeploymentParams map[string]AppParameterValue

// AppDeploymentProfile Application Deployment Profile
type AppDeploymentProfile struct {
	// Components Components of the deployment profile
	Components []ApplicationDeploymentProfileComponent `json:"components"`

	// DeviceConstraints Device constraints specifying the minimum device capabilities and eligibility rules required for the deployment.
	DeviceConstraints *DeviceConstraints `json:"deviceConstraints,omitempty"`

	// Type Type of deployment profile
	Type AppDeploymentProfileType `json:"type"`
}

// AppDeploymentProfileType Type of deployment profile
type AppDeploymentProfileType string

// AppDeploymentSpec Application Deployment specification
type AppDeploymentSpec struct {
	// ApplicationId An identifier for the application. The id is used to help create unique identifiers where required, such as namespaces. The id must be lower case letters and numbers and MAY contain dashes. Uppercase letters, underscores and periods MUST NOT be used. The id MUST NOT be more than 200 characters. The applicationId MUST match the associated application description's top-level "id" attribute.
	ApplicationId string `json:"applicationId"`

	// DeploymentProfile Deployment profile
	DeploymentProfile AppDeploymentProfile `json:"deploymentProfile"`

	// Parameters Parameters for the deployment
	Parameters *AppDeploymentParams `json:"parameters,omitempty"`
}

// AppParameterTarget Application Parameter Target
type AppParameterTarget struct {
	// Components Components of the parameter
	Components []string `json:"components"`

	// Pointer Pointer to the parameter
	Pointer string `json:"pointer"`
}

// AppParameterValue Application Parameter Value
type AppParameterValue struct {
	// Targets Targets of the parameter
	Targets []AppParameterTarget `json:"targets"`

	// Value Value of the parameter
	Value interface{} `json:"value"`
}

// ApplicationDeploymentProfileComponent A component within a deployment profile. Uses the unified ComponentProperties shape — both Helm and Compose components share the same OCI coordinate structure.
type ApplicationDeploymentProfileComponent struct {
	// Name Name of the component
	Name       string `json:"name"`
	Properties struct {
		// Repository OCI repository URI for the component package (e.g., oci://registry.example.com/org/component-name). MUST be a valid OCI reference using the oci:// scheme.
		Repository string `json:"repository"`

		// Revision OCI tag identifying the component version. MUST be a valid SemVer 2.0 string without leading v. Build metadata uses _ as separator instead of +.
		Revision string `json:"revision"`

		// Timeout Maximum time to wait for component installation to complete. Format is ##m##s (e.g., 5m0s, 8m30s).
		Timeout *string `json:"timeout,omitempty"`

		// Wait Whether to wait for component installation to complete before proceeding. Default is true. Only applies when multiple components are provided.
		Wait *bool `json:"wait,omitempty"`
	} `json:"properties"`
}

// GetApiV1ClientsClientIdBundlesDigestParams defines parameters for GetApiV1ClientsClientIdBundlesDigest.
type GetApiV1ClientsClientIdBundlesDigestParams struct {
	// IfNoneMatch Quoted ETag (same as digest) previously returned for this bundle.
	IfNoneMatch *string `json:"If-None-Match,omitempty"`
}

// GetApiV1ClientsClientIdDeploymentsParams defines parameters for GetApiV1ClientsClientIdDeployments.
type GetApiV1ClientsClientIdDeploymentsParams struct {
	// IfNoneMatch ETag value of the last successfully synced manifest. The ETag is returned to the client from the /deployments endpoint, it is the digest of the state manifest.
	IfNoneMatch *string `json:"If-None-Match,omitempty"`

	// Accept Indicates which manifest formats the client supports. Supported values: application/vnd.margo.manifest.v1+json.
	Accept *string `json:"Accept,omitempty"`
}

// GetApiV1ClientsClientIdDeploymentsDeploymentIdDigestParams defines parameters for GetApiV1ClientsClientIdDeploymentsDeploymentIdDigest.
type GetApiV1ClientsClientIdDeploymentsDeploymentIdDigestParams struct {
	// IfNoneMatch Optional ETag for caching. The ETag is returned to the client from the /deployments endpoint, it is the digest of the state manifest.
	IfNoneMatch *string `json:"If-None-Match,omitempty"`

	// AcceptEncoding Indicates supported compression formats (e.g., gzip, br)
	AcceptEncoding *string `json:"Accept-Encoding,omitempty"`
}

// PostApiV1OnboardingJSONBody defines parameters for PostApiV1Onboarding.
type PostApiV1OnboardingJSONBody struct {
	// ApiVersion API version identifier
	ApiVersion string `json:"apiVersion"`

	// Certificate Base64-encoded client certificate
	Certificate string `json:"certificate"`

	// Kind Resource kind
	Kind PostApiV1OnboardingJSONBodyKind `json:"kind"`
}

// PostApiV1OnboardingJSONBodyKind defines parameters for PostApiV1Onboarding.
type PostApiV1OnboardingJSONBodyKind string

// PostApiV1ClientsClientIdCapabilitiesDeviceIdJSONRequestBody defines body for PostApiV1ClientsClientIdCapabilitiesDeviceId for application/json ContentType.
type PostApiV1ClientsClientIdCapabilitiesDeviceIdJSONRequestBody = DeviceCapabilitiesManifest

// PutApiV1ClientsClientIdCapabilitiesDeviceIdJSONRequestBody defines body for PutApiV1ClientsClientIdCapabilitiesDeviceId for application/json ContentType.
type PutApiV1ClientsClientIdCapabilitiesDeviceIdJSONRequestBody = DeviceCapabilitiesManifest

// PostApiV1ClientsClientIdDeploymentsDeploymentIdStatusJSONRequestBody defines body for PostApiV1ClientsClientIdDeploymentsDeploymentIdStatus for application/json ContentType.
type PostApiV1ClientsClientIdDeploymentsDeploymentIdStatusJSONRequestBody = DeploymentStatusManifest

// PostApiV1OnboardingJSONRequestBody defines body for PostApiV1Onboarding for application/json ContentType.
type PostApiV1OnboardingJSONRequestBody PostApiV1OnboardingJSONBody

// AsDeviceCapabilitiesManifestLabels0 returns the union data inside the DeviceCapabilitiesManifest_Labels_AdditionalProperties as a DeviceCapabilitiesManifestLabels0
func (t DeviceCapabilitiesManifest_Labels_AdditionalProperties) AsDeviceCapabilitiesManifestLabels0() (DeviceCapabilitiesManifestLabels0, error) {
	var body DeviceCapabilitiesManifestLabels0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromDeviceCapabilitiesManifestLabels0 overwrites any union data inside the DeviceCapabilitiesManifest_Labels_AdditionalProperties as the provided DeviceCapabilitiesManifestLabels0
func (t *DeviceCapabilitiesManifest_Labels_AdditionalProperties) FromDeviceCapabilitiesManifestLabels0(v DeviceCapabilitiesManifestLabels0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeDeviceCapabilitiesManifestLabels0 performs a merge with any union data inside the DeviceCapabilitiesManifest_Labels_AdditionalProperties, using the provided DeviceCapabilitiesManifestLabels0
func (t *DeviceCapabilitiesManifest_Labels_AdditionalProperties) MergeDeviceCapabilitiesManifestLabels0(v DeviceCapabilitiesManifestLabels0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsDeviceCapabilitiesManifestLabels1 returns the union data inside the DeviceCapabilitiesManifest_Labels_AdditionalProperties as a DeviceCapabilitiesManifestLabels1
func (t DeviceCapabilitiesManifest_Labels_AdditionalProperties) AsDeviceCapabilitiesManifestLabels1() (DeviceCapabilitiesManifestLabels1, error) {
	var body DeviceCapabilitiesManifestLabels1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromDeviceCapabilitiesManifestLabels1 overwrites any union data inside the DeviceCapabilitiesManifest_Labels_AdditionalProperties as the provided DeviceCapabilitiesManifestLabels1
func (t *DeviceCapabilitiesManifest_Labels_AdditionalProperties) FromDeviceCapabilitiesManifestLabels1(v DeviceCapabilitiesManifestLabels1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeDeviceCapabilitiesManifestLabels1 performs a merge with any union data inside the DeviceCapabilitiesManifest_Labels_AdditionalProperties, using the provided DeviceCapabilitiesManifestLabels1
func (t *DeviceCapabilitiesManifest_Labels_AdditionalProperties) MergeDeviceCapabilitiesManifestLabels1(v DeviceCapabilitiesManifestLabels1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsDeviceCapabilitiesManifestLabels2 returns the union data inside the DeviceCapabilitiesManifest_Labels_AdditionalProperties as a DeviceCapabilitiesManifestLabels2
func (t DeviceCapabilitiesManifest_Labels_AdditionalProperties) AsDeviceCapabilitiesManifestLabels2() (DeviceCapabilitiesManifestLabels2, error) {
	var body DeviceCapabilitiesManifestLabels2
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromDeviceCapabilitiesManifestLabels2 overwrites any union data inside the DeviceCapabilitiesManifest_Labels_AdditionalProperties as the provided DeviceCapabilitiesManifestLabels2
func (t *DeviceCapabilitiesManifest_Labels_AdditionalProperties) FromDeviceCapabilitiesManifestLabels2(v DeviceCapabilitiesManifestLabels2) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeDeviceCapabilitiesManifestLabels2 performs a merge with any union data inside the DeviceCapabilitiesManifest_Labels_AdditionalProperties, using the provided DeviceCapabilitiesManifestLabels2
func (t *DeviceCapabilitiesManifest_Labels_AdditionalProperties) MergeDeviceCapabilitiesManifestLabels2(v DeviceCapabilitiesManifestLabels2) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsDeviceCapabilitiesManifestLabels3 returns the union data inside the DeviceCapabilitiesManifest_Labels_AdditionalProperties as a DeviceCapabilitiesManifestLabels3
func (t DeviceCapabilitiesManifest_Labels_AdditionalProperties) AsDeviceCapabilitiesManifestLabels3() (DeviceCapabilitiesManifestLabels3, error) {
	var body DeviceCapabilitiesManifestLabels3
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromDeviceCapabilitiesManifestLabels3 overwrites any union data inside the DeviceCapabilitiesManifest_Labels_AdditionalProperties as the provided DeviceCapabilitiesManifestLabels3
func (t *DeviceCapabilitiesManifest_Labels_AdditionalProperties) FromDeviceCapabilitiesManifestLabels3(v DeviceCapabilitiesManifestLabels3) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeDeviceCapabilitiesManifestLabels3 performs a merge with any union data inside the DeviceCapabilitiesManifest_Labels_AdditionalProperties, using the provided DeviceCapabilitiesManifestLabels3
func (t *DeviceCapabilitiesManifest_Labels_AdditionalProperties) MergeDeviceCapabilitiesManifestLabels3(v DeviceCapabilitiesManifestLabels3) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsDeviceCapabilitiesManifestLabels4 returns the union data inside the DeviceCapabilitiesManifest_Labels_AdditionalProperties as a DeviceCapabilitiesManifestLabels4
func (t DeviceCapabilitiesManifest_Labels_AdditionalProperties) AsDeviceCapabilitiesManifestLabels4() (DeviceCapabilitiesManifestLabels4, error) {
	var body DeviceCapabilitiesManifestLabels4
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromDeviceCapabilitiesManifestLabels4 overwrites any union data inside the DeviceCapabilitiesManifest_Labels_AdditionalProperties as the provided DeviceCapabilitiesManifestLabels4
func (t *DeviceCapabilitiesManifest_Labels_AdditionalProperties) FromDeviceCapabilitiesManifestLabels4(v DeviceCapabilitiesManifestLabels4) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeDeviceCapabilitiesManifestLabels4 performs a merge with any union data inside the DeviceCapabilitiesManifest_Labels_AdditionalProperties, using the provided DeviceCapabilitiesManifestLabels4
func (t *DeviceCapabilitiesManifest_Labels_AdditionalProperties) MergeDeviceCapabilitiesManifestLabels4(v DeviceCapabilitiesManifestLabels4) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t DeviceCapabilitiesManifest_Labels_AdditionalProperties) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *DeviceCapabilitiesManifest_Labels_AdditionalProperties) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsHelmApplicationDeploymentProfileComponent returns the union data inside the AppDeploymentProfile_Components_Item as a HelmApplicationDeploymentProfileComponent
func (t AppDeploymentProfile_Components_Item) AsHelmApplicationDeploymentProfileComponent() (HelmApplicationDeploymentProfileComponent, error) {
	var body HelmApplicationDeploymentProfileComponent
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromHelmApplicationDeploymentProfileComponent overwrites any union data inside the AppDeploymentProfile_Components_Item as the provided HelmApplicationDeploymentProfileComponent
func (t *AppDeploymentProfile_Components_Item) FromHelmApplicationDeploymentProfileComponent(v HelmApplicationDeploymentProfileComponent) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeHelmApplicationDeploymentProfileComponent performs a merge with any union data inside the AppDeploymentProfile_Components_Item, using the provided HelmApplicationDeploymentProfileComponent
func (t *AppDeploymentProfile_Components_Item) MergeHelmApplicationDeploymentProfileComponent(v HelmApplicationDeploymentProfileComponent) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsComposeApplicationDeploymentProfileComponent returns the union data inside the AppDeploymentProfile_Components_Item as a ComposeApplicationDeploymentProfileComponent
func (t AppDeploymentProfile_Components_Item) AsComposeApplicationDeploymentProfileComponent() (ComposeApplicationDeploymentProfileComponent, error) {
	var body ComposeApplicationDeploymentProfileComponent
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromComposeApplicationDeploymentProfileComponent overwrites any union data inside the AppDeploymentProfile_Components_Item as the provided ComposeApplicationDeploymentProfileComponent
func (t *AppDeploymentProfile_Components_Item) FromComposeApplicationDeploymentProfileComponent(v ComposeApplicationDeploymentProfileComponent) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeComposeApplicationDeploymentProfileComponent performs a merge with any union data inside the AppDeploymentProfile_Components_Item, using the provided ComposeApplicationDeploymentProfileComponent
func (t *AppDeploymentProfile_Components_Item) MergeComposeApplicationDeploymentProfileComponent(v ComposeApplicationDeploymentProfileComponent) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t AppDeploymentProfile_Components_Item) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *AppDeploymentProfile_Components_Item) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}
