name: Build & Push Workload Fleet Management Client Image

on:
  push:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Verify Docker
        run: docker --version

      - name: Build & push image to GHCR
        env:
          GITHUB_ORG: margo
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB}}
          GITHUB_ACTOR: ${{ github.actor }}
        run: |
          chmod +x scripts/build-workload-fleet-client.sh
          ./scripts/build-workload-fleet-client.sh
