name: Azure VM SSH Login

on:
  push:
    branches:
      - TestAutomation  # This workflow will still be triggered on pushes to the `dev` branch
  workflow_dispatch:  # This allows manual triggering of the workflow
jobs:

  ssh-login:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up environment variables from .env file
        run: |
          # Load environment variables from the .env file
          echo "Loading .env variables..."
          set -o allexport
          source .env
          set +o allexport

      - name: Install SSH client and sshpass
        run: sudo apt-get install -y openssh-client sshpass

      - name: Add VM's SSH key to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H $VM_HOST >> ~/.ssh/known_hosts

      - name: Log in to Azure VM using SSH
        run: |
          # Use sshpass to authenticate using username/password
          sshpass -p $AZURE_VM_PASSWORD ssh -o StrictHostKeyChecking=no $AZURE_VM_USERNAME@$VM_HOST "echo 'Logged in successfully!'"
