name: Code Style Check

on:
  pull_request:

jobs:
  gofmt:
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.25'

      - name: Check Go code format
        run: find . -type f -name "*.go" -exec gofmt -l {} \;

      - name: Check Go code subtle issues
        run: go vet ./...
